export const EVENT_NAMES = Object.freeze({
    downloadClicked: "downloadClicked",
    blockyBlockCreate: "blocklyBlockCreate",
    blocklyBlockDelete: "blocklyBlockDelete",
    blocklyBlockMove: "blocklyBlockMove",
    blocklyVarCreate: "blocklyVarCreate",
    blocklyVarDelete: "blocklyVarDelete",
    blocklyVarRename: "blocklyVarRename",
    blocklyUI: "blocklyUI",
    blocklyChange: "blocklyChange",
    undo: "undo",
    uploadClicked: "uploadClicked",
    simButtonStateClicked: "simButtonStateClicked",
    runClicked: "runClicked",
    changedWorkspace: "changedWorkspace",
    downloadScenarioClicked: "downloadScenarioClicked",
    moveRobotComponent: "moveRobotComponent",
    addRobotComponent: "addRobotComponent",
    removeRobotComponent: "removeRobotComponent",
    addRobotComponent: "addRobotComponent",
    changedScenario: "changedScenario",
    simStart: "simStart",
    simResume: "simResume",
    simPause: "simPause",
    simStopButtonClicked: "simStopButtonClicked",
    simStep: "simStep",
    simStop: "simStop",
    setSpeed: "setSpeed",
    startTutorial: "startTutorial",
    endTutorial: "endTutorial",
    tutorialNextStep: "tutorialNextStep", 
    tutorialPrevStep: "tutorialPrevStep",

});