var MSG = {
  arduinoCodeCopied: "Arduino code copied to clipboard",
  title: "دوينجوينو بلوكلي",
  blocks: " كتل  ",
  linkTooltip: " حفظ وربط الكتل. ",
  runTooltip: "  قم بتشغيل البرنامج المحدد بواسطة الكتل في مساحة العمل ",
  loadBlocksFileTooltip: " قم بتحميل ملف كتل قمت بحفظه من قبل  ",
  saveBlocksFileTooltip:  "  احفظ الكتل في ملف محلي ",
  toggleSimulator: " تبديل عرض المحاكاة  ",
  badCode:  "خطأ في البرنامج: \ n 1%   ",
  timeout: "تم تجاوز الحد الأقصى لتكرارات التنفيذ.  ",
  trashTooltip: " تجاهل كل الكتل.  ",
  catLogic: " منطق  ",
  catLoops: "الحلقات   ",
  catMath: " رياضيات  ",
  catText: "نص",
  catLists: " القوائم  ",
  catColour: " اللون  ",
  catArduino: " اردوينو  ",
  catVariables: " المتغيرات  ",
  catFunctions: " المهام  ",
  catDwenguino: " دوينجوينو  ",
  catSocialRobot: " روبوت اجتماعي  ",
  catComments:  " تعليقات  ",
  catBoardIO: " أيو  ",
  createVar: " إنشاء متغير  ",
  listVariable: " قائمة ",
  textVariable: " نص  ",
  httpRequestError: " كانت هناك مشكلة مع هذا الطلب.  ",
  linkAlert: " شارك الكتل الخاصة بك مع هذا الارتباط: \ n \ n%1  ",
  hashError: " أوري ، %1 لا يتوافق مع أي برنامج محفوظ.  ",
  xmlError: "الكتل  لا يمكن تحميل الملف المحفوظ الخاص بك. ربما تم إنشاؤه باستخدام إصدار مختلف من ",
  badXml: " خطأ في تحليل : \n %1 \n \n حدد موافق للتخلي عن التغييرات أو إلغاء لمزيد من تحرير XML.  ",
  setup: " اقامة  ",
  loop: " عقدة",
  dwenguino_main_program_structure: " يتم تنفيذ الكود الموجود في كتلة الإعداد مرة واحدة في بداية البرنامج. يتم تكرار الكود في الحلقة حتى يتوقف البرنامج.  ",
  catDwenguino: "  دوينجوينو ",
  delay_help: " انتظر مقدارًا محددًا من المللي ثانية (ثانية واحدة = 1000 مللي ثانية)  ",
  delay: " تأخير  ",
  clearLCD: " شاشة  واضحة  ",
  dwenguinoLCD: " دوينجوينو %1%2%3 كتابة نص: %4 في الصف: %5 يبدأ من العمود: %6 ",
  pin: " دبوس  ",
  toneOnPin: " تشغيل النغمة  ",
  frequency: " مع التردد  ",
  noToneOnPin: " توقف عن النغمة  ",
  toneOnPinTooltip: "تشغيل النغمة بتردد محدد على الدبوس المحدد  ",
  noToneOnPinTooltip: "  توقف النغمة على دبوس ",
  trig: " رقم دبوس حساب المثلثات  ",
  echo:  " رقم الصدى السري  ",
  sonarTooltip: " يقرأ هذا المستشعر المسافة من مستشعر السونار  ",
  pirTooltip: " يمكن لهذا المستشعر اكتشاف الحركة  ",
  miliseconds: "  مس ",
  digitalRead: " اقرأ القيمة الرقمية من  ",
  digitalWriteToPin: "اكتب على   ",
  digitalWriteValue: "  القيمة الرقمية ",
  digitalWriteTooltip: "  اكتب قيمة عالية أو منخفضة إلى دبوس رقمي من لوحة ",
  digitalReadTooltip: " اقرأ قيمة رقمية (1 / مرتفع أو 0 / منخفض) من دبوس محدد  ",
  high: " عالي  ",
  low: " منخفض  ",
  highLowTooltip:  " يمثل قيمة عالية (1) أو منخفضة (0) على دبوس.  ",
  tutsIntroduction: " المقدمة  ",
  tutsTheremin: " الثيرمين  ",
  tutsRobot: " إنسان آلي  ",
  tutsHelloDwenguino:  " مرحبا دوينجوينو!  ",
  tutsNameOnLcd: " الاسم على شاشات الكريستال السائل ",
  tutsBlinkLED: " رمش شاشات الكريستال السائل  ",
  tutsLedOnButtonPress: " شاشات الكريستال السائل عند الضغط على الزر   ",
  tutsBitPatternOnLeds: " نمط البت يعمل شاشات الكريستال السائل  ",
  tutsAllButtons: " كل الأزرار  ",
  tutsDriveForward: " قد للأمام  ",
  tutsRideInSquare: " ركوب مربع  ",
  tutsRideToWall: " اركب إلى الحائط  ",
  tutsAvoidWall: " تجنب الجدار  ",
  tutsNameOnLcdBasic: " اسمك على شاشات الكريستال السائل ",
  simulator: "  محاكي ",
  setLedState: "تحويل %1%2   ",
  setLedStateTooltip: "قم بتشغيل أو إيقاف تشغيل مؤشر شاشات الكريستال السائل على لوحة دوينجوينو   ",
  ledPinsTooltip: " اختر مؤشر شاشات الكريستال السائل الذي تريد التحكم فيه  ",
  dwenguinoOn: " افتح  ",
  dwenguinoOff: "  إيقاف ",
  dwenguinoOnOffTooltip: " حدد قيمة لتشغيل أو إيقاف تشغيل شاشات الكريستال السائل ",
  dwenguinoLedBlock: "شاشات الكريستال السائل " ,
  dwenguinoSonarBlock: " السونار%1%2%3 رقم الدبوس الثلاثي%4 رقم دبوس الصدى%5 ",
  dwenguinoServoBlock: "  محرك سيرفو %1%2%3 قناة # %4 زاوية%5 ",
  dwenguinoServoDropdownBlock: "محرك سيرفو %1",
  dwenguinoServoBlockTooltip: " اضبط إحدى الماكينات المتصلة بـ دوينجوينو بزاوية محددة بين 0 و 180 درجة  ",
  dwenguinoServoOne: "1",
  dwenguinoServoTwo: "2",
  dwenguinoServoBlockTooltip: " اضبط إحدى الماكينات المتصلة بـ دوينجوينو بزاوية محددة بين 0 و 180 درجة  ",
  dwenguinoDCMotorBlock: " محرك التيار المستمر%1%2%3 القناة %4 السرعة %5  ",
  dwenguinoDCMotorBlockTooltip: " اضبط سرعة أحد محركاتي دوينجوينو. السرعة = القيمة بين -255 (السرعة الكاملة للخلف) و 255 (السرعة الكاملة للأمام)  ",
  dwenguinoAnalogWrite: " اكتب إلى القيمة التناظرية %1% 2  ",
  dwenguinoAnalogWriteTooltip: " اكتب قيمة تناظرية بين 0 و 255 للدبوس المحدد  ",
  dwenguinoAnalogRead: "قراءة القيمة التناظرية من %1 ",
  dwenguinoAnalogWriteTooltip: " اقرأ قيمة بين 0 و 255 من الدبوس المحدد  ",
  digitalReadSwitch: " قراءة مفتاح التبديل %1",
  digitalReadSwitchTooltip: " اقرأ القيمة من أحد مفاتيح تبديل دوينجوينو  ",
  waitForSwitch: " انتظر حتى يتم الضغط على الزر %1 ",
  north: " شمال  ",
  east: " الشرق  ",
  south:  " جنوب  ",
  west: " الغرب  ",
  center: " مركز  ",
  ledsReg:  " شاشات الكريستال السائل  ",
  dwenguinoLedsRegTooltip: " يمكنك تشغيل المصابيح من 0 إلى 7 باستخدام رقم ثنائي. على سبيل المثال ، سوف يقوم 0b00001111 بتشغيل المصابيح من 0 إلى 3 وإيقاف الباقي  ",
  pressed: " تم الضغط عليه  ",
  notPressed: " غير مضغوط  ",
  pressedTooltip: " يمثل حالة الزر. استخدم هذه القيم للمقارنة بحالة الزر الفعلية  ",
  sureYouWantToChangeTutorial: "  هل تريد بالتأكيد بدء هذا البرنامج التعليمي؟ \ n ستتم إزالة كافة الكتل الموجودة في مساحة العمل الحالية. ",
  create:  " خلق  ",
  with_type:  " مع النوع  ",
  create_global: " خلق عالمية  ",
  socialRobotRgbLedBlock: " آر جي بي شاشات الكريستال السائل  ",
  socialRobotPinRed: " دبوس أحمر  ",
  socialRobotPinGreen: " دبوس أخضر " ,
  socialRobotPinBlue: " دبوس أزرق ",
  socialRobotRgbLedOffBlock: " قم بإيقاف تشغيل آر جي بي شاشات الكريستال السائل باستخدام   ",
  socialRobotRgbColorBlock: " %1 لون آر جي بي ",
  socialRobotRgbColor: "red %1 green %2 blue %3",
  socialRobotLedmatrixImageBlock: "Display pattern on LED matrix segment",
  socialRobotLedmatrixImageBlockTooltip: "Show the given led pattern on the LED matrix display.",
  socialRobotLedmatrixEyePatternBlock: "Display eye pattern",
  socialRobotLedmatrixEyePatternBlockTooltip: 'Show the given eye pattern on the LED matrix display.',
  socialRobotLedmatrixEyePatternSegmentBlock: "on LED matrix segment",
  socialRobotLedmatrixClearSegmentBlock: "Clear LED matrix segment",
  socialRobotLedmatrixClearSegmentBlockTooltip: 'Clear a segment of the LED matrix display.',
  socialRobotLedmatrixClearDisplayBlock: "Clear LED matrix",
  socialRobotLedmatrixClearDisplayBlockTooltip: 'Clear the complete LED matrix display.',
  socialrobotPirBlock: " بير  ",
  socialRobotSoundSensorBlock: "Sound sensor %1 %2 %3 pin %4",
  socialRobotSoundSensorBlockTooltip: "",
  socialRobotTouchSensorBlock: "Touch sensor %1 %2 %3 pin %4",
  socialRobotTouchSensorBlockTooltip: "",
  socialRobotButtonBlock: "Button %1 %2 %3 pin %4",
  socialRobotButtonBlockTooltip: "",
  socialrobotSetPinState: " قم بتعيين %1%2  ",
  socialrobotServoBlock: "  محرك سيرفو %1%2%3 طرف %4 زاوية %5 ",
  socialrobotWaveArmesBlock: " أذرع الموجة%1%2 الذراع الأيمن للدبوس المؤازر %3%4 الذراع الأيسر المؤازر%5%6  ",
  socialRobotArmsDownBlock: " ضع الذراعين لأسفل%1%2%3 الذراع الأيمن للدبوس المؤازر%4%5 الذراع الأيسر للدبوس%6%7  ",
  socialRobotArmsUpBlock: " ارفع الذراعين%1%2%3 الذراع الأيمن للدبوس المؤازر%4%5 الذراع الأيسر للدبوس%6%7  ",
  socialRobotEyesLeftBlock: " أدر العينين لليسار%1%2%3 العين اليسرى للدبوس المؤازر%4%5 العين اليمنى بدبوس مضاعفات%6%7  ",
  socialRobotEyesRightBlock: " أدر العينين لليمين%1%2%3 العين اليسرى بدبوس مضاعفات%4%5 العين اليمنى بدبوس مضاعفات%6%7  ",
  socialrobotReadPinBlock: "قراءة قيمة الطرف%1%2 ",
  socialRobotServoRightHand: "أجهزة دبوس اليد اليمنى   ",
  socialRobotServoLeftHand: "المؤازرة دبوس اليد اليسرى   ",
  sonarSliderLabel: " مسافة السونار  ",
  pirButtonLabel: " PIR زر   ",
  soundButtonLabel: " زر الصوت  ",
  touchButtonLabel: "Touch button",
  lightSensorSliderLabel: " زر مستشعر الضوء  ",
  servoCostume: " زي  ",
  servoOptions: " خيارات محرك سيرفو  ",
  sonarOptions:  " خيارات مستشعر السونار  ",
  lcdOptions:  " خيارات شاشة  ",
  pirOptions: "PIR خيارات مستشعر   ",
  soundOptions: " خيارات مستشعر الصوت  ",
  touchOptions: "Touch sensor options",
  buttonOptions: "Button options",
  lightOptions: " خيارات مستشعر الضوء  ",
  rgbLedOptions: "RGB LED options",
  ledmatrixOptions: 'Led  Matrix Options',
  ledOptions:  "  خيارات ",
  runError: "<h3> معذرة ، لم أتمكن من تحميل الكود على اللوحة </ h3>   ", 
  uploadError: "اتبع هذه الخطوات لإعادة تشغيل لوحة Dwenguino: \ n 1. افصل كبل USB \ n 2. قم بتوصيل الكمبيوتر ولوحة Dwenguino بكبل USB \ n 3. اضغط في نفس الوقت على زر RESET والزر SOUTH بلوحة Dwenguino \ n 4 . ثم حرر زر RESET أولاً \ n 5. ثم حرر الزر SOUTH \ n 6. قم بتحميل البرنامج مرة أخرى عبر <span id = 'db_menu_item_run' class = 'fas fa-play-circle' alt = 'تحميل الكود إلى لوحة Dwenguino' > </span> في القائمة الرئيسية   ",
  cleanError:  " تعذر إزالة الرمز السابق. \ n الرجاء التحقق مما إذا كان هناك تطبيق آخر يستخدم أي ملفات .cpp. \ n أغلق التطبيق.  ",
  compileError: " تعذر تجميع الرمز. \ n يجب عليك التحقق من التعليمات البرمجية ، هل نسيت كتلة في مكان ما؟  ",
  clear: " واضح  ",
  save: "حفظ",
  dwenguinoStepperMotorBlock: "محرك متدرج %1%2%3 رقم %4 مقدار الخطوات %5  ",
  dwenguinoStepperMotorBlockTooltip: " تقوم هذه الكتلة بتحويل محرك السائر لعدد محدد من الخطوات ",
  drawingrobotMove: " حرك العلامة بزاوية مقدارها%1 درجة مع %2  ",
  drawingrobotMoveXY: " نقل العلامة %1 وحدة لليمين و %2   وحدة لليسار ",
  drawingrobotLine: "x: %1 y: %2 ارسم خطًا إلى",
  drawingrobotCircle:  "ارسم دائرة نصف قطرها: %1 " ,
  drawingrobotRectangle: "ارسم مستطيلاً من العرض: %1 والارتفاع: %2 ",
  drawingrobotLiftStylus: " رفع علامة ",
  drawingrobotLowerStylus: " علامة الإسقاط ",
  drawingrobotChangeColor: " اللون %1 ",
  up: " فوق ",
  down: "أسفل" ,
  left: "اليسار  ",
  right:  "حق" ,
  bounds: "انتباه \ أنت تحاول الرسم خارج قطعة الورق  ",
  drawingrobotgrid: " شبكة  ",
  colorpicker: " اللون ",
  drawingrobotSaveImage: " حفظ الرسم ",
  drawingrobotDrawing: "رسم  ",
  stepperMotorOne: " الخطوة 1 ", 
  stepperMotorTwo:  " الخطوة 2 ",
  stepperMotorTooltip:  " حدد أي محرك متدرج من روبوت الراسمة الذي تريد استخدامه. ",

};

MSG.cookieConsent = {
  close: "Close",
  cookieConsent: "We use functional cookies to set up the Dwenguino simulator. ",
  cookieInfo: "More info on how we use cookies.",
  whatAreCookiesTitle: "Wat zijn cookies?",
  whatAreCookiesDescription1: "Cookies zijn kleine tekstbestanden die lokaal worden opgeslagen op uw computer. Deze cookies dienen voor tal van doeleinden: het onthouden van instellingen (login, taalkeuzes), het vergaren van informatie en het bijhouden van het bezoekgedrag van de gebruikers.",
  whatAreCookiesDescription2: "De cookies die wij gebruiken zijn veilig: zij hebben geen toegang tot persoonlijke informatie op uw computer en kunnen deze niet beschadigen of besmetten met virussen. De cookies geven op geen enkele manier persoonlijke informatie aan ons door. De informatie die we via cookies verzamelen helpt ons om je van specifieke diensten te laten genieten.",
  whatAreNecessaryCookiesTitle: "Wat zijn noodzakelijke cookies?",
  whatAreNecessaryCookiesDescription: "Noodzakelijke cookies zijn cookies die je nodig hebt om te surfen op de website en gebruik te maken van de functionaliteit die we aanbieden. Bovendien zijn de cookies noodzakelijk om de beveiligde onderdelen van de website te kunnen zien.",
  whichCookiesTitle: "Welke cookies gebruikt deze website?",
  dwengoCookieTitle: "Aanmelden als gebruiker (Dwengo cookie)",
  dwengoCookieDescription: "Bij het aanmelden op de website wordt een tijdelijke cookie gebruikt waardoor je herkend wordt als gebruiker. Met behulp van deze cookie wordt onder andere je taalinstelling en vooruitgang bewaard. De cookie zorgt er voor dat je toegang hebt tot de beveiligde delen van de website. Deze cookie is slechts geldig tot aan het einde van de sessie en is enkel beschikbaar voor en gemaakt door Dwengo vzw.",
  jenkinsCookieTitle: "Jenkins configuratie (Jenkins cookie)",
  jenkinsCookieDescription: "De Jenkins cookie is voor ons noodzakelijk om de Dwenguino simulator online op een server te kunnen installeren. Jenkins is software waarvan we gebruik maken om onze simulator te updaten. Die cookie bevat informatie over de instellingen van Jenkins en bevat dus ook geen enkele informatie over jou als gebruiker.",
};

MSG.dropzone = {
  dictSelectFile: "حدد ملف.  ",
  dictChooseFile: " اختر ملف ",
  dictDefaultMessage: "قم بإسقاط الملفات هنا للتحميل  ",
  dictFallbackMessage:  "لا يدعم المستعرض الخاص بك تحميلات السحب والإفلات.  ",
  dictFileTooBig: " الملف كبير جدًا ({{حجم الملف}} ميغا بايت). الحد الأقصى لحجم الملف: {{الحد الأقصى لحجم الملف}} ميغا بايت. ",
  dictFallbackText: " يرجى استخدام النموذج الاحتياطي أدناه لتحميل ملفاتك كما في الأيام الخوالي. ",
  dictInvalidFileType: " لا يمكنك تحميل ملفات من هذا النوع. ",
  dictResponseError: " استجاب الخادم برمز {{رمز الحالة}}. ",
  dictCancelUpload: " إلغاء الرفع ",
  dictCancelUploadConfirmation: " هل أنت متأكد أنك تريد إلغاء هذا التحميل؟ ",
  dictRemoveFile: " إزالة الملف ",
  dictMaxFilesExceeded: "لا يمكنك تحميل المزيد من الملفات.  ",
  dictUploadBlocks: "Upload blocks",
  dictFileNotSupported: "This file is not supported.",
};

MSG.ledmatrix = {
  restPosition: 'Rest position', 
  blink1: 'Blink 1',
  blink2: 'Blink 2',
  blink3: 'Blink 3',
  blink4: 'Blink 4',
  blink5: 'Blink 5',
  right1: 'Right 1',
  right2: 'Right 2',
  left1: 'Left 1',
  left2: 'Left 2',
  up1: 'Up 1',
  up2: 'Up 2',
  up3: 'Up 3',
  down1: 'Down 1',
  down2: 'Down 2',
  down3: 'Down 3',
  angryLeft1: 'Angry left 1',
  angryLeft2: 'Angry left 2',
  angryLeft3: 'Angry left 3',
  angryLeft4: 'Angry left 4',
  angryRight1: 'Angry right 1',
  angryRight2: 'Angry right 2',
  angryRight3: 'Angry right 3',
  angryRight4: 'Angry right 4',
  sadLeft1: 'Sad left 1',
  sadLeft2: 'Sad left 2',
  sadLeft3: 'Sad left 3',
  sadRight1: 'Sad right 1',
  sadRight2: 'Sad right 2',
  sadRight3: 'Sad right 3',
  evilLeft1: 'Evil left 1',
  evilLeft2: 'Evil left 2',
  evilRight1: 'Evil right 1',
  evilRight2: 'Evil right 2',
  scanHorizontal1: 'Scan horizontal 1',
  scanHorizontal2: 'Scan horizontal 2',
  scanHorizontal3: 'Scan horizontal 3',
  scanHorizontal4: 'Scan horizontal 4',
  scanVertical1: 'Scan vertical 1',
  scanVertical2: 'Scan vertical 2',
  scanVertical3: 'Scan vertical 3',
  scanVertical4: 'Scan vertical 4',
  scanVertical5: 'Scan vertical 5',
  scanVertical6: 'Scan vertical 6',
  rip1: 'RIP 1',
  rip2: 'RIP 2',
  peering1: 'Peering 1',
  peering2: 'Peering 2',
  peering3: 'Peering 3',
  peering4: 'Peering 4'
};

MSG.simulator = {
  start: " بداية ",
  stop: "  قف",
  pause: "راحة  ",
  step: " خطوة ",
  speed: "سرعة  ",
  speedVerySlow: "40 مرة بطيئة  ",
  speedSlow: " 20 مرة بطيئة ",
  speedMedium: "10 مرات بطيئة  ",
  speedFast: "5 مرات بطيئة  ",
  speedVeryFast: " 2 مرات بطيئة ",
  speedRealTime: "في الوقت الحالى  ",
  components: " حدد المكونات ",
  servo: "  ",
  servoDescription: " محرك السيرفو عبارة عن مشغل يمكنه <b> تدوير كائن بزاوية معينة </ b>. يمكن وضع المحركات المؤازرة في المحاكاة بزاوية بين 0 و 180 درجة. يمكن تزيين المحركات المؤازرة بسهولة وبالتالي فهي مثالية لصنع مكونات متحركة بشكل دوري ",
  motor:  " محرك ",
  DCMotorDescriptino: "",
  scope: "المتغيرات  ",
  alertDebug: " تتوقف المحاكاة عند استئناف البرمجة. ",
  distance:  " مسافة ",
  scenario:  " سيناريو ",
  scenario_default: " لوحة عادية ",
  scenario_moving: "تحريك الروبوت  ",
  scenario_wall:  " روبوت متحرك بجدار ",
  scenario_socialrobot:" روبوت اجتماعي ",
  code:  "الشفرة  ",
  pir: "مستشعر   ",
  pirDescription: "يتيح لك مستشعر الأشعة تحت الحمراء (PIR) <b> استشعار الحركة </ b> ، لأنه يكتشف تغيرات الأشعة تحت الحمراء في بيئتها  ",
  sonar: " سونار ",
  sonarDescription: "",
  led: " ليد ",
  ledDescription: " الصمام الثنائي الباعث للضوء (LED) هو جهاز من أشباه الموصلات <b> يُصدر ضوءًا </ b> عندما يمر تيار كهربائي خلاله. تنتج مواد أشباه الموصلات المختلفة <b> ألوانًا مختلفة من الضوء </ b>. ",
  rgbled: "RGB LED",
  rgbledDescription: "",
  ledmatrix: "LED matrix",
  ledmatrixDescription: "",
  ledmatrixsegment: "LED matrix",
  ledmatrixsegmentDescription: "",
  touch: "Touch sensor",
  touchDescription: "",
  lcd: " شاشة عرض من الكريستال السائل ",
  lcdDescription: "شاشة LCD على لوحة عبارة عن شاشة عرض 16x2 مع إضاءة خلفية.  ",
  button: " زر ",
  buttonDescription: "",
  sound: " مستشعر الصوت ",
  soundDescription: "",
  light:  " مستشعر الضوء ",
  lightDescription: "",
  buzzer: " صفارة ",
  buzzerDescription: " يمكن استخدام الجرس الموجود على لوحة Dwengo <b> لتشغيل سلسلة من النغمات </ b> أو أجزاء صوتية قصيرة. يتم التحكم في ارتفاع كل نغمة عن طريق تحديد <b> تردد </ b> الجرس. استخدم كتلة تأخير لتغيير طول النغمة. ",
  decoration: " زخرفة ",
};

MSG.socialrobot = {
  plain: "إفتراضي  ",
  eye:  " عين ",
  mouth: "فم  ",
  righthand: "اليد اليمنى  ",
  lefthand: " اليد اليسرى ",
};

MSG.tutorialMenu = {
  header: "دروس  ",
  catDwenguino: " تعلم البرمجة مع  بلوكلي دوينجوينو ",
  catDwenguinoComponents: "نظرة عامة مفيدة  دوينجوينو <br> مكونات   ",
  catDwenguinoConnector: "Pin mapping &<br>expansion connector",  catRidingRobot: "ركوب الروبوت  ",
  catSocialRobot: " روبوت اجتماعي ",
  catWeGoStem: " نحن نذهب إيقاف ",
  chooseCategory:  " حدد فئة البرنامج التعليمي ",
  chooseTutorial:  " حدد البرنامج التعليمي ",
  previous:  " السابق ",
  close: " أغلق ",
  checkAnswer:  " تحقق من الجواب ",
  correctAnswer: " كانت الإجابة صحيحة! ",
  wrongAnswer: "لم تكن الإجابة صحيحة. حاول مرة أخري!  ",
  dwenguinoComponents: "مكونات  دوينجوينو  ",
  sensors: "Sensors",
  actuators: "Actuators",
  movement: "Movement",
  audio: "Audio",
  display: "Display"
};

MSG.tutorials = {
  introduction: {},
  /*theremin: {},
  robot: {},
  hello_dwenguino: {},*/
};


MSG.tutorials.general = {
  sureTitle: "هل أنت واثق؟  ",
  sureText:  " عند النقر فوق التالي ، ستتم إزالة جميع الكتل الموجودة في مساحة العمل. ",
};


MSG.tutorials.introduction = {
  step1Title: " مرحبا بكم في بلوكلي دوينجوينو",
  step1Content: " مرحبًا ، اسمي دوينجوينو! سوف أساعدك في التعرف على الواجهة! ",
  step2aTitle: "منطقة كود بلوكلي  ",
  step2aContent: " في هذا المجال قمت بوضع الكتل البرمجية يجب أن تضع الكتل الخاصة بك داخل كتلة حلقة الإعداد إذا كنت تريد تنفيذها. ",
  step2bTitle: " مربع الأدوات بلوكلي",
  step2bContent: "هذا هو صندوق الأدوات ، ويحتوي على جميع الكتل التي يمكنك استخدامها لإنشاء برنامجك. يمكنك استكشاف الفئات المختلفة لمعرفة ما يمكن أن يفعله دوينجوينو.  ",
  step3Title: " اختيار اللغة ",
  step3Content: " استخدم هذا لتغيير اللغة ",
  step4Title: " صعوبة ",
  step4Content: " يتيح لك شريط التمرير هذا ضبط مستوى الصعوبة. في الوقت الحالي نحن نقدم فقط مستويات المبتدئين والمتقدمين. ",
  step5Title: " دوينجوبوكس ",
  step5Content: ". عبارة عن برامج تعليمية تفاعلية ترشدك خلال تحديات الحوسبة المادية المختلفة. دوينجوبوكس ",
  step6Title: " تحميل الكود ",
  step6Content: "عند اكتمال الكود الخاص بك ، يمكنك تحميله على لوحة دوينجوينو بالنقر فوق هذا الزر. تأكد من تحديد اللوحة اليمنى والمنفذ داخل معرف اردوينو.  ",
  step7Title: " Open ",
  step7Content: " يتيح لك هذا الزر فتح برنامج تم حفظه مسبقًا. ",
  step8Title: " حفظ ",
  step8Content: "باستخدام هذا الزر ، يمكنك حفظ التعليمات البرمجية الخاصة بك في ملف محلي.  ",
  step9Title: " المحاكاة ",
  step9Content: "مع هذا الزر لفتح جهاز المحاكاة. يمكنك استخدامه لاختبار الكود الخاص بك قبل التحميل.  ",
};


MSG.tutorials.nameOnLcd = {
  step1Title: " الاسم على شاشة  عرض من الكريستال السائل ",
  step1Content: " افتح عرض المحاكي واختبر الكود. ماذا ترى؟ ",
  step2Title: " الاسم على شاشة  عرض من الكريستال السائل ",
  step2Content: " قم بتغيير البرنامج بحيث يظهر اسمك على السطر الأول من شاشة  من الكريستال السائل. ",
};


MSG.tutorials.blinkLED = {
  step1Title: "وميض شاشة  من الكريستال السائل  ",
  step1Content: " افتح عرض المحاكي واختبر الكود. ماذا ترى؟ ",
  step2Title: " وميض شاشة  من الكريستال السائل ",
  step2Content: " قم بتغيير البرنامج بحيث يتم تشغيل مؤشر شاشة  من الكريستال السائل لمدة ثانية واحدة ثم يقوم بإيقاف تشغيله لمدة ثانية واحدة. يتكرر هذا التسلسل إلى أجل غير مسمى. ",
  step3Title: "إضافي  ",
  step3Content: " قم بتشغيل وإيقاف مؤشر شاشة  من الكريستال السائل آخر. ",
};


MSG.tutorials.ledOnButtonPress = {
  step1Title: "  على زر الضغط شاشة  من الكريستال السائل",
  step1Content: " افتح عرض المحاكي واختبر الكود. ماذا ترى؟ ",
  step2Title: "  على زر الضغط شاشة  من الكريستال السائل",
  step2Content: " قم بتغيير البرنامج بحيث يتم تشغيل مؤشر شاشة  من الكريستال السائل عند الضغط على زر الشمال. ",
  step3Title: "  إضافي",
  step3Content:  " تأكد من إيقاف تشغيل مؤشر شاشة  من الكريستال السائل عند تحرير زر الشمال. ",
};


MSG.tutorials.bitPatternOnLeds = {
  step1Title: " نمط على المصابيح ",
  step1Content: " افتح عرض المحاكي واختبر الكود. ماذا ترى؟ ",
  step2Title: " نمط على المصابيح ",
  step2Content: " الرمز الذي لديك طويل جدًا. هل يمكنك الحصول على نفس النتيجة باستخدام كتل أقل؟ حاول الحصول على نفس النتيجة باستخدام كتل أقل! ",
  step3Title: " نمط على المصابيح ",
  step3Content: " عندما تنجح في تقليل عدد الكتل ، اتصل بأحد المدرسين للحصول على تعليقات على الحل الخاص بك. ",
};


MSG.tutorials.allButtons = {
  step1Title: " كل الأزرار ",
  step1Content: "افتح عرض المحاكاة واختبر الكود. ماذا ترى؟  ",
  step2Title: " كل الأزرار ",
  step2Content: " يجب أن يعمل هذا الرمز على تشغيل مؤشر المصابيح عند الضغط على أحد الأزرار. انظر إلى البرنامج. هل تعمل جميع الأزرار؟ حاول تصحيح التعليمات البرمجية للأزرار التي لا تعمل. ",
  step3Title: " إضافي ",
  step3Content: "قم بتغيير الرمز بحيث ينطفئ مؤشر المصابيح عند تحرير الزر.  ",
};


MSG.tutorials.driveForward = {
  step1Title: " قد للأمام ",
  step1Content: "افتح عرض المحاكاة.  ",
  step2Title: "قد للأمام  ",
  step2Content: " حدد عرض السيناريو واختبر الكود. ماذا ترى؟ ",
  step3Title: " قد للأمام ",
  step3Content: " هل تقود السيارة للأمام؟ صحح الكود حتى تتحرك السيارة للأمام. ",
};


MSG.tutorials.rideInSquare = {
  step1Title: " ركوب في المربع ",
  step1Content: " قلم عرض المحاكاة. ",
  step2Title: "ركوب في المربع  ",
  step2Content: " حدد عرض السيناريو واختبر الكود. ماذا ترى؟ ",
  step3Title: " ركوب في المربع ",
  step3Content: "هل تسير السيارة في مربع؟ قم بتصحيح الكود بحيث تسير السيارة في مربع.  ",
  step4Title: " إضافي ",
  step4Content: " الكود طويل ، هل يمكنك جعله أقصر مع الحفاظ على نفس السلوك؟ ",
};


MSG.tutorials.rideToWall = {
  step1Title: "اركب إلى الحائط  ",
  step1Content: "افتح عرض المحاكاة.  ",
  step2Title: " اركب إلى الحائط ",
  step2Content:  " حدد عرض السيناريو. ",
  step3Title:  "اركب إلى الحائط  ",
  step3Content:  " قم بتغيير السيناريو إلى تحريك الروبوت بالحائط واختبر الكود. ماذا ترى؟ ",
  step4Title: " اركب إلى الحائط ",
  step4Content: "هل تصطدم السيارة بالحائط؟ هل يتوقف عند الحائط؟ قم بتغيير الرمز بحيث تتوقف السيارة بالقرب من الحائط.  ",
};


MSG.tutorials.avoidWall = {
  step1Title: " تجنب الجدار ",
  step1Content: " افتح عرض المحاكاة. ",
  step2Title:  " تجنب الجدار ",
  step2Content:  "حدد عرض السيناريو.  ",
  step3Title:  " تجنب الجدار ",
  step3Content:  " قم بتغيير السيناريو لتحريك الروبوت بالحائط واختبر الكود. ماذا ترى؟ ",
  step4Title:  " تجنب الجدار ",
  step4Content: " هل تتجنب السيارة الحائط بالدوران قبل وصوله إليه؟ قم بتغيير الرمز بحيث تستمر السيارة في القيادة ولكن لا تصطدم بالحائط أبدًا. ",
};


MSG.tutorials.nameOnLcdBasic = {
  step0Title: " هل أنت واثق؟ ",
  step0Content: " هل أنت واثق؟ عند النقر فوق التالي ، ستفقد الكتل الموجودة في مساحة العمل. ",
  step1Title: "الاسم على شاشة المصابيح  ",
  step1Content: " في هذا البرنامج التعليمي ، يجب أن تضع اسمك على شاشة LCD. يمكنك أن ترى مثالا لكيفية القيام بذلك. ",
  step2Title: " اختبار على لوحة متحكم ",
  step2Content: " اختبر الكود الخاص بك عن طريق توصيل لوحة دوينجوينو بالكمبيوتر باستخدام كابل يو اس بي والضغط على زر التشغيل في القائمة العلوية. ",
  step3Title: " اسمك ",
  step3Content: " الآن ، يظهر اسم توم على الشاشة. قم بتغيير الرمز حتى يظهر اسمك. ",
  step4Title: "صفين  ",
  step4Content: "تحتوي شاشة المصابيح على صفين. قم بتغيير رقم الصف من 0 إلى 1.  ",
  step5Title: " اختبار ",
  step5Content: "اختبر الكود الخاص بك.  ",
  step6Title: " عظيم! ",
  step6Content:  "أحسنت! أنت الآن تعرف كيفية عرض اسمك على شاشة المصابيح.  ",
};


/*MSG.tutorials.hello_dwenguino = {
  label: "Hello World!"= " مرحبا بالعالم! ",
};*/

MSG.logging = {
  setup: " إعداد الاختبار ",
  login: " تسجيل الدخول ",
  logout: "Log out",
  firstname: "First name",
  newuser: "مستخدم جديد ",
  email: "Email address",
  enterEmail: "Enter email address",
  forgotPassword: "I forgot my password",
  secretCode: "Secret code",
  enterSecretCode: "Enter your secret code sent to you by email",
  userDoesNotExist: "This user does not exist. Try a different email address.",
  resetPassword: "Reset your password",
  back: "Back",
  enterFirstname: "Enter your first name",
  password: "Password",
  repeatedPassword: "Repeat password",
  enterPassword: "Enter password",
  enterRepeatedPassword: "Repeat your password",
  username: "اسم المستخدم  ",
  chooseUsername: " اختر اسم المستخدم ",
  choosePassword: " حدد 4 رموز شخصية ككلمة المرور الخاصة بك. يجب أن تكون قادرًا على تذكرها بالترتيب الصحيح. ",
  currentlySelected:  " المحدد حاليا: ",
  role: "Role",
  student: "Student",
  teacher: "Teacher",
  verification: "Verify your email address",
  verificationSentTo: "A verification message has been sent to your email address. Click the link in the email to verify your account.",
  birth:  "تاريخ الولادة  ",
  school: "مدرسة  ",
  selectSchool: "البحث باسم المدرسة ...  ",
  agegroup: " الفئة العمرية: ",
  primary1: "الصف الأول الابتدائي  ",
  primary2: "الصف الابتدائي 2  ",
  primary3: "الصف الابتدائي 3  ",
  primary4: "الصف الابتدائي 4 ",
  primary5: "الصف الابتدائي 5  ",
  primary6: " الصف الابتدائي 6 ",
  secondary1: "الصف الأول الثانوي  ",
  secondary2: "الصف الثاني الثانوي  ",
  secondary3: "الصف الثانوي 3  ",
  secondary4: "الصف الثانوي 4  ",
  secondary5: " الصف الثانوي 5 ",
  secondary6: "الصف الثانوي 6  ",
  gender: " جنس: ",
  gender1:" F ",
  gender2: " M ",
  gender3:" X ",
  gender4: " أفضل أن لا أقول ",
  activity: "نشاط:  ",
  name: " اسم ",
  date: " تاريخ ",
  ok: " حسنا ",
  continue: "Continue",
  reset: " إعادة تعيين ",
  person: " شخص ",
  dog: " الكلب ",
  car: "سيارة  ",
  camera: "الة تصوير  ",
  heart: "قلب  ",
  plane: "طائرة  ",
  house: " منزل ",
  umbrella: " مظلة ",
  star: " نجمة ",
  money: "مال  ",
  gift: " هدية مجانية ",
  keys: "  مفاتيح ",
  music: " موسيقى ",
  snowflake: " ندفة الثلج ",
  fire: "نار  ",
  envelope: " ظرف ",
  conditions: "Voorwaarden",
  conditions1: "Om de app te gebruiken, moet je akkoord gaan met de <b>gebruiksvoorwaarden</b> en het <b>privacybeleid</b>.",
  generalConditions: "de gebruiksvoorwaarden",
  privacyStatement: "het privacybeleid",
  conditions2: "Daar staat onder andere in dat je moet inloggen om te beschikken over functionaliteit zoals het bewaren van je programma's of het bijhouden van je voortgang, dat je data anoniem wordt gelogd en verwerkt, en dat je ons mag mailen met vragen over privacy.",
  conditions3: "Ben je <b>13 jaar of ouder?</b> Dan mag je hieronder <b>zelf bevestigen</b> dat je de info hebt gelezen en akkoord gaat.",
  conditions4: "Ben je <b>12 jaar of jonger?</b> Dan moet een van je ouders of voogden toestemming geven.",
  acceptConditions: "Ik ga akkoord met de gebruiksvoorwaarden en het privacybeleid van de Dwengo-simulator",
  acceptResearch: "Ik geef toestemming aan Dwengo vzw om de gegevens die de simulator verzamelt, voor <b>wetenschappelijk onderzoek</b> te gebruiken, geanonimiseerd en volgens het privacybeleid.",
  anonymized: "* <b>\'Geanonimiseerd\'</b> wil zeggen dat er geen link is tussen je persoonsgegevens en je data. Niemand weet dus wat je deed in de simulator."
}

MSG.validator = {
  errSchool: " اختر مدرسة. ",
  errId: " لم تقم بتحديد رموز كافية. ",
  errAgeGroup: "حدد الفئة العمرية الخاصة بك.  ",
  errGender: "اختر جنسك.  ",
  errFirstname: "Je voornaam is niet ingevuld.",
  errLastname: "Je achternaam is niet ingevuld.",
  errPassword: "Je paswoord voldoet niet aan de voorwaarden.",
  errPasswordNotIdentical: "Je paswoorden zijn niet identiek.",
  errEmail: "Je email is niet geldig",
  errActivityId: "لا يمكن أن يكون عنوان نشاطك فارغًا.  ",
  errAcceptConditions: "Je hebt de gebruiksvoorwaarden en het privacybeleid nog niet geaccepteerd.",
  errAcceptResearch: "Je hebt nog geen toestemming gegeven om de gegevens voor wetenschappelijk onderzoek te laten gebruiken.",
  errRequiredFields: "Je hebt niet alle velden ingevuld.",
  errRoleInvalid: "De opgegeven rol is niet geldig."
};