var MSG = {
  arduinoCodeCopied: "Arduino code copied to clipboard",
  title: "DwenguinoBlockly",
  blocks: "Μπλοκ",
  linkTooltip: "Αποθήκευση και σύνδεση σε μπλοκ.",
  runTooltip: "Εκτέλεση προγράμματος όπως αυτό ορίζεται από τα μπλοκ στον χώρο εργασίας.",
  loadBlocksFileTooltip: "Φόρτωση προγράμματος που έχει αποθηκευτεί στο παρελθόν.",
  saveBlocksFileTooltip: "Αποθήκευση προγράμματος σε τοπικό αρχείο.",
  toggleSimulator: "Ενεργοποίηση προσομοιωτή",
  badCode: "Σφάλμα προγράμματος:\n%1",
  timeout: "Υπέρβαση μέγιστου αριθμού επαναλήψεων.",
  trashTooltip: "Διαγραφή όλων των μπλοκ.",
  catLogic: "Λογική",
  catLoops: "Επαναλήψεις",
  catMath: "Μαθηματικά",
  catText: "Κείμενο",
  catLists: "Λίστες",
  catColour: "Χρώμα",
  catArduino: "Arduino",
  catVariables: "Μεταβλητές",
  catFunctions: "Συναρτήσεις",
  catDwenguino: "Dwenguino",
  catSocialRobot: "Social robot",
  catBoardIO: "Πλακέτα εισόδων/εξόδων",
  createVar: "Create variable",
  catComments: "Comments",
  listVariable: "λίστα",
  textVariable: "κείμενο",
  httpRequestError: "Υπήρξε πρόβλημα με το αίτημα.",
  linkAlert: "Κοινοποίηση των μπλοκ με αυτόν τον σύνδεσμο:\n\n%1",
  hashError: "Λυπάμαι, το «%1» δεν αντιστοιχεί σε κανένα αποθηκευμένο πρόγραμμα.",
  xmlError: "Δεν μπορώ να φορτώσω το αποθηκευμένο αρχείο σου.  Μήπως δημιουργήθηκε από κάποια παλιότερη έκδοση του Blockly;",
  badXml: "Σφάλμα ανάλυσης XML:\n%1\n\nΕπίλεξε «Εντάξει» για να εγκαταλείψεις τις αλλαγές σου ή «Ακύρωση» για να επεξεργαστείς το XML κι άλλο.",
  setup: "Ρύθμιση",
  loop: "Επανάληψη",
  dwenguino_main_program_structure: "Ο κώδικας στο μπλοκ ρύθμισης εκτελείται μόνο μία φορά, στην αρχή του προγράμματος. Ο κώδικας στο μπλοκ επανάληψης εκτελείται επαναλαμβανόμενα μέχρι τη λήξη του προγράμματος",
  catDwenguino: "Dwenguino",
  delay_help: "Αναμονή προκαθορισμένου χρόνου σε χιλιοστά δευτερολέπτου. (1 δευτερόλεπτο (s) = 1000 χιλιοστά δευτερολέπτου (ms))",
  delay: "Αναμονή",
  clearLCD: "Καθαρισμός LCD",
  dwenguinoLCD: "Dwenguino LCD %1 %2 %3 Εμφάνισε κείμενο: %4 Στη σειρά: %5 Ξεκινώντας από τη στήλη: %6",
  pin: "Ακροδέκτης",
  toneOnPin: "Αναπαραγωγή τόνου στον ακροδέκτη ",
  frequency: "με συχνότητα",
  noToneOnPin: "Διακοπή αναπαραγωγής τόνου στο",
  toneOnPinTooltip: "Αναπαραγωγή τόνου καθορισμένης συχνότητας σε καθορισμένο ακροδέκτη",
  noToneOnPinTooltip: "Διακοπή αναπαραγωγής τόνου στον ακροδέκτη",
  trig: "Αριθμός ακροδέκτη TRIG",
  echo: "Αριθμός ακροδέκτη ECHO",
  sonarTooltip: "Αυτός ο αισθητήρας διαβάζει την απόσταση ενός αντικειμένου από αυτόν",
  miliseconds: "χιλιοστά δευτερολέπτου",
  digitalRead: "Ανάγνωση ψηφιακής τιμής",
  digitalWriteToPin: "Εγγραφή τιμής στον ψηφιακό ακροδέκτη ",
  digitalWriteValue: "Εγγραφή ψηφιακής τιμής",
  digitalWriteTooltip: "Εγγραφή ψηφιακής τιμής (1/υψηλή ή 0/χαμηλή στάθμη) στον ψηφιακό ακροδέκτη του Dwenguino",
  digitalReadTooltip: "Ανάγνωση ψηφιακής τιμής (1/υψηλή ή 0/χαμηλή στάθμη) από καθορισμένο ακροδέκτη",
  high: "Υψηλή στάθμη",
  low: "Χαμηλή στάθμη",
  highLowTooltip: "Η ψηφιακή τιμή (1/υψηλή ή 0/χαμηλή στάθμη) στον ακροδέκτη",
  tutsIntroduction: "Introduction",
  tutsTheremin: "Theremin",
  tutsRobot: "Ρομπότ",
  tutsHelloDwenguino: "Γεια σου Dwenguino!",
  tutsNameOnLcd: "Όνομα στην οθόνη LCD",
  tutsBlinkLED: "Αναβόσβησε το LED",
  tutsLedOnButtonPress: "Ενεργοποίηση LED με πάτημα κουμπιού",
  tutsBitPatternOnLeds: "Δυαδικό μοτίβο και LED",
  tutsAllButtons: "Όλα τα κουμπιά",
  tutsDriveForward: "Κίνηση εμπρός",
  tutsRideInSquare: "Τετράγωνη τροχιά",
  tutsRideToWall: "Προσέγγιση τοίχου",
  tutsAvoidWall: "Αποφυγή τοίχου",
  tutsNameOnLcdBasic: "Όνομα στην οθόνη LCD",
  simulator: "Προσομοιωτής",
  setLedState: "Ενεργοποίηση ή απενεργοποίηση LED %1 %2",
  setLedStateTooltip: "Ενεργοποίηση ή απενεργοποίηση ενός LED του Dwenguino",
  ledPinsTooltip: "Επιλογή ενός LED προς έλεγχο",
  dwenguinoOn: "ON",
  dwenguinoOff: 'OFF',
  dwenguinoOnOffTooltip: "Επιλογή τιμής για το άναμμα/σβήσιμο ενός LED",
  dwenguinoLedBlock: "LED",
  dwenguinoSonarBlock: "Αισθητήρα υπερήχων %1 %2 %3 trig pin number %4 echo pin number %5",
  dwenguinoServoBlock: "Σερβοκινητήρας %1 %2 %3 κανάλι # %4 γωνία %5",
  dwenguinoServoDropdownBlock: "Servo motor %1",
  dwenguinoServoBlockTooltip: "Ορισμός γωνίας μεταξύ 0 και 180 μοιρών σε σερβοκινητήρα συνδεμένου στο Dwenguino.",
  dwenguinoServoDropdownTooltip: "Select one of the two internal servo motors",
  dwenguinoServoOne: "1",
  dwenguinoServoTwo: "2",
  dwenguinoDCMotorBlock: "Κινητήρας DC %1 %2 %3 κανάλι %4 ταχύτητα %5",
  dwenguinoDCMotorBlockTooltip: "Ορισμός ταχύτητας σε κινητήρα DC συνδεμένου στο Dwenguino. (Ταχύτητα = τιμή μεταξύ -255 (μέγιστη ταχύτητα όπισθεν) και 255 (μέγιστη ταχύτητα εμπρός))",
  dwenguinoAnalogWrite: "Εγγραφή στο %1 την αναλογική τιμή %2",
  dwenguinoAnalogWriteTooltip: "Εγγραφή αναλογικής τιμής μεταξύ 0 και 255 σε καθορισμένο ακροδέκτη",
  dwenguinoAnalogRead: "Ανάγνωση αναλογικής τιμής από %1",
  dwenguinoAnalogWriteTooltip: "Ανάγνωση αναλογικής τιμής μεταξύ 0 και 255 από τον καθορισμένο ακροδέκτη",
  digitalReadSwitch: "Ανάγνωση ψηφιακής τιμής του διακόπτη %1",
  digitalReadSwitchTooltip: "Ανάγνωση ψηφιακής τιμής από έναν από τους διακόπτες του Dwenguino",
  waitForSwitch: "περίμενε μέχρι να πατηθεί το κουμπί %1",
  north: "Βορράς",
  east:"Ανατολή",
  south: "Νότος",
  west: "Δύση",
  center: "Κέντρο",
  ledsReg: "LED",
  dwenguinoLedsRegTooltip: "Μπορείς να ανάψεις τα LED 0 έως 7 χρησιμοποιώντας ένα δυαδικό αριθμό. Για παράδειγμα το 0b00001111 θα ανάψει τα LED 0 έως 3 on ενώ τα υπόλοιπα θα σβήσουν",
  pressed: "Πιεσμένο",
  notPressed: "Μη πιεσμένο",
  pressedTooltip: "Αντιπροσωπεύει την κατάσταση ενός κουμπιού. Χρησιμοποίησε αυτές τις τιμές για να τις συγκρίνεις με την τρέχουσα κατάσταση του κουμπιού",
  sureYouWantToChangeTutorial: "Είσαι σίγουρος ότι θες να ξεκινήσεις αυτό το μάθημα;\n Όλα τα μπλοκ στην επιφάνεια εργασίας θα χαθούν.",
  create: "Δημιουργία",
  with_type: "με τύπο",
  create_global: "Δημιουργία καθολικής",
  socialRobotRgbLedBlock: "RGB LED",
  socialRobotPinRed: "pin red",
  socialRobotPinGreen: "pin green",
  socialRobotPinBlue: "pin blue",
  socialRobotRgbLedOffBlock: "Turn the RGB LED off with",
  socialRobotRgbColorBlock: "RGB color",
  socialRobotPirBlock: "PIR %1 %2 %3 trig pin number %4",
  socialRobotSoundSensorBlock: "Sound sensor %1 %2 %3 pin %4",
  socialRobotSoundSensorBlockTooltip: "",
  socialRobotTouchSensorBlock: "Touch sensor %1 %2 %3 pin %4",
  socialRobotTouchSensorBlockTooltip: "",
  socialRobotButtonBlock: "Button %1 %2 %3 pin %4",
  socialRobotButtonBlockTooltip: "",
  socialrobotSetPinState: "Set %1 %2",
  socialrobotServoBlock: "Σερβοκινητήρας %1 %2 %3  κανάλι %4 Ακροδέκτης %5",
  socialrobotWaveArmesBlock: "Κούνα τα χέρια %1 %2 Σερβοκινητήρας δεξιού χεριού %3 %4 Σερβοκινητήρας αριστερού χεριού %5 %6",
  socialRobotArmsDownBlock: "Κατέβασε τα χέρια %1 %2 %3 Σερβοκινητήρας δεξιού χεριού %4 %5 Σερβοκινητήρας αριστερού χεριού %6 %7",
  socialRobotArmsUpBlock: "Put arms up %1 %2 %3 Σερβοκινητήρας δεξιού χεριού %4 %5 Σερβοκινητήρας αριστερού χεριού %6 %7",
  socialRobotEyesLeftBlock: "Στρίψε το βλέμμα αριστερά %1 %2 %3 Σερβοκινητήρας αριστερού ματιού %4 %5 Σερβοκινητήρας δεξιού ματιού %6 %7",
  socialRobotEyesRightBlock: "Στρίψε το βλέμμα δεξιά %1 %2 %3 Σερβοκινητήρας αριστερού ματιού %4 %5 Σερβοκινητήρας δεξιού ματιού %6 %7",
  socialrobotReadPinBlock: "Ανάγνωση τιμής ακροδέκτη %1 %2",
  socialRobotServoRightHand: " Σερβοκινητήρας δεξιού χεριού",
  socialRobotServoLeftHand: "Σερβοκινητήρας αριστερού χεριού",
  sonarSliderLabel: "Απόσταση από αισθητήρα υπερήχων",
  pirButtonLabel: "Κουμπί PIR",
  soundButtonLabel: "Κουμπί ήχου",
  touchButtonLabel: "Touch button",
  lightSensorSliderLabel: "Απόσταση από αισθητήρα φωτός",
  servoCostume: "Στολή",
  servoOptions: "Επιλογές σερβοκινητήρα",
  sonarOptions: "Επιλογές αισθητήρα υπερήχων",
  lcdOptions: "Επιλογές οθόνης LCD",
  pirOptions: "Επιλογές αισθητήρα PIR",
  soundOptions: "Επιλογές αισθητήρα ήχου",
  touchOptions: "Touch sensor options",
  buttonOptions: "Button options",
  lightOptions: "Επιλογές αισθητήρα φωτός",
  rgbLedOptions: "Επιλογές RGB LED",
  ledmatrixOptions: 'Led  Matrix Options',
  ledOptions: "Επιλογές LED",
  pinOptions: "Ακροδέκτης",
  colorOptions: "Color",
  runError: "Ωχ, σφάλμα κατά την προσπάθεια να τρέξει ο κώδικάς σου στην πλακέτα.",
  uploadError: "Ακολούθησε τα παρακάτω βήματα για να επανεκκινήσεις την πλακέτα Dwenguino: \n    1. Αποσύνδεσε το καλώδιο USB \n    2. Σύνδεσε ξανά με το καλώδιο USB τον υπολογιστή και την πλακέτα Dwenguino \n    3. Πίεσε ταυτόχρονα τα κουμπιά RESET και SOUTH της πλακέτας Dwenguino \n    4. Άφησε πρώτα το κουμπί RESET \n    5. Ύστερα άφησε το κουμπί SOUTH \n    6. Μεταφόρτωσε ξανά το πρόγραμμα πατώντας το <span id='db_menu_item_run' class='fas fa-play-circle' alt='Upload code to Dwenguino board'></span> κουμπί στο κύριο μενού",
  cleanError: "Ο προηγούμενος κώδικας δε μπορεί να αφαιρεθεί.\nΈλεγξε παρακαλώ αν κάποια άλλη εφαρμογή χρησιμοποιεί κάποιο αρχείο .cpp.\nΤερμάτισε αυτή την εφαρμογή.",
  compileError: "Ο κώδικας δε μπορεί να μεταγλωττιστεί.\nΈλεγξε παρακαλώ τον κώδικά σου, ξέχασες μήπως πουθενά κάποιο μπλοκ;",
  clear: "Καθαρισμός",
  save: "Αποθήκευση",

  //TODO: translate
  dwenguinoStepperMotorBlock: "κινητήρας stepper %1 %2 %3 αριθμό %4 πλήθος βημάτων %5",
  dwenguinoStepperMotorBlockTooltip: "TODO",
  drawingrobotMove:"Μετακίνησε τη γραφίδα υπό γωνία %1 μοίρες με %2 βήματα",
  drawingrobotMoveXY:"Μετακίνησε τη γραφίδα %1 προς τα δεξιά και %2 προς τα αριστερά",
  drawingrobotLine:"Σχεδίασε μία γραμμή προς x: %1 y: %2",
  drawingrobotCircle:"Σχεδίασε έναν κύκλο με ακτίνα: %1",
  drawingrobotRectangle:"Σχεδίασε ένα ορθογώνιο με μήκος: %1 en πλάτος: %2",
  drawingrobotLiftStylus: "Ανέβασμα γραφίδας",
  drawingrobotLowerStylus: "Κατέβασμα γραφίδας",
  drawingrobotChangeColor: "Χρώμα %1",
  up:"πάνω",
  down:"κάτω",
  left:"αριστερά",
  right:"δεξιά",
  bounds:"Προσοχή\nΠροσποθείς να ζωγραφίσεις έξω από το χαρτί",
  drawingrobotgrid: "raster",
  colorpicker:"Χρώμα",
  drawingrobotSaveImage:"Αποθήκευση ζωγραφιάς",
  drawingrobotDrawing:"Ζωγραφιά",
  stepperMotorOne: "STEPPER1",
  stepperMotorTwo: "STEPPER2",
  stepperMotorTooltip: "Επίλεξε ποιον stepper κινητήρα του robot εκτυπωτή θες να χρησιμοποιήσεις.",
  clear: "Καθαρισμός",
  save: "Αποθήκευση",
};

MSG.cookieConsent = {
  close: "Close",
  cookieConsent: "We use functional cookies to set up the Dwenguino simulator. ",
  cookieInfo: "More info on how we use cookies.",
  whatAreCookiesTitle: "Wat zijn cookies?",
  whatAreCookiesDescription1: "Cookies zijn kleine tekstbestanden die lokaal worden opgeslagen op uw computer. Deze cookies dienen voor tal van doeleinden: het onthouden van instellingen (login, taalkeuzes), het vergaren van informatie en het bijhouden van het bezoekgedrag van de gebruikers.",
  whatAreCookiesDescription2: "De cookies die wij gebruiken zijn veilig: zij hebben geen toegang tot persoonlijke informatie op uw computer en kunnen deze niet beschadigen of besmetten met virussen. De cookies geven op geen enkele manier persoonlijke informatie aan ons door. De informatie die we via cookies verzamelen helpt ons om je van specifieke diensten te laten genieten.",
  whatAreNecessaryCookiesTitle: "Wat zijn noodzakelijke cookies?",
  whatAreNecessaryCookiesDescription: "Noodzakelijke cookies zijn cookies die je nodig hebt om te surfen op de website en gebruik te maken van de functionaliteit die we aanbieden. Bovendien zijn de cookies noodzakelijk om de beveiligde onderdelen van de website te kunnen zien.",
  whichCookiesTitle: "Welke cookies gebruikt deze website?",
  dwengoCookieTitle: "Aanmelden als gebruiker (Dwengo cookie)",
  dwengoCookieDescription: "Bij het aanmelden op de website wordt een tijdelijke cookie gebruikt waardoor je herkend wordt als gebruiker. Met behulp van deze cookie wordt onder andere je taalinstelling en vooruitgang bewaard. De cookie zorgt er voor dat je toegang hebt tot de beveiligde delen van de website. Deze cookie is slechts geldig tot aan het einde van de sessie en is enkel beschikbaar voor en gemaakt door Dwengo vzw.",
  jenkinsCookieTitle: "Jenkins configuratie (Jenkins cookie)",
  jenkinsCookieDescription: "De Jenkins cookie is voor ons noodzakelijk om de Dwenguino simulator online op een server te kunnen installeren. Jenkins is software waarvan we gebruik maken om onze simulator te updaten. Die cookie bevat informatie over de instellingen van Jenkins en bevat dus ook geen enkele informatie over jou als gebruiker.",
};

MSG.dropzone = {
  dictSelectFile: "Επίλεξε ένα αρχείο.",
  dictChooseFile: "Επιλογή αρχείου",
  dictDefaultMessage: "Άφησε αρχεία εδώ για να τα μεταφορτώσεις",
  dictFallbackMessage: "Ο περιηγητής σου δεν υποστηρίζει μεταφορτώσεις αρχείων με σύρσιμο.",
  dictFileTooBig: "Το αρχείο είναι πολύ μεγάλο ({{filesize}}MiB). Μέγιστο μέγεθος αρχείου: {{maxFilesize}}MiB.",
  dictFallbackText: "Χρησιμοποίησε παρακαλώ την παρακάτω εφεδρική φόρμα για να μεταφορτώσεις τα αρχεία σου σαν τον παλιό καιρό.",
  dictInvalidFileType: "Δεν μπορείς να μεταφορτώσεις αρχείου αυτού του τύπου.",
  dictResponseError: "Ο εξυπηρετητής απάντησε με κωδικό {{statusCode}}.",
  dictCancelUpload: "Ακύρωση μεταφόρτωσης",
  dictCancelUploadConfirmation: "Είσαι σίγουρος ότι θες να ακυρώσεις τη μεταφόρτωση του αρχείου;",
  dictRemoveFile: "Διαγραφή αρχείου",
  dictMaxFilesExceeded: "Δεν μπορείς να μεταφορτώσεις επιπλέον αρχεία.",
  dictUploadBlocks: "Upload blocks",
  dictFileNotSupported: "This file is not supported.",
}

MSG.simulator = {
  start: "Εκκίνηση",
  stop: "Διακοπή",
  pause: "Παύση",
  step: "1 βήμα",
  speed: "Ταχύτητα",
  speedVerySlow: "Επιβράδυνση 40 φορές συγκριτικά με την πραγματική ταχύτητα",
  speedSlow: "Επιβράδυνση 20 φορές συγκριτικά με την πραγματική ταχύτητα",
  speedMedium: "Επιβράδυνση 10 φορές συγκριτικά με την πραγματική ταχύτητα",
  speedFast: "Επιβράδυνση 5 φορές συγκριτικά με την πραγματική ταχύτητα",
  speedVeryFast: "Επιβράδυνση 2 φορές συγκριτικά με την πραγματική ταχύτητα",
  speedRealTime: "Πραγματική ταχύτητα εκτέλεσης",
  components: "Επιλογή εξαρτημάτων",
  servo: "Σερβοκινητήρας",
  servoDescription: "A servo motor is an actuator that can <b>rotate an object over a certain angle</b>. In the simulator servo motors can be put at an angle between 0 and 180 degrees. Servo motors can easily be decorated and are thus ideal to make periodically moving components",
  motor: "Κινητήρας DC",
  DCMotorDescription: "",
  scope: "Μεταβλητές",
  alertDebug: "Πρέπει να διακοπεί η προσομοίωση πριν τη συνέχιση του προγραμματισμού.",
  distance: "απόσταση",
  scenario: "σενάριο",
  scenario_default: "Κανονική πίστα",
  scenario_moving: "Κινούμενο ρομπότ",
  scenario_wall: "Κινούμενο ρομπότ και τοίχος",
  code: "Κώδικας",
  pir: "Αισθητήρας PIR",
  pirDescription: "A passif infrared (PIR) sensor allows you to <b>sense motion</b>, because it detects changes of infrared radiation in its environment",
  sonar: "Sonar",
  sonarDescription: "",
  led: "LED",
  ledDescription: "",
  rgbled: "RGB LED",
  rgbledDescription: "",
  ledmatrix: "LED matrix",
  ledmatrixDescription: "",
  ledmatrixsegment: "LED matrix",
  ledmatrixsegmentDescription: "",
  touch: "Touch sensor",
  touchDescription: "",
  lcd: "Οθόνη LCD",
  lcdDescription: "",
  button: "Κουμπί",
  buttonDescription: "",
  sound: "Αισθητήρας Sound",
  soundDescription: "",
  light: "Αισθητήρας Light",
  lightDescription: "",
  buzzer: "Buzzer",
  buzzerDescription: "",
  decoration: "Διακόσμηση",
};

MSG.socialrobot = {
  plain: "Προεπιλογή",
  eye: "Μάτι",
  mouth: "Στόμα",
  righthand: "Δεξί χέρι",
  lefthand: "Αριστερό χέρι",
};

MSG.tutorialMenu = {
  header: "Μαθήματα",
  catDwenguino: "Μάθε προγραμματισμό<br>με το DwenguinoBlockly",
  catDwenguinoComponents: "Πρακτική επισκόπηση<br>των εξαρτημάτων του Dwenguino",
  catDwenguinoConnector: "Pin mapping &<br>expansion connector",  catRidingRobot: "Riding robot",
  catSocialRobot: "Social robot",
  catWeGoStem: "WeGoSTEM",
  chooseCategory: "Επίλεξε κατηγορία μαθημάτων",
  chooseTutorial: "Επίλεξε μάθημα",
  previous: "Προηγούμενο",
  close: "Κλείσιμο",
  checkAnswer: "Έλεγξε την απάντηση",
  correctAnswer: "Η απάντηση ήταν σωστή!",
  wrongAnswer: "Η απάντηση ήταν λάθος. Προσπάθησε ξανά!",
  dwenguinoComponents: "Εξαρτήματα του Dwenguino",
  sensors: "Sensors",
  actuators: "Actuators",
  movement: "Movement",
  audio: "Audio",
  display: "Display"
};

MSG.tutorials = {
  introduction: {},
  /*theremin: {},
  robot: {},
  hello_dwenguino: {},*/
};


MSG.tutorials.general = {
  sureTitle: "Είσαι σίγουρος;",
  sureText: "Αν πατήσεις 'Next' όλα τα μπλοκ στην επιφάνεια εργασίας θα χαθούν.",
};


MSG.tutorials.introduction = {
  step1Title: "Καλωσορίσατε στο DwenguinoBlockly",
  step1Content: "Γεια, το όνομά μου είναι Dwenguino! Θα σε βοηθήσω να γνωρίσεις το περιβάλλον προγραμματισμού!",
  step2aTitle: "Ο χώρος προγραμματισμού του Blockly",
  step2aContent: "Εδώ τοποθετούμε τα μπλοκ κώδικα. Πρέπει να τα τοποθετούμε μέσα στα μπλοκ ρύθμισης ή επανάληψης εφόσον επιθυμούμε να εκτελεστούν.",
  step2bTitle: "Η εργαλειοθήκη του Blockly.",
  step2bContent: "Η εργαλειοθήκη περιλαμβάνει όλα τα μπλοκ που υπάρχουν για να δημιουργήσουμε το πρόγραμμά μας. Μπορούμε να εξερευνήσουμε τις διάφορες κατηγορίες για να ανακαλύψουμε τις δυνατότητες του Dwenguino.",
  step3Title: "Επιλογή γλώσσας",
  step3Content: "Το χρησιμοποιούμε για να επιλέξουμε τη γλώσσα του περιβάλλοντος προγραμματισμού.",
  step4Title: "Επίπεδο δυσκολίας",
  step4Content: "Με αυτή τη ρύθμιση επιλέγουμε το επίπεδο δυσκολίας. Για την ώρα έχουμε υλοποιήσει μόνο ένα επίπεδο για αρχάριους και ένα για προχωρημένους.",
  step5Title: "Dwengobooks",
  step5Content: "Τα Dwengobooks είναι διαδραστικοί οδηγοί που μας ξεναγούν στις διάφορες προκλήσεις του physical computing.",
  step6Title: "Ανέβασμα του κώδικα",
  step6Content: "Όταν ο κώδικας είναι έτοιμος, μπορούμε να τον ανεβάσουμε στο Dwenguino πατώντας αυτό το κουμπί. Να προσέξουμε πρώτα ότι έχουμε επιλέξει το σωστό τύπο πλακέτας και θύρας στο Arduino IDE.",
  step7Title: "Άνοιγμα",
  step7Content: "Με αυτό το κουμπί φορτώνουμε ένα προηγουμένως αποθηκευμένο πρόγραμμα.",
  step8Title: "Αποθήκευση",
  step8Content: "Με αυτό το κουμπί αποθηκεύουμε τον κώδικά μας σε ένα τοπικό αρχείο.",
  step9Title: "Ο προσομοιωτής",
  step9Content: "Με αυτό το κουμπί ενεργοποιούμε τον προσομοιωτή. Μπορούμε επίσης να το χρησιμοποιούμε για να δοκιμάζουμε το πρόγραμμά μας πριν το ανεβάσουμε στο Dwenguino."
};


MSG.tutorials.nameOnLcd = {
  step1Title: "Όνομα στην οθόνη LCD",
  step1Content: "Ενεργοποίησε την προβολή προσομοιωτή και τρέξε τον κώδικα. Τι παρατηρείς;",
  step2Title: "Όνομα στην οθόνη LCD",
  step2Content: "Μπορείς να τροποποιήσεις τον κώδικα ώστε να εμφανίζεται το όνομά σου στην πρώτη γραμμή της οθόνης LCD;",
};


MSG.tutorials.blinkLED = {
  step1Title: "Αναβόσβημα των LED",
  step1Content: "Ενεργοποίησε την προβολή προσομοιωτή και τρέξε τον κώδικα. Τι παρατηρείς;",
  step2Title: "Αναβόσβημα των LED",
  step2Content: "Μπορείς να τροποποιήσεις τον κώδικα ώστε το LED να ανάβει για ένα δευτερόλεπτο και ύστερα να σβήνει για ένα δευτερόλεπτο; (Αυτή η λειτουργία να επαναλαμβάνεται συνεχώς)",
  step3Title: "Επιπλέον",
  step3Content: "Μπορείς να κάνεις κάποιο άλλο LED να αναβοσβήνει;",
};


MSG.tutorials.ledOnButtonPress = {
  step1Title: "Ενεργοποίηση LED με πάτημα κουμπιού",
  step1Content: "Ενεργοποίησε την προβολή προσομοιωτή και τρέξε τον κώδικα. Τι παρατηρείς;",
  step2Title: "Ενεργοποίηση LED με πάτημα κουμπιού",
  step2Content: "Μπορείς να τροποποιήσεις τον κώδικα ώστε το LED να ανάβει όταν πατήσεις το κουμπί βορρά;",
  step3Title: "Επιπλέον",
  step3Content: "Μπορείς να κάνεις το LED να σβήνει όταν αφήνεις το κουμπί βορρά;",
};


MSG.tutorials.bitPatternOnLeds = {
  step1Title: "Δυαδικό μοτίβο και LED",
  step1Content: "Ενεργοποίησε την προβολή προσομοιωτή και τρέξε τον κώδικα. Τι παρατηρείς;",
  step2Title: "Δυαδικό μοτίβο και LED",
  step2Content: "Ο παρακάτω κώδικας είναι πολύ μακρύς. Μπορείς να πετύχεις το ίδιο αποτέλεσμα χρησιμοποιώντας λιγότερα μπλοκ;",
  step3Title: "Δυαδικό μοτίβο και LED",
  step3Content: "Μόλις καταφέρεις να μειώσεις τον αριθμό των μπλοκ, κάλεσε τον δάσκαλό/δασκάλα σου να δει πώς το κατάφερες!",
};


MSG.tutorials.allButtons = {
  step1Title: "Όλα τα κουμπιά",
  step1Content: "Ενεργοποίησε την προβολή προσομοιωτή και τρέξε τον κώδικα. Τι παρατηρείς;",
  step2Title: "Όλα τα κουμπιά",
  step2Content: "Με αυτό τον κώδικα θα πρέπει το LED να ανάβει όταν πατηθεί οποιοδήποτε από τα κουμπιά. Κοίτα προσεκτικά τον κώδικα. Ισχύει για όλα τα κουμπιά; Μπορείς να διορθώσεις τον κώδικα ώστε να δουλεύει με όλα τα κουμπιά;",
  step3Title: "Επιπλέον",
  step3Content: "Μπορείς να τροποποιήσεις τον κώδικα ώστε το LED να σβήνει όταν το κουμπί δεν πατιέται πια;",
};


MSG.tutorials.driveForward = {
  step1Title: "Κίνηση εμπρός",
  step1Content: "Ενεργοποίησε την προβολή προσομοιωτή.",
  step2Title: "Κίνηση εμπρός",
  step2Content: "Ενεργοποίησε την προβολή σεναρίου και τρέξε τον κώδικα. Τι παρατηρείς;",
  step3Title: "Κίνηση εμπρός",
  step3Content: "Πηγαίνει όντως το ρομπότ εμπρός; Μπορείς να διορθώσεις τον κώδικα ώστε το ρομπότ να πηγαίνει εμπρός;",
};


MSG.tutorials.rideInSquare = {
  step1Title: "Τετράγωνη τροχιά",
  step1Content: "Ενεργοποίησε την προβολή προσομοιωτή.",
  step2Title: "Τετράγωνη τροχιά",
  step2Content: "Ενεργοποίησε την προβολή σεναρίου και τρέξε τον κώδικα. Τι παρατηρείς;",
  step3Title: "Τετράγωνη τροχιά",
  step3Content: "Ακολουθεί όντως το ρομπότ τετράγωνη τροχιά; Μπορείς να διορθώσεις τον κώδικα ώστε να το κάνει σωστά;",
  step4Title: "Επιπλέον",
  step4Content: "Ο παρακάτω κώδικας είναι πολύ μακρύς. Μπορείς να πετύχεις το ίδιο αποτέλεσμα χρησιμοποιώντας λιγότερα μπλοκ;",
};


MSG.tutorials.rideToWall = {
  step1Title: "Προσέγγιση τοίχου",
  step1Content: "Ενεργοποίησε την προβολή προσομοιωτή.",
  step2Title: "Προσέγγιση τοίχου",
  step2Content: "Ενεργοποίησε την προβολή σεναρίου και τρέξε τον κώδικα.",
  step3Title: "Προσέγγιση τοίχου",
  step3Content: "Άλλαξε το σενάριο στο «Κινούμενο ρομπότ και τοίχος» και τρέξε τον κώδικα. Τι παρατηρείς;",
  step4Title: "Προσέγγιση τοίχου",
  step4Content: "Προσεγγίζει τελικά το ρομπότ τον τοίχο; Σταματάει στον τοίχο; Μπορείς να τροποποιήσεις τον κώδικα ώστε το ρομπότ να σταματάει δίπλα στον τοίχο;",
};


MSG.tutorials.avoidWall = {
  step1Title: "Αποφυγή τοίχου",
  step1Content: "Ενεργοποίησε την προβολή προσομοιωτή.",
  step2Title: "Αποφυγή τοίχου",
  step2Content: "Ενεργοποίησε την προβολή σεναρίου.",
  step3Title: "Αποφυγή τοίχου",
  step3Content: "Άλλαξε το σενάριο στο «Κινούμενο ρομπότ και τοίχος» και τρέξε τον κώδικα. Τι παρατηρείς;",
  step4Title: "Αποφυγή τοίχου",
  step4Content: "Καταφέρνει το ρομπότ να αποφύγει τον τοίχο στρίβοντας λίγο πριν τον φτάσει; Μπορείς να τροποποιήσεις τον κώδικα ώστε το ρομπότ να συνεχίσει να κινείται χωρίς ποτέ να προσκρούει στον τοίχο;",
};


//TODO: Translate
MSG.tutorials.nameOnLcdBasic = {
  step0Title: "Είσαι σίγουρος;",
  step0Content: "Είσαι σίγουρος; Όταν κάνεις κλικ στη συνέχεια, τα μπλοκ στο φύλλο εργασίας θα αντικατασταθούν.",
  step1Title: "Όνομα στην οθόνη LCD",
  step1Content: "Σε αυτό το μάθημα θα μάθεις πώς να εμφανίσεις το όνομά σου στην οθόνη LCD. Βλέπεις ένα παράδειγμα πώς να το κάνεις αυτό.",
  step2Title: "Δοκιμή στην πλακέτα",
  step2Content: "Έλεγξε τον κώδικα συνδέοντας την πλακέτα Dwenguino στον υπολογιστή με το καλώδιο USB και πατώντας το κουμπί αναπαραγωγής.",
  step3Title: "Το όνομά σου",
  step3Content: "Αυτή τη στιγμή εμφανίζεται στην οθόνη το όνομα 'Tom'. Άλλαξε τον κώδικα ώστε να βλέπεις το όνομά σου.",
  step4Title: "Δύο γραμμές",
  step4Content: "Η οθόνη LCD έχει δύο γραμμές. Άλλαξε τη γραμμή στην οποία εμφανίζεται το όνομά σου επιλέγοντας 0 ή 1.",
  step5Title: "Δοκιμή",
  step5Content: "Δοκίμασε τον κώδικά σου.",
  step6Title: "Εξαιρετικά!",
  step6Content: "Μπράβο! Γνωρίζεις πλέον πώς να εμφανίσεις το όνομά σου στην οθόνη LCD.",
};


/*MSG.tutorials.hello_dwenguino = {
  label: "Hello World!",
};*/

MSG.logging = {
  setup: "Δοκιμαστική εγκατάσταση",
  login: "Σύνδεση",
  logout: "Log out",
  firstname: "First name",
  newuser: "Νέος χρήστης",
  username: "Όνομα χρήστη",
  chooseUsername: "Επίλεξε όνομα χρήστη",
  email: "Email address",
  enterEmail: "Enter email address",
  forgotPassword: "I forgot my password",
  secretCode: "Secret code",
  enterSecretCode: "Enter your secret code sent to you by email",
  userDoesNotExist: "This user does not exist. Try a different email address.",
  resetPassword: "Reset your password",
  back: "Back",
  enterFirstname: "Enter your first name",
  password: "Password",
  repeatedPassword: "Repeat password",
  enterPassword: "Enter password",
  enterRepeatedPassword: "Repeat your password",
  choosePassword: "Επίλεξε 4 προσωπικά εικονίδια ως το συνθηματικό σου. Θα χρειαστεί να τα απομνημονεύσεις με τη σωστή σειρά.",
  currentlySelected: "Τρέχοντα επιλεγμένα: ",
  role: "Role",
  student: "Student",
  teacher: "Teacher",
  verification: "Verify your email address",
  verificationSentTo: "A verification message has been sent to your email address. Click the link in the email to verify your account.",
  birth: "Ημερομηνία γέννησης",
  school: "Σχολείο",
  selectSchool: "Αναζήτηση με το όνομα του σχολείου...",
  agegroup: "Ηλικιακή ομάδα:",
  primary1: "Α Δημοτικού",
  primary2: "Β Δημοτικού",
  primary3: "Γ Δημοτικού",
  primary4: "Δ Δημοτικού",
  primary5: "Ε Δημοτικού",
  primary6: "ΣΤ Δημοτικού",
  secondary1: "Α Γυμνασίου",
  secondary2: "Β Γυμνασίου",
  secondary3: "Γ Γυμνασίου",
  secondary4: "Α Λυκείου",
  secondary5: "Β Λυκείου",
  secondary6: "Γ Λυκείου",
  gender: "Φύλο: ",
  gender1: "Γ",
  gender2: "Α",
  gender3: "X",
  gender4: "θα προτιμούσα να μην πω",
  activity: "Δραστηριότητα: ",
  name: "Όνομα ",
  date: "Ημερομηνία ",
  ok: "Εντάξει",
  reset: "Επαναφορά",
  person: "Άνθωπος",
  dog: "Σκύλος",
  car: "Αυτοκίνητο",
  camera: "Κάμερα",
  heart: "Καρδιά",
  plane: "Αεροπλάνο",
  house: "Σπίτι",
  umbrella: "Αλεξιβρόχιο",
  star: "Αστέρι",
  money: "Χρήματα",
  gift: "Δώρο",
  keys: "Κλειδιά",
  music: "Μουσική",
  snowflake: "Χιονονιφάδα",
  fire: "Φωτιά",
  envelope: "Φάκελος"
};

MSG.validator = {
  errSchool: "Επίλεξε σχολείο.",
  errId: "Δεν επέλεξες αρκετά εικονίδια.",
  errAgeGroup: "Επίλεξε την ηλικιακή σου ομάδα.",
  errGender: "Επίλεξε το φύλο σου.",
  errActivityId: "Ο τίτλος της εργασίας σου δε μπορεί να είναι κενός."
};