var MSG = {
  arduinoCodeCopied: "Arduino code copied to clipboard",
  title: "DwenguinoBlockly",
  blocks: "Blocchi",
  linkTooltip: "Salva e collega ai blocchi.",
  runTooltip: "Lancia il programma definito dai blocchi.",
  loadBlocksFileTooltip: "Carica un file salvato in precedenza",
  saveBlocksFileTooltip: "Salva un file sul tuo computer",
  toggleSimulator: "Attiva o disattiva la vista simulatore",
  badCode: "Errore:\n%1",
  timeout: "Numero massimo di iterazioni superato.",
  trashTooltip: "Elimina tutti i blocchi.",
  catLogic: "Logica",
  catLoops: "Loop",
  catMath: "Matematica",
  catText: "Testo",
  catLists: "Liste",
  catColour: "Colore",
  catArduino: "Arduino",
  catVariables: "Variabili",
  catFunctions: "Funzioni",
  catDwenguino: "Dwenguino",
  catSocialRobot: "Robot sociale",
  catComments: "Comments",
  catBoardIO: "IO",
  listVariable: "lista",
  textVariable: "testo",
  httpRequestError: "C'è stato un problema con questa richiesta.",
  linkAlert: "Condividi il tuo programma a blocchi a questo link:\n\n%1",
  hashError: "Spiacente, '%1' non corrisponde a nessun programma salvato.",
  xmlError: "Non posso caricare questo file. Forse è stato creato con una versione differente di Blockly?",
  badXml: "Errore nell'analisi dell'XML:\n%1\n\n Seleziona'OK' per eliminare i tuoi cambiamenti 'Cancella' per continuare a editare l'XML.",
  pressed: "PREMUTO",
  setup: "setup",
  loop: "loop",
  dwenguino_main_program_structure: "Le istruzioni contenute nel blocco setup sono eseguite una volta soltanto, all'avvio del programma. Il codice contenuto nel blocco loop è ripetuto continuamente, fino a quando il programma non viene arrestato.",
  catDwenguino: "Dwenguino",
  delay_help: "Attendi per una quantità stabilita di millisecondi (1 millisecondo = 1000 secondi)",
  delay: "delay",
  clearLCD: "Pulisci LCD",
  dwenguinoLCD: "Dwenguino LCD %1 %2 %3 Scrivi testo: %4 Sulla riga: %5 A partire dalla colonna: %6",
  pin: "pin",
  toneOnPin: "Suona una nota su ",
  frequency: "con frequenza",
  noToneOnPin: "Ferma la nota su",
  toneOnPinTooltip: "Riproduce una nota con una frequenza specifica su un pin specificato",
  noToneOnPinTooltip: "Ferma la nota sul pin",
  trig: "Invia un segnale attraverso il pin numero",
  echo: "fa un echo sul pin numero",
  sonarTooltip: "Questo sensore sonar misura una distanza",
  miliseconds: "ms",
  digitalRead: "Leggi un valore digitale da",
  digitalWriteToPin: "Scrivi su",
  digitalWriteValue: "valore digitale",
  digitalWriteTooltip: "Scrivi un valore high o low su un pin digitale della scheda Dwenguino",
  digitalReadTooltip: "Leggi un valore digitale (1/high o 0/low) da un pin specifico",
  high: "HIGH",
  low: "LOW",
  highLowTooltip: "Rapresenta un valore high (1) o low (0) su un pin.",
  tutsIntroduction: "Introduzione",
  tutsTheremin: "Theremin",
  tutsRobot: "Robot",
  tutsHelloDwenguino: "Hello Dwenguino!",
  simulator: "Simulatore",
  setLedState: "Cambia %1 %2",
  setLedStateTooltip: "Accendi o spegni un led sulla scheda Dwenguino",
  ledPinsTooltip: "Seleziona il led che vuoi controllare",
  dwenguinoOn: "ON",
  dwenguinoOff: 'OFF',
  dwenguinoOnOffTooltip: "Seleziona un variabile per cambiare lo stato del led ON o OFF",
  dwenguinoLedBlock: "led",
  dwenguinoSonarBlock: "Sonar %1 %2 %3 trig pin number %4 echo pin number %5",
  dwenguinoServoBlock: "Motore servo %1 %2 %3 canale # %4 angolo %5",
  dwenguinoServoDropdownBlock: "Servo motor %1",
  dwenguinoServoBlockTooltip: "Posiziona uno dei servomotori connessi a Dwenguino a un angolo compreso fra 0 e 180 gradi",
  dwenguinoServoDropdownTooltip: "Seleziona uno dei due motori servo interni.",
  dwenguinoServoOne: "1",
  dwenguinoServoTwo: "2",
  dwenguinoDCMotorBlock: "Motore DC %1 %2 %3 canale %4 velocità %5",
  dwenguinoDCMotorBlockTooltip: "Imposta la velocità dei due motori collegabili alla scheda. Velocità = valori compresi fra -255 (massima velocità all'indietro) e 255 (massima velocità in avanti)",
  dwenguinoAnalogWriteBlock: "Scrivi su",
  dwenguinoAnalogValue: "il valore analogico",
  dwenguinoAnalogWriteTooltip: "Scrivi una valore analogico compreso fra 0 e 255 su un pic specificato",
  dwenguinoAnalogRead: "Leggi un valore analogico dal pin %1",
  dwenguinoAnalogWriteTooltip: "Leggi un valore compreso fra 0 e 255 dal pin specificato.",
  digitalReadSwitch: "Leggi dal pulsante %1",
  waitForSwitch: "attendere fino a quando si preme %1 il pulsante",
  digitalReadSwitchTooltip: "Leggi un valore da uno dei pulsanti di Dwenguino",
  north: "Nord",
  east:"Est",
  south: "Sud",
  west: "Ovest",
  center: "Centro",
  ledsReg: "led",
  dwenguinoLedsRegTooltip: "Puoi accendere o spegnere i led da 0 a 7 usando un numero binario. Per esempio 0b00001111 accenderà i led da 0 a 3, mantenendo gli altri spenti.",
  pressed: "PREMUTO",
  notPressed: "NON PREMUTO",
  pressedTooltip: "Rappresenta lo stato del pulsante. Usa questi valori per confrontare lo stato attuale di uno o più pulsanti.",
  create_global: "Crea globale",
  socialRobotRgbLedBlock: "RGB led",
  socialRobotPinRed: "pin rosso",
  socialRobotPinGreen: "pin verde",
  socialRobotPinBlue: "pin azzurro",
  socialRobotRgbLedOffBlock: "Spegni la RGB led con",
  socialRobotRgbColorBlock: "colore RGB %1",
  socialRobotRgbColor: "rosso %1 verde %2 azzurro %3",
  socialRobotLedmatrixImageBlock: "Mostra il modello sul segmento della matrice led",
  socialRobotLedmatrixImageBlockTooltip: "Mostra il dato modello led sul display della matrice led.",
  socialRobotLedmatrixEyePatternBlock: "Mostra il 'Eye Pattern'",
  socialRobotLedmatrixEyePatternBlockTooltip: 'Mostra il dato \'Eye Pattern\' sul display della matrice LED.',
  socialRobotLedmatrixEyePatternSegmentBlock: "sul segmento della matrice led",
  socialRobotLedmatrixClearSegmentBlock: "Svuota il segmento della matrice led",
  socialRobotLedmatrixClearSegmentBlockTooltip: 'Svuota un segmento di scelta della matrice led.',
  socialRobotLedmatrixClearDisplayBlock: "Svuota la matrice led",
  socialRobotLedmatrixClearDisplayBlockTooltip: 'Svuota l\'intero modello della matrice led.',
  socialRobotPirBlock: "Sensore di prossimità %1 %2 %3 trig pin numero %4",
  socialRobotSoundSensorBlock: "Sensore sonoro %1 %2 %3 pin %4",
  socialRobotSoundSensorBlockTooltip: "",
  socialRobotTouchSensorBlock: "Sensore tattile %1 %2 %3 pin %4",
  socialRobotTouchSensorBlockTooltip: "",
  socialRobotButtonBlock: "Pulsante %1 %2 %3 pin %4",
  socialRobotButtonBlockTooltip: "",
  socialrobotSetPinState: "Fissa %1 %2",
  socialrobotServoBlock: "Motore servo %1 %2 %3 pin %4 angolo %5",
  socialrobotWaveArmesBlock: "Agita le braccia %1 %2 servo pin braccio destro %3 %4 servo braccio sinistro %5 %6",
  socialRobotArmsDownBlock: "Abbassa le braccia %1 %2 %3 servo pin braccio destro %4 %5 servo pin braccio sinistro %6 %7",
  socialRobotArmsUpBlock: "Alza le braccia %1 %2 %3 servo pin braccio destro %4 %5 servo pin braccio sinistro %6 %7",
  socialRobotEyesLeftBlock: "Gira gli occhi a sinistra %1 %2 %3 servo pin occhio sinistro %4 %5 servo pin occhio destro %6 %7",
  socialRobotEyesRightBlock: "Gira gli occhi a destra %1 %2 %3 servo pin occhio sinistro %4 %5 servo pin occhio destro %6 %7",
  socialrobotReadPinBlock: "Leggi valore del pin %1 %2",
  socialRobotServoRightHand: "Servo pin mano destra",
  socialRobotServoLeftHand: "Servo pin mano sinistra",
  sonarSliderLabel: "Distanza sonar",
  pirButtonLabel: "pulsante sensore di prossimità",
  soundButtonLabel: "pulsante sensore sonoro",
  touchButtonLabel: "pulsante sensore tattile",
  lightSensorSliderLabel: "pulsante sensore di luce",
  servoCostume: "Aspetto",
  servoOptions: "Opzioni del motore servo",
  sonarOptions: "Opzioni del sensore sonar",
  lcdOptions: "Opzioni dello schermo LCD",
  pirOptions: "Opzioni del sensore di prossimità",
  soundOptions: "Opzioni del sensore sonoro",
  touchOptions: "Opzioni del sensore tattile",
  buttonOptions: "Opzioni del pulsante",
  lightOptions: "Opzioni del sensore di luce",
  rgbLedOptions: "Opzioni del led RGB",
  ledmatrixOptions: 'Led  Matrix Options',
  ledOptions: "LED options",
  ledOptions: "Opzioni del led",
  pinOptions: "Pin",
  colorOptions: "Colore",
  runError: "<h3>Mi dispiace, non ho potuto caricare il codice sulla scheda.</h3>",
  uploadError: "Segui questi passi per riavviare la scheda Dwenguino: \n    1. Scollega il cavo USB \n    2. Collega il computer e la scheda Dwenguino con il cavo USB \n    3. Allo stesso tempo preme i pulsanti RESET e SUD della scheda Dwenguino \n    4. Prima rilascia il pulsante RESET \n    5. Poi rilascia il pulsante SUD \n    6. Ricarica il programma via <span id='db_menu_item_run' class='fas fa-play-circle' alt='Upload code to Dwenguino board'></span> button in the main menu",
  cleanError: "Non si è potuto rimuovere il codice precedente.\nVerifica se c'è un'altra applicazione che utilizza un file .cpp.\n Chiusi quest'applicazione.",
  compileError: "Non si è potuto compilare il codice.\nDevi verificare il tuo codice, forse hai dimenticato un blocco.",
  dwenguinoStepperMotorBlock: "motore passo a passo %1 %2 %3 numero %4 quantità di passi %5",
  dwenguinoStepperMotorBlockTooltip: "TODO",
  drawingrobotMove:"Sposta il pennarello con un angolo di %1 gradi in %2 passi",
  drawingrobotMoveXY:"Sposta il pennarello %1 a destra e %2 a sinistra",
  drawingrobotLine:"Traccia una linea fino a x: %1 y: %2",
  drawingrobotCircle:"Disegna un cerchio con raggio: %1",
  drawingrobotRectangle:"Disegna un rettangolo di larghezza: %1 e di altezza: %2",
  drawingrobotLiftStylus: "Solleva il pennarello",
  drawingrobotLowerStylus: "Posa il pennarello",
  drawingrobotChangeColor: "Colore %1",
  up:"su",
  down:"giù",
  left:"sinistra",
  right:"destra",
  bounds:"Attenzione\nProvi a disegnare fuori dal foglio",
  drawingrobotgrid: "griglia",
  colorpicker:"colore",
  drawingrobotSaveImage:"Salva il disegno",
  drawingrobotDrawing:"Disegno",
  clear: "Cancellare",
  save: "Salvare",
};

MSG.cookieConsent = {
  close: "Close",
  cookieConsent: "We use functional cookies to set up the Dwenguino simulator. ",
  cookieInfo: "More info on how we use cookies.",
  whatAreCookiesTitle: "Wat zijn cookies?",
  whatAreCookiesDescription1: "Cookies zijn kleine tekstbestanden die lokaal worden opgeslagen op uw computer. Deze cookies dienen voor tal van doeleinden: het onthouden van instellingen (login, taalkeuzes), het vergaren van informatie en het bijhouden van het bezoekgedrag van de gebruikers.",
  whatAreCookiesDescription2: "De cookies die wij gebruiken zijn veilig: zij hebben geen toegang tot persoonlijke informatie op uw computer en kunnen deze niet beschadigen of besmetten met virussen. De cookies geven op geen enkele manier persoonlijke informatie aan ons door. De informatie die we via cookies verzamelen helpt ons om je van specifieke diensten te laten genieten.",
  whatAreNecessaryCookiesTitle: "Wat zijn noodzakelijke cookies?",
  whatAreNecessaryCookiesDescription: "Noodzakelijke cookies zijn cookies die je nodig hebt om te surfen op de website en gebruik te maken van de functionaliteit die we aanbieden. Bovendien zijn de cookies noodzakelijk om de beveiligde onderdelen van de website te kunnen zien.",
  whichCookiesTitle: "Welke cookies gebruikt deze website?",
  dwengoCookieTitle: "Aanmelden als gebruiker (Dwengo cookie)",
  dwengoCookieDescription: "Bij het aanmelden op de website wordt een tijdelijke cookie gebruikt waardoor je herkend wordt als gebruiker. Met behulp van deze cookie wordt onder andere je taalinstelling en vooruitgang bewaard. De cookie zorgt er voor dat je toegang hebt tot de beveiligde delen van de website. Deze cookie is slechts geldig tot aan het einde van de sessie en is enkel beschikbaar voor en gemaakt door Dwengo vzw.",
  jenkinsCookieTitle: "Jenkins configuratie (Jenkins cookie)",
  jenkinsCookieDescription: "De Jenkins cookie is voor ons noodzakelijk om de Dwenguino simulator online op een server te kunnen installeren. Jenkins is software waarvan we gebruik maken om onze simulator te updaten. Die cookie bevat informatie over de instellingen van Jenkins en bevat dus ook geen enkele informatie over jou als gebruiker.",
};

MSG.dropzone = {
  dictSelectFile: "Seleziona un file.",
  dictChooseFile: "Scegli un file",
  dictDefaultMessage: "Posa qui i files per carica",
  dictFallbackMessage: "Il tuo browser non supporta il caricamento di files Drag and Drop.",
  dictFileTooBig: "File troppo grande ({{filesize}}MiB). Dimensione massima del file: {{maxFilesize}}MiB.",
  dictFallbackText: "Si prega di utilizzare il modulo di ripiego qui sotto per caricare i tuoi files come nei tempi antichi.",
  dictInvalidFileType: "Non si può caricare file di questo tipo.",
  dictResponseError: "Il server ha risposto con il codice {{statusCode}}.",
  dictCancelUpload: "Cancella caricamento",
  dictCancelUploadConfirmation: "Sei sicuro/a di voler cancellare questo caricamento?",
  dictRemoveFile: "Rimuovi il file",
  dictMaxFilesExceeded: "Non puoi caricare altri file.",
  dictUploadBlocks: "Blocchi di caricamento",
  dictFileNotSupported: "Questo tipo di file non è supportato.",
};

MSG.ledmatrix = {
  restPosition: 'Posizione di riposo', 
  blink1: 'Lampeggia 1',
  blink2: 'Lampeggia 2',
  blink3: 'Lampeggia 3',
  blink4: 'Lampeggia 4',
  blink5: 'Lampeggia 5',
  right1: 'Destra 1',
  right2: 'Destra 2',
  left1: 'Sinistra 1',
  left2: 'Sinistra 2',
  up1: 'Su 1',
  up2: 'Su 2',
  up3: 'Su 3',
  down1: 'Giù 1',
  down2: 'Giù 2',
  down3: 'Giù 3',
  angryLeft1: 'Arrabbiato sinistra 1',
  angryLeft2: 'Arrabbiato sinistra 2',
  angryLeft3: 'Arrabbiato sinistra 3',
  angryLeft4: 'Arrabbiato sinistra 4',
  angryRight1: 'Arrabbiato destra 1',
  angryRight2: 'Arrabbiato destra 2',
  angryRight3: 'Arrabbiato destra 3',
  angryRight4: 'Arrabbiato destra 4',
  sadLeft1: 'Triste sinistra 1',
  sadLeft2: 'Triste sinistra 2',
  sadLeft3: 'Triste sinistra 3',
  sadRight1: 'Triste destra 1',
  sadRight2: 'Triste destra 2',
  sadRight3: 'Triste destra 3',
  evilLeft1: 'Maligno sinistra 1',
  evilLeft2: 'Maligno sinistra 2',
  evilRight1: 'Maligno destra 1',
  evilRight2: 'Maligno destra 2',
  scanHorizontal1: 'Scansione orizzontale 1',
  scanHorizontal2: 'Scansione orizzontale 2',
  scanHorizontal3: 'Scansione orizzontale 3',
  scanHorizontal4: 'Scansione orizzontale 4',
  scanVertical1: 'Scansione verticale 1',
  scanVertical2: 'Scansione verticale 2',
  scanVertical3: 'Scansione verticale 3',
  scanVertical4: 'Scansione verticale 4',
  scanVertical5: 'Scansione verticale 5',
  scanVertical6: 'Scansione verticale 6',
  rip1: 'RIP 1',
  rip2: 'RIP 2',
  peering1: 'Scrutare 1',
  peering2: 'Scrutare 2',
  peering3: 'Scrutare 3',
  peering4: 'Scrutare 4'
};

MSG.simulator = {
  start: "Avvia",
  stop: "Ferma",
  pause: "Pausa",
  step: "1 Step",
  speed: "Velocità",
  speedVerySlow: "40 volte più lento",
  speedSlow: "20 volte più lento",
  speedMedium: "10 volte più lento",
  speedFast: "5 volte più lento",
  speedVeryFast: "2 volte più lento",
  speedRealTime: "Real-time",
  components: "Seleziona i componenti",
  servo: "Servo",
  servoDescription: "Un motore servo è un attuatore che può <b>ruotare un oggetto di una certa angolazione</b>. I motori servo possono essere posizionati con un angolo dai 0 e 180 gradi. Motori servo possono essere decorato con facilità e sono dunque ideali per creare componenti mobili regolarmente.",
  motor: "Motore",
  DCMotorDescription: "Un motore a corrente continua o motore DC gira completamente. Puoi utilizzare un tale motore per far girare il robot. Indica la velocità e la direzione del motore nel tuo programma come un numero dal -255 fino al 255.",
  scope: "Variabili",
  alertDebug: "Arresta la simulazione prima di tornare al programma",
  distance: "distanza",
  scenario: "Scenario",
  scenario_default: "Scheda normale",
  scenario_moving: "Robot mobile",
  scenario_wall: "Robot mobile con muro",
  code: "Codice",
  pir: "sensore di prossimità",
  pirDescription: "Utilizza questo sensore per <b>percepire movimenti<b>. Premendo il pulsante nel simulatore, puoi simulare movimenti. Se il sensore rileva cambiamenti, si dà un 1, se no un 0.",
  sonar: "Sonar",
  sonarDescription: "Utilizza questo sensore per rilevare un oggetto o una persona e per determinare a quale distanza i sensore si trovano dalla persona o l'oggetto. È previsto una barra di scorrimento nel simulatore per simulare la distanza tra l'oggetto e il sensore. Il sensore dà la distanza in centimetri.",
  led: "led",
  ledDescription: "Nel simulatore disponi di led in quattro colori. Un led è controllato da un pin che indichi tu. Se il pin si trova nello stato ALTO, il led brucia. Se il pin si trova nello stato BASSO, il led è spento.",
  rgbled: "RGB led",
  rgbledDescription: "",
  ledmatrix: "matrice led",
  ledmatrixDescription: "",
  ledmatrixsegment: "LED matrix",
  ledmatrixsegmentDescription: "",
  touch: "Sensor tattile",
  touchDescription: "Utilizza questo sensore per rilevare se il robot viene toccato. È previsto un pulsante nel simulatore per simulare contatti che premendolo vengono attivati. Se il robot viene toccato, il sensore dà un 1, se no un 0.",
  lcd: "schermo LCD",
  lcdDescription: "Lo schermo LCD contiene due linee con 16 caratteri ciascuna. Trasmetti il testo desiderato nel tuo programma.",
  button: "Pulsante",
  buttonDescription: "",
  sound: "Sensore sonoro",
  soundSensor: "",
  light: "Sensore di luce",
  lightSensor: "",
  buzzer: "Cicalino",
  buzzerDescription: "Con il cicalino puoi riprodurre suoni con una frequenza che scegli tu. La frequenza desiderata (in Hz) lo trasmetti nel tuo programma. Determini per quanto tempo il suono viene sonato con un blocco di pausa.",
  decoration: "Decorazione"
};
MSG.tutorialMenu = {
  header: "Tutorials",
  catDwenguino: "Impara a programmare<br>con DwenguinoBlockly",
  catDwenguinoComponents: "Panoramica utile dei<br>componenti Dwenguino",
  catDwenguinoConnector: "Pin mapping &<br>connettore di espansione",  catRidingRobot: "Robot guidando",
  catSocialRobot: "Robot sociale",
  catWeGoStem: "WeGoSTEM",
  chooseCategory: "Seleziona una categoria di tutorial",
  chooseTutorial: "Seleziona un tutorial",
  previous: "Precedente",
  close: "Chiudi",
  checkAnswer: "Verifica risposta",
  correctAnswer: "La risposta è corretta!",
  wrongAnswer: "La risposta non è corretta. Prova di nuovo!",
  dwenguinoComponents: "Componenti Dwenguino",
  sensors: "Sensori",
  actuators: "Attuatori",
  movement: "Movimento",
  audio: "Audio",
  display: "Display"
};

MSG.tutorials = {
    introduction: {},
};

MSG.tutorials.general = {
  sureTitle: "Sei sicuro/a?",
  sureText: "Quando clicchi 'Prossimo', tutti i blocchi sul foglio di lavoro saranno sostituti.",
};

MSG.tutorials.introduction = {
  step1Title: "Benvenuto in DwenguinoBlockly",
  step1Content: "Ciao! Il mio nome è Dwenguino! Ti aiuterò a conoscere questa interfaccia di programmazione!",
  step2aTitle: "Area del codice Blockly",
  step2aContent: "In quest'area puoi aggiungere blocchi di codice. Affinché siano eseguiti devi metterli all'interno dei blocchi setup o loop.",
  step2bTitle: "La toolbox Blockly",
  step2bContent: "Questa è la scatola degli attrezzi: contiene i blocchi che puoi usare per comporre il tuo programma. I blocchi sono raccolti in diverse categorie, utili per aiutarti a orientarti fra le possibilità della scheda Dwenguino.",
  step3Title: "Seleziona la lingua",
  step3Content: "Usa questo menu per selezionare la lingua",
  step4Title: "Difficoltà",
  step4Content: "Con questo slider puoi selezionare il livello di difficoltà, scegliendo fra livello base e avanzato.",
  step5Title: "Dwengobook",
  step5Content: "I Dwengobook sono tutorial interattivi che ti guidano attraverso diverse sfide di robotica e programmazione.",
  step6Title: "Carica il programma",
  step6Content: "Quando hai terminato di comporre il tuo codice, puoi caricarlo sulla scheda Dwenguino usando questo pulsante. Assicurati di aver selezionato nella IDE Arduino la scheda corretta e la porta corrispondente prima di effettuare il caricamento.",
  step7Title: "Apri",
  step7Content: "Questo pulsante ti permette di aprire un programma salvato in precedenza.",
  step8Title: "Salva",
  step8Content: "Con questo pulsante puoi salvare il tuo codice in un file locale.",
  step9Title: "Simulatore",
  step9Content: "In futuro potrai usare questo pulsante per aprire il simulatore. Per ora puoi usarlo per testare il tuo codice!"
};

MSG.logging = {
  setup: "Configurazione",
  login: "Accedere",
  logout: "Log out",
  firstname: "First name",
  newuser: "Nuovo utente",
  username: "Nome utente",
  chooseUsername: "Scegli un nome utente",
  email: "Email address",
  enterEmail: "Enter email address",
  forgotPassword: "I forgot my password",
  secretCode: "Secret code",
  enterSecretCode: "Enter your secret code sent to you by email",
  userDoesNotExist: "This user does not exist. Try a different email address.",
  resetPassword: "Reset your password",
  back: "Back",
  enterFirstname: "Enter your first name",
  password: "Password",
  repeatedPassword: "Repeat password",
  enterPassword: "Enter password",
  enterRepeatedPassword: "Repeat your password",
  choosePassword: "Seleziona 4 icone personali come password. Bisogna ricordarsi di questi nel giusto ordine.",
  currentlySelected: "Attualmente selezionato: ",
  role: "Role",
  student: "Student",
  teacher: "Teacher",
  verification: "Verify your email address",
  verificationSentTo: "A verification message has been sent to your email address. Click the link in the email to verify your account.",
  birth: "Data di nascita",
  school: "Scuola",
  selectSchool: "Cerca per nome di scuola...",
  agegroup: "Fascia d'età:",
  primary1: "Scuola elementare 1",
  primary2: "Scuola elementare 2",
  primary3: "Scuola elementare 3",
  primary4: "Scuola elementare 4",
  primary5: "Scuola elementare 5",
  primary6: "Scuola elementare 6",
  secondary1: "Scuola superiore 1",
  secondary2: "Scuola superiore 2",
  secondary3: "Scuola superiore 3",
  secondary4: "Scuola superiore 4",
  secondary5: "Scuola superiore 5",
  secondary6: "Scuola superiore 6",
  gender: "Genere: ",
  gender1: "D",
  gender2: "H",
  gender3: "X",
  gender4: "Preferisco non dirlo",
  activity: "Attività: ",
  name: "Nome ",
  date: "Data ",
  ok: "D'accordo",
  continue: "Continue",
  reset: "Reset",
  person: "Persone",
  dog: "Cane",
  car: "Macchina",
  camera: "Fotocamera",
  heart: "Cuore",
  plane: "Aereo",
  house: "Casa",
  umbrella: "Ombrello",
  star: "Stella",
  money: "Soldi",
  gift: "Regalo",
  keys: "Chiavi",
  music: "Musica",
  snowflake: "Neve",
  fire: "Fuoco",
  envelope: "Busta",
  conditions: "Voorwaarden",
  conditions1: "Om de app te gebruiken, moet je akkoord gaan met de <b>gebruiksvoorwaarden</b> en het <b>privacybeleid</b>.",
  generalConditions: "de gebruiksvoorwaarden",
  privacyStatement: "het privacybeleid",
  conditions2: "Daar staat onder andere in dat je moet inloggen om te beschikken over functionaliteit zoals het bewaren van je programma's of het bijhouden van je voortgang, dat je data anoniem wordt gelogd en verwerkt, en dat je ons mag mailen met vragen over privacy.",
  conditions3: "Ben je <b>13 jaar of ouder?</b> Dan mag je hieronder <b>zelf bevestigen</b> dat je de info hebt gelezen en akkoord gaat.",
  conditions4: "Ben je <b>12 jaar of jonger?</b> Dan moet een van je ouders of voogden toestemming geven.",
  acceptConditions: "Ik ga akkoord met de gebruiksvoorwaarden en het privacybeleid van de Dwengo-simulator",
  acceptResearch: "Ik geef toestemming aan Dwengo vzw om de gegevens die de simulator verzamelt, voor <b>wetenschappelijk onderzoek</b> te gebruiken, geanonimiseerd en volgens het privacybeleid.",
  anonymized: "* <b>\'Geanonimiseerd\'</b> wil zeggen dat er geen link is tussen je persoonsgegevens en je data. Niemand weet dus wat je deed in de simulator."
};

MSG.validator = {
  errSchool: "Seleziona una scuola.",
  errId: "Non hai selezionato abbastanza icone.",
  errAgeGroup: "Seleziona fascia d'età.",
  errGender: "Seleziona il tuo genere.",
  errFirstname: "Je voornaam is niet ingevuld.",
  errLastname: "Je achternaam is niet ingevuld.",
  errPassword: "Je paswoord voldoet niet aan de voorwaarden.",
  errPasswordNotIdentical: "Je paswoorden zijn niet identiek.",
  errEmail: "Je email is niet geldig",
  errActivityId: "Il titolo della attività non può essere vuoto.",
  errAcceptConditions: "Je hebt de gebruiksvoorwaarden en het privacybeleid nog niet geaccepteerd.",
  errAcceptResearch: "Je hebt nog geen toestemming gegeven om de gegevens voor wetenschappelijk onderzoek te laten gebruiken.",
  errRequiredFields: "Je hebt niet alle velden ingevuld.",
  errRoleInvalid: "De opgegeven rol is niet geldig."
};