var MSG = {
tajuk: "DwenguinoBlockly",
blok: "Blok",
linkTooltip: "Simpan dan sambungkan ke blok.",
runTooltip: "Jalankan program yang ditentukan oleh blok di ruang kerja.",
loadBlocksFileTooltip: "Muatkan fail blok yang disimpan sebelum ini",
saveBlocksFileTooltip: "Simpan blok ke file lokal",
toggleSimulator: "Togol tampilan simulator.",
badCode: "Ralat program: \ n %1",
timeout: "Pelaksanaan pelaksanaan maksimum melebihi.",
trashTooltip: "Buang semua blok.",
catLogic: "Logik",
catLoops: "Loop",
catMath: "Matematik",
catText: "Teks",
catLists: "Senarai",
catColour: "Color",
catArduino: "Arduino",
catVariables: "Pemboleh ubah",
catFunctions: "Functions",
catDwenguino: "Dwenguino",
catSocialRobot: "Social robot",
catComments: "Comments",
catBoardIO: "IO",
listVariable: "list",
textVariable: "text",
httpRequestError: "Terdapat masalah dengan permintaan itu.",
linkAlert: "Kongsi blok anda dengan pautan ini: \ n \ n %1",
hashError: "Maaf, '%1' tidak sesuai dengan mana-mana program yang disimpan.",
xmlError: "Tidak dapat memuat fail yang disimpan anda Mungkin ia telah dibuat dengan versi berbeza Blockly?",
badXml: "Error parsing XML: \ n%1 \ n \ nPilih 'OK' untuk meninggalkan perubahan anda atau 'Cancel' untuk selanjutnya mengedit XML.",
pressed: "DITERIMA",
setup: "persediaan",
loop: "gelung",
dwenguino_main_program_structure: "Kod dalam blok persediaan dilaksanakan sekali pada permulaan program. Kod dalam gelung diulangi sehingga program berhenti.",
catDwenguino: "Dwenguino",
delay_help: "Tunggu sebilangan milisecond tertentu (1 milisecond = 1000 saat)",
delay: "kelewatan",
clearLCD: "Clear LCD",
dwenguinoLCD: "Dwenguino LCD %1 %2 %3 Tulis teks: %4 Pada baris: %5 Bermula dari lajur: %6",
pin: "pin",
toneOnPin: "Mainkan nada",
frequency: "dengan kekerapan",
noToneOnPin: "Berhenti nada",
toneOnPinTooltip: "Nada main dengan kekerapan tertentu pada pin tertentu",
noToneOnPinTooltip: "Hentikan nada di pin",
trig: "nombor pin trig",
echo: "nombor pin echo",
sonarTooltip: "Sensor ini membaca jarak dari sensor sonar",
miliseconds: "ms",
digitalRead: "Baca nilai digital dari",
digitalWriteToPin: "Tulis pada",
digitalWriteValue: "nilai digital",
digitalWriteTooltip: "Tulis nilai tinggi atau rendah pada pin digital lembaga Dwenguino",
digitalReadTooltip: "Baca nilai digital (1 / tinggi atau 0 / rendah) dari pin yang ditentukan",
high: "TINGGI",
low: "RENDAH",
highLowTooltip: "Merupakan nilai tinggi (1) atau rendah (0) pada pin.",
tutsIntroduction: "Pengenalan",
tutsTheremin: "Theremin",
tutsRobot: "Robot",
tutsHelloDwenguino: "Hello Dwenguino!",
tutsNameOnLcd: "Name on LCD",
tutsBlinkLED: "Blink LED",
tutsLedOnButtonPress: "LED on button press",
tutsBitPatternOnLeds: "Bit pattern on leds",
tutsAllButtons: "All buttons",
tutsDriveForward: "Drive forward",
tutsRideInSquare: "Ride a square",
tutsRideToWall: "Ride to wall",
tutsAvoidWall: "Avoid wall",
simulator: "Simulator",
setLedState: "Putaran",
setLedStateTooltip: "Hidupkan atau matikan papan pada papan Dwenguino",
ledPinsTooltip: "Pic yang dipimpin anda mahu mengawal",
dwenguinoOn: "ON",
dwenguinoOff: 'OFF',
dwenguinoOnOffTooltip: "Pilih nilai untuk menghidupkan LED ON atau OFF",
dwenguinoLedBlock: "LED",
dwenguinoSonarBlock: "Sonar",
channel: "channel #",
angle: "angle",
speed: "speed",
dwenguinoServoBlock: "Servo motor",
dwenguinoServoBlockTooltip: "Tetapkan satu servo yang disambungkan ke Dwenguino ke sudut tertentu antara 0 dan 180 darjah",
dwenguinoServoOne: "1",
dwenguinoServoTwo: "2",
dwenguinoServoDropdownTooltip: "Select one of the two internal servo motors",
dwenguinoDCMotorBlock: "DC Motor",
dwenguinoDCMotorBlockTooltip: "Tetapkan kelajuan salah satu daripada dua motor dwenguino Speed = nilai antara -255 (kelajuan penuh ke belakang) dan 255 (kelajuan penuh ke depan)",
dwenguinoAnalogWriteBlock: "Tulis kepada",
dwenguinoAnalogValue: "nilai analog",
dwenguinoAnalogWriteTooltip: "Tulis nilai analog antara 0 dan 255 ke pin yang ditentukan",
dwenguinoAnalogReadBlock: "Baca nilai analog dari",
dwenguinoAnalogWriteTooltip: "Baca nilai beteween 0 dan 255 dari pin yang ditentukan",
digitalReadSwitch: "Baca suis %1",
waitForSwitch: "wait until button %1 is pressed",
digitalReadSwitchTooltip: "Baca nilai dari salah satu suis dwenguino",
north: "Utara",
east: "Timur",
south: "Selatan",
west: "Barat",
center: "Pusat",
ledsReg: "LEDS",
dwenguinoLedsRegTooltip: "Anda boleh menghidupkan 0 hingga 7 dengan menggunakan nombor binari, contohnya 0b00001111 akan bertukar menjadi 0 hingga 3 dan sisanya",
pressed: "DITERIMA",
notPressed: "TIDAK BERTINGKAT",
pressedTooltip: "Merupakan keadaan butang. Gunakan nilai ini untuk membandingkan dengan keadaan butang sebenar",
create: "Create",
with_type: "with type",
create_global: "Create global",
socialRobotRgbLedBlock: "RGB LED",
socialRobotPinRed: "pin red",
socialRobotPinGreen: "pin green",
socialRobotPinBlue: "pin blue",
socialRobotRgbLedOffBlock: "Turn the RGB LED off with",
socialRobotRgbColorBlock: "RGB color",
socialrobotPirBlock: "Pir",
socialrobotSetPinBlock: "Set",
socialrobotReadPinBlock: "Read value of pin",
socialrobotServoBlock: "Servo motor",
socialrobotWaveArmesBlock: "Wave arms",
socialRobotArmsDownBlock: "Put arms down",
socialRobotArmsUpBlock: "Put arms up",
socialRobotEyesLeftBlock: "Turn eyes left",
socialRobotEyesRightBlock: "Turn eyes right",
socialRobotServoRightHand: "Servo right hand",
socialRobotServoLeftHand: "Servo left hand",
socialRobotServoRightEye: "Servo pin right eye",
socialRobotServoLeftEye: "Servo pin left eye", 
sonarSliderLabel: "Sonar distance",
pirButtonLabel: "PIR button",
soundButtonLabel: "Sound button",
lightSensorSliderLabel: "Light sensor button",
servoCostume: "Costume",
servoOptions: "Servo motor options",
sonarOptions: "Sonar sensor options",
lcdOptions: "LCD screen options",
pirOptions: "PIR sensor options",
soundOptions: "Sound sensor options",
lightOptions: "Light sensor options",
rgbLedOptions: "RGB LED options",
ledOptions: "LED options",
runError: "Oops there was an error when trying to run your code on the board.",
runError: "<h3>Sorry, I was unable to upload the code to the board</h3>",
uploadError: "Follow these steps to restart the Dwenguino board: \n    1. Disconnect the USB cable \n    2. Connect the computer and Dwenguino board with the USB cable \n    3. Simultaneously press the RESET and the SOUTH button of the Dwenguino board \n    4. Then first release the RESET button \n    5. Then release the SOUTH button \n    6. Upload the program again via the <span id='db_menu_item_run' class='glyphicon glyphicon-play' alt='Upload code to Dwenguino board'></span> button in the main menu",
compileError: "The code could not be compiled.\nYou should check your code, did you forget a block someware?",

//TODO: translate
  dwenguinoStepperMotorBlock: "stepper-motor %1 %2 %3 nummer %4 aantal stappen %5",
  dwenguinoStepperMotorBlockTooltip: "TODO",
  drawingrobotMove:"Verplaats de stift onder een van hoek %1 graden met %2 stappen",
  drawingrobotMoveXY:"Verplaats de stift %1 naar rechts en %2 naar links",
  drawingrobotLine:"Teken een lijn naar x: %1 y: %2",
  drawingrobotCircle:"Teken een cirkel met straal: %1",
  drawingrobotRectangle:"Teken een rechthoek met breedte: %1 en hoogte: %2",
  drawingrobotLiftStylus: "Stift opheffen",
  drawingrobotLowerStylus: "Stift neerzetten",
  drawingrobotChangeColor: "Kleur %1",
  up:"omhoog",
  down:"omlaag",
  left:"links",
  right:"rechts",
  bounds:"Opgelet\nJe probeert buiten het papier te tekenen",
  drawingrobotgrid: "raster",
  colorpicker:"Kleur",
  drawingrobotSaveImage:"Tekening opslaan",
  drawingrobotDrawing:"Tekening",
};


MSG.dropzone = {
  dictSelectFile: "Select a file.",
  dictChooseFile: "Choose file",
  dictDefaultMessage: "Drop files here to upload",
  dictFallbackMessage: "Your browser does not support drag'n'drop file uploads.",
  dictFileTooBig: "File is too big ({{filesize}}MiB). Max filesize: {{maxFilesize}}MiB.",
  dictFallbackText: "Please use the fallback form below to upload your files like in the olden days.",
  dictInvalidFileType: "You can't upload files of this type.",
  dictResponseError: "Server responded with {{statusCode}} code.",
  dictCancelUpload: "Cancel upload",
  dictCancelUploadConfirmation: "Are you sure you want to cancel this upload?",
  dictRemoveFile: "Remove file",
  dictMaxFilesExceeded: "You can not upload any more files.",
}

MSG.simulator = {
start: "Mula",
stop: "Berhenti",
pause: "Jeda",
step: "1 Langkah",
speed: "Kelajuan",
speedVerySlow: "40 kali perlahan",
speedSlow: "20 kali perlahan",
speedMedium: "10 kali perlahan",
speedFast: "5 kali perlahan",
speedVeryFast: "2 kali perlahan",
speedRealTime: "Real-time",
components: "Pilih komponen",
servo: "Servo",
motor: "Motor",
scope: "Pemboleh ubah",
alertDebug: "Hentikan penyelakuan sebelum menyambung semula ke program",
distance: "jarak",
scenario: "Senario",
senario_default: "Papan biasa",
scenario_moving: "Bergerak robot",
scenario_wall: "Memindahkan robot dengan dinding",
code: "Kod",
pir: "PIR sensor",
pirDescription: "A passif infrared (PIR) sensor allows you to <b>sense motion</b>, because it detects changes of infrared radiation in its environment",
sonar: "Sonar",
led: "LED",
ledDescription: "A light-emitting diode (LED) is a semiconductor device that <b>emits light</b> when an electric current passes through it. Different semiconductor materials produce <b>different colors of light</b>. ",
rgbled: "RGB LED",
rgbledDescription: "",
lcd: "LCD screen",
lcdDescription: "The LCD display on the Dwengo board is a 16x2 character display with backlight.",
button: "Button",
sound: "Sound sensor",
light: "Light sensor",
buzzer: "Buzzer",
buzzerDescription: "The buzzer on the Dwengo board can be used to <b>play a series of tones</b> or short sound fragments. The height of each tone is controlled by defining the <b>frequency</b> of the buzzer. Use a delay block to change the length of a tone.",
decoration: "Decoration"
};

MSG.socialrobot = {
  plain: "Default",
  eye: "Eye",
  mouth: "Mouth",
  righthand: "Right hand",
  lefthand: "Left hand",
};

MSG.tutorialMenu = {
  header: "Tutorials",
  catDwenguino: "Learn to program<br>with DwenguinoBlockly",
  catRidingRobot: "Riding robot",
  catSocialRobot: "Social robot",
  catWeGoStem: "WeGoSTEM",
  chooseCategory: "Select a tutorial category",
  chooseTutorial: "Select a tutorial",
  previous: "Previous",
  close: "Close",
}

MSG.tutorials = {
introduction: {},
};

MSG.tutorials.general = {
  sureTitle: "Are you sure?",
  sureText: "When you click 'Next' all blocks in the workspace will be removed.",
};

MSG.tutorials.introduction = {
step1Title: "Welkom to DwenguinoBlockly",
step1Content: "Hai, nama saya Dwenguino! Saya akan membantu anda untuk mengenali antara muka!",
step2aTitle: "Kawasan kod Block",
step2aContent: "Di kawasan ini, anda meletakkan blok kod anda. Anda harus meletakkan blok anda di dalam blok gelung setup jika anda mahu mereka dilaksanakan.",
step2bTitle: "Kotak peralatan Blockly",
step2bContent: "Ini adalah kotak peralatan, ia mengandungi semua blok yang boleh anda gunakan untuk mencipta program anda. Anda boleh meneroka cathegories yang berbeza untuk mengetahui apa yang boleh dilakukan oleh Dwenguino anda.",
step3Title: "Pemilihan bahasa",
step3Content: "Gunakan ini untuk menukar bahasa",
step4Title: "Difficulty",
step4Content: "Slider ini membolehkan anda menetapkan tahap yang sukar. Buat masa ini kami hanya menyediakan peringkat pemula dan maju.",
step5Title: "Dwengobooks",
step5Content: "Dwengobooks adalah tutorial interaktif yang membimbing anda melalui cabaran pengkomputeran fizikal yang berbeza.",
step6Title: "Kod muat naik",
step6Content: "Apabila kod anda selesai, anda boleh memuat naiknya ke papan Dwenguino dengan mengklik butang ini. Pastikan anda penunjuk memilih papan kanan dan port di dalam ide Arduino.",
step7Title: "Terbuka",
step7Content: "Tombol ini membolehkan anda membuka program yang telah disimpan sebelumnya.",
step8Title: "Simpan",
step8Content: "Dengan butang ini anda boleh menyimpan kod anda ke fail setempat.",
step9Title: "simulator",
step9Content: "Pada masa akan datang anda akan dapat menggunakan butang ini untuk membuka simulator. Anda boleh menggunakannya untuk menguji kod sebelum memuat naik."
};

MSG.tutorials.nameOnLcd = {
  step1Title: "Nama Atas Skrin",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: "Nama Atas Skrin",
  step2Content: "Tukar program supaya nama anda muncul pada baris pertama skrin lcd.",
};

MSG.tutorials.blinkLED = {
  step1Title: "LED Berkedip",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: "LED Berkedip",
  step2Content: "Tukar program supaya LED bertukar untuk satu saat dan kemudian mematikan LED selama satu saat. Urutan ini diulangi selama-lamanya.",
  step3Title: "Tambahan",
  step3Content: "Buat satu lagi nyalakan LED dan matikan. ",
};

MSG.tutorials.ledOnButtonPress = {
  step1Title: "LED atas semua butang tekan ",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: "LED atas semua butang tekan ",
  step2Content: "Tukar program supaya LED dihidupkan apabila anda menekan butang utara.",
  step3Title: "Tambahan",
  step3Content: "Pastikan LED dimatikan apabila anda melepaskan butang utara. Petunjuk: anda boleh menukar blok jika dengan mengklik butang gear: Tukar ke tempat yang lain blok untuk mematikan belakang LED",
};

MSG.tutorials.bitPatternOnLeds = {
  step1Title: " Cora katas LEDs",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: " Cora katas LEDs",
  step2Content: "Kod yang anda ada sangat panjang. Bolehkah anda mendapatkan hasil yang sama menggunakan kurang blok? Cuba dapatkan hasil yang sama dengan menggunakan kurang blok!",
  step3Title: " Cora katas LEDs",
  step3Content: "Apabila anda berjaya mengurangkan bilangan blok, hubungi salah seorang tutor untuk mendapatkan maklum balas mengenai penyelesaian anda.",
};


MSG.tutorials.allButtons = {
  step1Title: "Semua Butang",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: "Semua Butang",
  step2Content: "Kod ini perlu dihidupkan apabila salah satu butang ditekan. Lihatlah program ini. Adakah semua butang berfungsi? Cuba untuk membetulkan kod untuk butang yang tidak berfungsi.",
  step3Title: "Tambahan",
  step3Content: "Tukar kod supaya LED dimatikan apabila butang dibebaskan.",
};

MSG.tutorials.driveForward = {
  step1Title: "Pandu ke hadapan",
  step1Content: "Buka pandangan simulator.",
  step2Title: "Pandu ke hadapan",
  step2Content: "Klik pada senario Robot. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step3Title: "Pandu ke hadapan",
  step3Content: "Adakah kereta memandu ke hadapan? Betulkan kod supaya kereta memandu ke hadapan.",
};

MSG.tutorials.rideInSquare = {
  step1Title: "Naik ke square",
  step1Content: "Buka pandangan simulator.",
  step2Title: "Naik ke square",
  step2Content: "Klik pada senario Robot. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step3Title: "Naik ke square",
  step3Content: "Adakah menaiki kereta di lapangan? Betulkan kod itu sehingga menaiki kereta di lapangan",
  step4Title: "Tambahan",
  step4Content: "The code you have is very long. Can you get the same result using less blocks? Try to get the same result by using less blocks!",
};

MSG.tutorials.rideToWall = {
  step1Title: "Naik ke dinding",
  step1Content: "Buka pandangan simulator.",
  step2Title: "Naik ke dinding",
  step2Content: "Klik pada senario.",
  step3Title: "Naik ke dinding",
  step3Content: "Klik pada senario Memindahkan robot dengan dinding. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step4Title: "Naik ke dinding",
  step4Content: "Adakah menaiki kereta ke dinding? Adakah ia berhenti di dinding? Tukar kod supaya kereta berhenti di dekat dinding.",
};


MSG.tutorials.avoidWall = {
  step1Title: "Elak Dinding",
  step1Content: "Buka pandangan simulator.",
  step2Title: "Elak Dinding",
  step2Content: "Tukar senario .",
  step3Title: "Elak Dinding",
  step3Content: "Klik pada senario Memindahkan robot dengan dinding.",
  step4Title: "Elak Dinding",
  step4Content: "Adakah kereta mengelakkan dinding dengan memutar sebelum sampai? Tukar kod supaya kereta terus memandu tetapi tidak pernah memukul dinding.",
};


MSG.logging = {
  setup: "Test setup",
  login: "Login",
  newuser: "New user",
  username: "Username",
  chooseUsername: "Choose a username",
  choosePassword: "Select 4 personal icons as your password. You need to be able to remember these in the right order.",
  currentlySelected: "Currently selected: ",
  birth: "Date of birth",
  school: "School",
  selectSchool: "Search by name of school...",
  agegroup: "Age group:",
  primary1: "Primary grade 1",
  primary2: "Primary grade 2",
  primary3: "Primary grade 3",
  primary4: "Primary grade 4",
  primary5: "Primary grade 5",
  primary6: "Primary grade 6",
  secondary1: "Secondary grade 1",
  secondary2: "Secondary grade 2",
  secondary3: "Secondary grade 3",
  secondary4: "Secondary grade 4",
  secondary5: "Secondary grade 5",
  secondary6: "Secondary grade 6",
  gender: "Gender: ",
  gender1: "F",
  gender2: "M",
  gender3: "X",
  gender4: "I\'d rather not say",
  activity: "Activity: ",
  name: "Name ",
  date: "Date ",
  ok: "Ok",
  reset: "Reset",
  person: "Person",
  dog: "Dog",
  car: "Car",
  camera: "Camera",
  heart: "Heart",
  plane: "Plane",
  house: "House",
  umbrella: "Umbrella",
  star: "Star",
  money: "Money",
  gift: "Gift",
  keys: "Keys",
  music: "Music",
  snowflake: "Snowflake",
  fire: "Fire",
  envelope: "Envelope"
};

MSG.validator = {
  errSchool: "Select a school.",
  errId: "You didn't select enough icons.",
  errAgeGroup: "Select your age group.",
  errGender: "Select your gender.",
  errActivityId: "Your activity title cannot be empty."
};