var MSG = {
  arduinoCodeCopied: "Arduino code copied to clipboard",
  title: "DwenguinoBlockly",
  blocks: "Blok",
  linkTooltip: "Simpan dan sambungkan ke blok.",
  runTooltip: "Jalankan program yang ditentukan oleh blok di ruang kerja.",
  loadBlocksFileTooltip: "Muatkan fail blok yang disimpan sebelum ini",
  saveBlocksFileTooltip: "Simpan blok ke file lokal",
  toggleSimulator: "Togol tampilan simulator.",
  badCode: "Ralat program: \ n %1",
  timeout: "Pelaksanaan pelaksanaan maksimum melebihi.",
  trashTooltip: "Buang semua blok.",
  catLogic: "Logik",
  catLoops: "Loop",
  catMath: "Matematik",
  catText: "Teks",
  catLists: "Senarai",
  catColour: "Color",
  catArduino: "Arduino",
  catVariables: "Pemboleh ubah",
  catFunctions: "Functions",
  catDwenguino: "Dwenguino",
  catSocialRobot: "Social robot",
  catComments: "Comments",
  catBoardIO: "IO",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "Terdapat masalah dengan permintaan itu.",
  linkAlert: "Kongsi blok anda dengan pautan ini: \ n \ n %1",
  hashError: "Maaf, '%1' tidak sesuai dengan mana-mana program yang disimpan.",
  xmlError: "Tidak dapat memuat fail yang disimpan anda Mungkin ia telah dibuat dengan versi berbeza Blockly?",
  badXml: "Error parsing XML: \ n%1 \ n \ nPilih 'OK' untuk meninggalkan perubahan anda atau 'Cancel' untuk selanjutnya mengedit XML.",
  pressed: "DITERIMA",
  setup: "persediaan",
  loop: "gelung",
  dwenguino_main_program_structure: "Kod dalam blok persediaan dilaksanakan sekali pada permulaan program. Kod dalam gelung diulangi sehingga program berhenti.",
  catDwenguino: "Dwenguino",
  delay_help: "Tunggu sebilangan milisecond tertentu (1 milisecond = 1000 saat)",
  delay: "kelewatan",
  clearLCD: "Clear LCD",
  dwenguinoLCD: "Dwenguino LCD %1 %2 %3 Tulis teks: %4 Pada baris: %5 Bermula dari lajur: %6",
  pin: "pin",
  toneOnPin: "Mainkan nada",
  frequency: "dengan kekerapan",
  noToneOnPin: "Berhenti nada",
  toneOnPinTooltip: "Nada main dengan kekerapan tertentu pada pin tertentu",
  noToneOnPinTooltip: "Hentikan nada di pin",
  trig: "nombor pin trig",
  echo: "nombor pin echo",
  sonarTooltip: "Sensor ini membaca jarak dari sensor sonar",
  miliseconds: "ms",
  digitalRead: "Baca nilai digital dari",
  digitalWriteToPin: "Tulis pada",
  digitalWriteValue: "nilai digital",
  digitalWriteTooltip: "Tulis nilai tinggi atau rendah pada pin digital lembaga Dwenguino",
  digitalReadTooltip: "Baca nilai digital (1 / tinggi atau 0 / rendah) dari pin yang ditentukan",
  high: "TINGGI",
  low: "RENDAH",
  highLowTooltip: "Merupakan nilai tinggi (1) atau rendah (0) pada pin.",
  tutsIntroduction: "Pengenalan",
  tutsTheremin: "Theremin",
  tutsRobot: "Robot",
  tutsHelloDwenguino: "Hello Dwenguino!",
  tutsNameOnLcd: "Name on LCD",
  tutsBlinkLED: "Blink LED",
  tutsLedOnButtonPress: "LED on button press",
  tutsBitPatternOnLeds: "Bit pattern on leds",
  tutsAllButtons: "All buttons",
  tutsDriveForward: "Drive forward",
  tutsRideInSquare: "Ride a square",
  tutsRideToWall: "Ride to wall",
  tutsAvoidWall: "Avoid wall",
  simulator: "Simulator",
  setLedState: "Putaran %1 %2",
  setLedStateTooltip: "Hidupkan atau matikan papan pada papan Dwenguino",
  ledPinsTooltip: "Pic yang dipimpin anda mahu mengawal",
  dwenguinoOn: "ON",
  dwenguinoOff: 'OFF',
  dwenguinoOnOffTooltip: "Pilih nilai untuk menghidupkan LED ON atau OFF",
  dwenguinoLedBlock: "LED",
  dwenguinoSonarBlock: "sonar %1 %2 %3 trig pin number %4 echo pin number %5",
  dwenguinoServoBlock: "Servo motor %1 %2 %3 channel # %4 angle %5",
  dwenguinoServoDropdownBlock: "Servo motor %1",
  dwenguinoServoBlockTooltip: "Tetapkan satu servo yang disambungkan ke Dwenguino ke sudut tertentu antara 0 dan 180 darjah",
  dwenguinoServoDropdownTooltip: "Select one of the two internal servo motors",
  dwenguinoServoOne: "1",
  dwenguinoServoTwo: "2",
  dwenguinoDCMotorBlock: "DC Motor %1 %2 %3 channel %4 speed %5",
  dwenguinoDCMotorBlockTooltip: "Tetapkan kelajuan salah satu daripada dua motor dwenguino Speed = nilai antara -255 (kelajuan penuh ke belakang) dan 255 (kelajuan penuh ke depan)",
  dwenguinoAnalogWrite: "Tulis kepada %1 nilai analog %2",
  dwenguinoAnalogRead: "Baca nilai analog dari %1",
  dwenguinoAnalogWriteTooltip: "Tulis nilai analog antara 0 dan 255 ke pin yang ditentukan",
  dwenguinoAnalogReadBlock: "Baca nilai analog dari",
  dwenguinoAnalogWriteTooltip: "Baca nilai beteween 0 dan 255 dari pin yang ditentukan",
  digitalReadSwitch: "Baca suis %1",
  waitForSwitch: "wait until button %1 is pressed",
  digitalReadSwitchTooltip: "Baca nilai dari salah satu suis dwenguino",
  north: "Utara",
  east: "Timur",
  south: "Selatan",
  west: "Barat",
  center: "Pusat",
  ledsReg: "LEDS",
  dwenguinoLedsRegTooltip: "Anda boleh menghidupkan 0 hingga 7 dengan menggunakan nombor binari, contohnya 0b00001111 akan bertukar menjadi 0 hingga 3 dan sisanya",
  pressed: "DITERIMA",
  notPressed: "TIDAK BERTINGKAT",
  pressedTooltip: "Merupakan keadaan butang. Gunakan nilai ini untuk membandingkan dengan keadaan butang sebenar",
  create: "Create",
  with_type: "with type",
  create_global: "Create global",
  socialRobotRgbLedBlock: "RGB LED",
  socialRobotPinRed: "pin red",
  socialRobotPinGreen: "pin green",
  socialRobotPinBlue: "pin blue",
  socialRobotRgbLedOffBlock: "Turn the RGB LED off with",
  socialRobotRgbColorBlock: "RGB color %1",
  socialRobotRgbColor: "red %1 green %2 blue %3",
  socialRobotLedmatrixImageBlock: "Display pattern on LED matrix segment",
  socialRobotLedmatrixImageBlockTooltip: "Show the given led pattern on the LED matrix display.",
  socialRobotLedmatrixEyePatternBlock: "Display eye pattern",
  socialRobotLedmatrixEyePatternBlockTooltip: 'Show the given eye pattern on the LED matrix display.',
  socialRobotLedmatrixEyePatternSegmentBlock: "on LED matrix segment",
  socialRobotLedmatrixClearSegmentBlock: "Clear LED matrix segment",
  socialRobotLedmatrixClearSegmentBlockTooltip: 'Clear a segment of the LED matrix display.',
  socialRobotLedmatrixClearDisplayBlock: "Clear LED matrix",
  socialRobotLedmatrixClearDisplayBlockTooltip: 'Clear the complete LED matrix display.',
  socialRobotPirBlock: "Pir %1 %2 %3 trig pin number %4",
  socialRobotSoundSensorBlock: "Sound sensor %1 %2 %3 pin %4",
  socialRobotSoundSensorBlockTooltip: "",
  socialRobotTouchSensorBlock: "Touch sensor %1 %2 %3 pin %4",
  socialRobotTouchSensorBlockTooltip: "",
  socialRobotButtonBlock: "Button %1 %2 %3 pin %4",
  socialRobotButtonBlockTooltip: "",
  socialrobotSetPinState: "Set %1 %2",
  socialrobotServoBlock: "Servo motor %1 %2 %3 pin %4 angle %5",
  socialrobotWaveArmesBlock: "Wave arms %1 %2 Servo right arm %3 %4 Servo left arm %5 %6",
  socialRobotArmsDownBlock: "Put arms down %1 %2 %3 Servo right arm %4 %5 Servo left arm %6 %7",
  socialRobotArmsUpBlock: "Put arms up %1 %2 %3 Servo right arm %4 %5 Servo left arm %6 %7",
  socialRobotEyesLeftBlock: "Turn eyes left %1 %2 %3 Servo left eye %4 %5 Servo right eye %6 %7",
  socialRobotEyesRightBlock: "Turn eyes right %1 %2 %3 Servo left eye %4 %5 Servo right eye %6 %7",
  socialrobotReadPinBlock: "Read value of pin %1 %2",
  socialRobotServoRightHand: "Servo right hand",
  socialRobotServoLeftHand: "Servo left hand",
  sonarSliderLabel: "Sonar distance",
  pirButtonLabel: "PIR button",
  soundButtonLabel: "Sound button",
  touchButtonLabel: "Touch button",
  lightSensorSliderLabel: "Light sensor button",
  servoCostume: "Costume",
  servoOptions: "Servo motor options",
  sonarOptions: "Sonar sensor options",
  lcdOptions: "LCD screen options",
  pirOptions: "PIR sensor options",
  soundOptions: "Sound sensor options",
  touchOptions: "Touch sensor options",
  buttonOptions: "Button options",
  lightOptions: "Light sensor options",
  rgbLedOptions: "RGB LED options",
  ledmatrixOptions: 'Led  Matrix Options',
  ledOptions: "LED options",
  pinOptions: "Pin",
  colorOptions: "Color",
  runError: "Oops there was an error when trying to run your code on the board.",
  runError: "<h3>Sorry, I was unable to upload the code to the board</h3>",
  uploadError: "Follow these steps to restart the Dwenguino board: \n    1. Disconnect the USB cable \n    2. Connect the computer and Dwenguino board with the USB cable \n    3. Simultaneously press the RESET and the SOUTH button of the Dwenguino board \n    4. Then first release the RESET button \n    5. Then release the SOUTH button \n    6. Upload the program again via the <span id='db_menu_item_run' class='fas fa-play-circle' alt='Upload code to Dwenguino board'></span> button in the main menu",
  compileError: "The code could not be compiled.\nYou should check your code, did you forget a block someware?",

//TODO: translate
  dwenguinoStepperMotorBlock: "stepper-motor %1 %2 %3 nummer %4 aantal stappen %5",
  dwenguinoStepperMotorBlockTooltip: "TODO",
  drawingrobotMove:"Verplaats de stift onder een van hoek %1 graden met %2 stappen",
  drawingrobotMoveXY:"Verplaats de stift %1 naar rechts en %2 naar links",
  drawingrobotLine:"Teken een lijn naar x: %1 y: %2",
  drawingrobotCircle:"Teken een cirkel met straal: %1",
  drawingrobotRectangle:"Teken een rechthoek met breedte: %1 en hoogte: %2",
  drawingrobotLiftStylus: "Stift opheffen",
  drawingrobotLowerStylus: "Stift neerzetten",
  drawingrobotChangeColor: "Kleur %1",
  up:"omhoog",
  down:"omlaag",
  left:"links",
  right:"rechts",
  bounds:"Opgelet\nJe probeert buiten het papier te tekenen",
  drawingrobotgrid: "raster",
  colorpicker:"Kleur",
  drawingrobotSaveImage:"Tekening opslaan",
  drawingrobotDrawing:"Tekening",
};

MSG.cookieConsent = {
  close: "Close",
  cookieConsent: "We use functional cookies to set up the Dwenguino simulator. ",
  cookieInfo: "More info on how we use cookies.",
  whatAreCookiesTitle: "Wat zijn cookies?",
  whatAreCookiesDescription1: "Cookies zijn kleine tekstbestanden die lokaal worden opgeslagen op uw computer. Deze cookies dienen voor tal van doeleinden: het onthouden van instellingen (login, taalkeuzes), het vergaren van informatie en het bijhouden van het bezoekgedrag van de gebruikers.",
  whatAreCookiesDescription2: "De cookies die wij gebruiken zijn veilig: zij hebben geen toegang tot persoonlijke informatie op uw computer en kunnen deze niet beschadigen of besmetten met virussen. De cookies geven op geen enkele manier persoonlijke informatie aan ons door. De informatie die we via cookies verzamelen helpt ons om je van specifieke diensten te laten genieten.",
  whatAreNecessaryCookiesTitle: "Wat zijn noodzakelijke cookies?",
  whatAreNecessaryCookiesDescription: "Noodzakelijke cookies zijn cookies die je nodig hebt om te surfen op de website en gebruik te maken van de functionaliteit die we aanbieden. Bovendien zijn de cookies noodzakelijk om de beveiligde onderdelen van de website te kunnen zien.",
  whichCookiesTitle: "Welke cookies gebruikt deze website?",
  dwengoCookieTitle: "Aanmelden als gebruiker (Dwengo cookie)",
  dwengoCookieDescription: "Bij het aanmelden op de website wordt een tijdelijke cookie gebruikt waardoor je herkend wordt als gebruiker. Met behulp van deze cookie wordt onder andere je taalinstelling en vooruitgang bewaard. De cookie zorgt er voor dat je toegang hebt tot de beveiligde delen van de website. Deze cookie is slechts geldig tot aan het einde van de sessie en is enkel beschikbaar voor en gemaakt door Dwengo vzw.",
  jenkinsCookieTitle: "Jenkins configuratie (Jenkins cookie)",
  jenkinsCookieDescription: "De Jenkins cookie is voor ons noodzakelijk om de Dwenguino simulator online op een server te kunnen installeren. Jenkins is software waarvan we gebruik maken om onze simulator te updaten. Die cookie bevat informatie over de instellingen van Jenkins en bevat dus ook geen enkele informatie over jou als gebruiker.",
};

MSG.dropzone = {
  dictSelectFile: "Select a file.",
  dictChooseFile: "Choose file",
  dictDefaultMessage: "Drop files here to upload",
  dictFallbackMessage: "Your browser does not support drag'n'drop file uploads.",
  dictFileTooBig: "File is too big ({{filesize}}MiB). Max filesize: {{maxFilesize}}MiB.",
  dictFallbackText: "Please use the fallback form below to upload your files like in the olden days.",
  dictInvalidFileType: "You can't upload files of this type.",
  dictResponseError: "Server responded with {{statusCode}} code.",
  dictCancelUpload: "Cancel upload",
  dictCancelUploadConfirmation: "Are you sure you want to cancel this upload?",
  dictRemoveFile: "Remove file",
  dictMaxFilesExceeded: "You can not upload any more files.",
  dictUploadBlocks: "Upload blocks",
  dictFileNotSupported: "This file is not supported.",
};

MSG.ledmatrix = {
  restPosition: 'Rest position', 
  blink1: 'Blink 1',
  blink2: 'Blink 2',
  blink3: 'Blink 3',
  blink4: 'Blink 4',
  blink5: 'Blink 5',
  right1: 'Right 1',
  right2: 'Right 2',
  left1: 'Left 1',
  left2: 'Left 2',
  up1: 'Up 1',
  up2: 'Up 2',
  up3: 'Up 3',
  down1: 'Down 1',
  down2: 'Down 2',
  down3: 'Down 3',
  angryLeft1: 'Angry left 1',
  angryLeft2: 'Angry left 2',
  angryLeft3: 'Angry left 3',
  angryLeft4: 'Angry left 4',
  angryRight1: 'Angry right 1',
  angryRight2: 'Angry right 2',
  angryRight3: 'Angry right 3',
  angryRight4: 'Angry right 4',
  sadLeft1: 'Sad left 1',
  sadLeft2: 'Sad left 2',
  sadLeft3: 'Sad left 3',
  sadRight1: 'Sad right 1',
  sadRight2: 'Sad right 2',
  sadRight3: 'Sad right 3',
  evilLeft1: 'Evil left 1',
  evilLeft2: 'Evil left 2',
  evilRight1: 'Evil right 1',
  evilRight2: 'Evil right 2',
  scanHorizontal1: 'Scan horizontal 1',
  scanHorizontal2: 'Scan horizontal 2',
  scanHorizontal3: 'Scan horizontal 3',
  scanHorizontal4: 'Scan horizontal 4',
  scanVertical1: 'Scan vertical 1',
  scanVertical2: 'Scan vertical 2',
  scanVertical3: 'Scan vertical 3',
  scanVertical4: 'Scan vertical 4',
  scanVertical5: 'Scan vertical 5',
  scanVertical6: 'Scan vertical 6',
  rip1: 'RIP 1',
  rip2: 'RIP 2',
  peering1: 'Peering 1',
  peering2: 'Peering 2',
  peering3: 'Peering 3',
  peering4: 'Peering 4'
};

MSG.simulator = {
start: "Mula",
stop: "Berhenti",
pause: "Jeda",
step: "1 Langkah",
speed: "Kelajuan",
speedVerySlow: "40 kali perlahan",
speedSlow: "20 kali perlahan",
speedMedium: "10 kali perlahan",
speedFast: "5 kali perlahan",
speedVeryFast: "2 kali perlahan",
speedRealTime: "Real-time",
components: "Pilih komponen",
servo: "Servo",
servoDescription: "",
motor: "Motor",
DCMotorDescription: "",
scope: "Pemboleh ubah",
alertDebug: "Hentikan penyelakuan sebelum menyambung semula ke program",
distance: "jarak",
scenario: "Senario",
senario_default: "Papan biasa",
scenario_moving: "Bergerak robot",
scenario_wall: "Memindahkan robot dengan dinding",
code: "Kod",
pir: "PIR sensor",
pirDescription: "A passif infrared (PIR) sensor allows you to <b>sense motion</b>, because it detects changes of infrared radiation in its environment",
sonar: "Sonar",
sonarDescription: "",
led: "LED",
ledDescription: "A light-emitting diode (LED) is a semiconductor device that <b>emits light</b> when an electric current passes through it. Different semiconductor materials produce <b>different colors of light</b>. ",
rgbled: "RGB LED",
rgbledDescription: "",
ledmatrix: "LED matrix",
ledmatrixDescription: "",
ledmatrixsegment: "LED matrix",
ledmatrixsegmentDescription: "",
touch: "Touch sensor",
touchDescription: "",
lcd: "LCD screen",
lcdDescription: "The LCD display on the Dwengo board is a 16x2 character display with backlight.",
button: "Button",
buttonDescription: "",
sound: "Sound sensor",
soundDescription: "",
light: "Light sensor",
lightDescription: "",
buzzer: "Buzzer",
buzzerDescription: "The buzzer on the Dwengo board can be used to <b>play a series of tones</b> or short sound fragments. The height of each tone is controlled by defining the <b>frequency</b> of the buzzer. Use a delay block to change the length of a tone.",
decoration: "Decoration"
};

MSG.socialrobot = {
  plain: "Default",
  eye: "Eye",
  mouth: "Mouth",
  righthand: "Right hand",
  lefthand: "Left hand",
};

MSG.tutorialMenu = {
  header: "Tutorials",
  catDwenguino: "Learn to program<br>with DwenguinoBlockly",
  catDwenguinoComponents: "Handy overview of<br>the Dwenguino components",
  catDwenguinoConnector: "Pin mapping &<br>expansion connector",  catRidingRobot: "Riding robot",
  catSocialRobot: "Social robot",
  catWeGoStem: "WeGoSTEM",
  chooseCategory: "Select a tutorial category",
  chooseTutorial: "Select a tutorial",
  previous: "Previous",
  close: "Close",
  checkAnswer: "Check answer",
  correctAnswer: "The answer was correct!",
  wrongAnswer: "The answer was not correct. Try again!",
  dwenguinoComponents: "Dwenguino components",
  sensors: "Sensors",
  actuators: "Actuators",
  movement: "Movement",
  audio: "Audio",
  display: "Display"
};

MSG.tutorials = {
introduction: {},
};

MSG.tutorials.general = {
  sureTitle: "Are you sure?",
  sureText: "When you click 'Next' all blocks in the workspace will be removed.",
};

MSG.tutorials.introduction = {
step1Title: "Welkom to DwenguinoBlockly",
step1Content: "Hai, nama saya Dwenguino! Saya akan membantu anda untuk mengenali antara muka!",
step2aTitle: "Kawasan kod Block",
step2aContent: "Di kawasan ini, anda meletakkan blok kod anda. Anda harus meletakkan blok anda di dalam blok gelung setup jika anda mahu mereka dilaksanakan.",
step2bTitle: "Kotak peralatan Blockly",
step2bContent: "Ini adalah kotak peralatan, ia mengandungi semua blok yang boleh anda gunakan untuk mencipta program anda. Anda boleh meneroka cathegories yang berbeza untuk mengetahui apa yang boleh dilakukan oleh Dwenguino anda.",
step3Title: "Pemilihan bahasa",
step3Content: "Gunakan ini untuk menukar bahasa",
step4Title: "Difficulty",
step4Content: "Slider ini membolehkan anda menetapkan tahap yang sukar. Buat masa ini kami hanya menyediakan peringkat pemula dan maju.",
step5Title: "Dwengobooks",
step5Content: "Dwengobooks adalah tutorial interaktif yang membimbing anda melalui cabaran pengkomputeran fizikal yang berbeza.",
step6Title: "Kod muat naik",
step6Content: "Apabila kod anda selesai, anda boleh memuat naiknya ke papan Dwenguino dengan mengklik butang ini. Pastikan anda penunjuk memilih papan kanan dan port di dalam ide Arduino.",
step7Title: "Terbuka",
step7Content: "Tombol ini membolehkan anda membuka program yang telah disimpan sebelumnya.",
step8Title: "Simpan",
step8Content: "Dengan butang ini anda boleh menyimpan kod anda ke fail setempat.",
step9Title: "simulator",
step9Content: "Pada masa akan datang anda akan dapat menggunakan butang ini untuk membuka simulator. Anda boleh menggunakannya untuk menguji kod sebelum memuat naik."
};

MSG.tutorials.nameOnLcd = {
  step1Title: "Nama Atas Skrin",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: "Nama Atas Skrin",
  step2Content: "Tukar program supaya nama anda muncul pada baris pertama skrin lcd.",
};

MSG.tutorials.blinkLED = {
  step1Title: "LED Berkedip",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: "LED Berkedip",
  step2Content: "Tukar program supaya LED bertukar untuk satu saat dan kemudian mematikan LED selama satu saat. Urutan ini diulangi selama-lamanya.",
  step3Title: "Tambahan",
  step3Content: "Buat satu lagi nyalakan LED dan matikan. ",
};

MSG.tutorials.ledOnButtonPress = {
  step1Title: "LED atas semua butang tekan ",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: "LED atas semua butang tekan ",
  step2Content: "Tukar program supaya LED dihidupkan apabila anda menekan butang utara.",
  step3Title: "Tambahan",
  step3Content: "Pastikan LED dimatikan apabila anda melepaskan butang utara. Petunjuk: anda boleh menukar blok jika dengan mengklik butang gear: Tukar ke tempat yang lain blok untuk mematikan belakang LED",
};

MSG.tutorials.bitPatternOnLeds = {
  step1Title: " Cora katas LEDs",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: " Cora katas LEDs",
  step2Content: "Kod yang anda ada sangat panjang. Bolehkah anda mendapatkan hasil yang sama menggunakan kurang blok? Cuba dapatkan hasil yang sama dengan menggunakan kurang blok!",
  step3Title: " Cora katas LEDs",
  step3Content: "Apabila anda berjaya mengurangkan bilangan blok, hubungi salah seorang tutor untuk mendapatkan maklum balas mengenai penyelesaian anda.",
};


MSG.tutorials.allButtons = {
  step1Title: "Semua Butang",
  step1Content: "Buka pandangan simulator. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step2Title: "Semua Butang",
  step2Content: "Kod ini perlu dihidupkan apabila salah satu butang ditekan. Lihatlah program ini. Adakah semua butang berfungsi? Cuba untuk membetulkan kod untuk butang yang tidak berfungsi.",
  step3Title: "Tambahan",
  step3Content: "Tukar kod supaya LED dimatikan apabila butang dibebaskan.",
};

MSG.tutorials.driveForward = {
  step1Title: "Pandu ke hadapan",
  step1Content: "Buka pandangan simulator.",
  step2Title: "Pandu ke hadapan",
  step2Content: "Klik pada senario Robot. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step3Title: "Pandu ke hadapan",
  step3Content: "Adakah kereta memandu ke hadapan? Betulkan kod supaya kereta memandu ke hadapan.",
};

MSG.tutorials.rideInSquare = {
  step1Title: "Naik ke square",
  step1Content: "Buka pandangan simulator.",
  step2Title: "Naik ke square",
  step2Content: "Klik pada senario Robot. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step3Title: "Naik ke square",
  step3Content: "Adakah menaiki kereta di lapangan? Betulkan kod itu sehingga menaiki kereta di lapangan",
  step4Title: "Tambahan",
  step4Content: "The code you have is very long. Can you get the same result using less blocks? Try to get the same result by using less blocks!",
};

MSG.tutorials.rideToWall = {
  step1Title: "Naik ke dinding",
  step1Content: "Buka pandangan simulator.",
  step2Title: "Naik ke dinding",
  step2Content: "Klik pada senario.",
  step3Title: "Naik ke dinding",
  step3Content: "Klik pada senario Memindahkan robot dengan dinding. Jalankan program dengan mengklik Start di dalam simulator. Lihat apa yang berlaku.",
  step4Title: "Naik ke dinding",
  step4Content: "Adakah menaiki kereta ke dinding? Adakah ia berhenti di dinding? Tukar kod supaya kereta berhenti di dekat dinding.",
};


MSG.tutorials.avoidWall = {
  step1Title: "Elak Dinding",
  step1Content: "Buka pandangan simulator.",
  step2Title: "Elak Dinding",
  step2Content: "Tukar senario .",
  step3Title: "Elak Dinding",
  step3Content: "Klik pada senario Memindahkan robot dengan dinding.",
  step4Title: "Elak Dinding",
  step4Content: "Adakah kereta mengelakkan dinding dengan memutar sebelum sampai? Tukar kod supaya kereta terus memandu tetapi tidak pernah memukul dinding.",
};


MSG.logging = {
  setup: "Test setup",
  login: "Login",
  logout: "Log out",
  firstname: "First name",
  newuser: "New user",
  username: "Username",
  chooseUsername: "Choose a username",
  email: "Email address",
  enterEmail: "Enter email address",
  forgotPassword: "I forgot my password",
  secretCode: "Secret code",
  enterSecretCode: "Enter your secret code sent to you by email",
  userDoesNotExist: "This user does not exist. Try a different email address.",
  resetPassword: "Reset your password",
  back: "Back",
  enterFirstname: "Enter your first name",
  password: "Password",
  repeatedPassword: "Repeat password",
  enterPassword: "Enter password",
  enterRepeatedPassword: "Repeat your password",
  choosePassword: "Select 4 personal icons as your password. You need to be able to remember these in the right order.",
  currentlySelected: "Currently selected: ",
  role: "Role",
  verification: "Verify your email address",
  verificationSentTo: "A verification message has been sent to your email address. Click the link in the email to verify your account.",
  birth: "Date of birth",
  school: "School",
  selectSchool: "Search by name of school...",
  agegroup: "Age group:",
  primary1: "Primary grade 1",
  primary2: "Primary grade 2",
  primary3: "Primary grade 3",
  primary4: "Primary grade 4",
  primary5: "Primary grade 5",
  primary6: "Primary grade 6",
  secondary1: "Secondary grade 1",
  secondary2: "Secondary grade 2",
  secondary3: "Secondary grade 3",
  secondary4: "Secondary grade 4",
  secondary5: "Secondary grade 5",
  secondary6: "Secondary grade 6",
  gender: "Gender: ",
  gender1: "F",
  gender2: "M",
  gender3: "X",
  gender4: "I\'d rather not say",
  activity: "Activity: ",
  name: "Name ",
  date: "Date ",
  ok: "Ok",
  reset: "Reset",
  person: "Person",
  dog: "Dog",
  car: "Car",
  camera: "Camera",
  heart: "Heart",
  plane: "Plane",
  house: "House",
  umbrella: "Umbrella",
  star: "Star",
  money: "Money",
  gift: "Gift",
  keys: "Keys",
  music: "Music",
  snowflake: "Snowflake",
  fire: "Fire",
  envelope: "Envelope"
};

MSG.validator = {
  errSchool: "Select a school.",
  errId: "You didn't select enough icons.",
  errAgeGroup: "Select your age group.",
  errGender: "Select your gender.",
  errActivityId: "Your activity title cannot be empty."
};