var MSG = {
  arduinoCodeCopied: "Arduino code copied to clipboard",
  title: "Kod",
  blocks: "Bloki",
  linkTooltip: "Zapisz i podlinkuj do bloków",
  runTooltip: "Uruchom program zdefinowany przez bloki w obszarze roboczym",
  loadBlocksFileTooltip: "Wczytaj zapisany wcześniej plik blocków.",
  saveBlocksFileTooltip: "Zapisz bloki do lokalnego pliku.",
  toggleSimulator: "Otwórz lub zamknij okno symulatora.",
  badCode: "Błąd programu:\n%1",
  timeout: "Maksymalna liczba iteracji wykonywań przekroczona",
  trashTooltip: "Odrzuć wszystkie bloki.",
  catLogic: "Logika",
  catLoops: "Pętle",
  catMath: "Matematyka",
  catText: "Tekst",
  catLists: "Listy",
  catColour: "Kolor",
  catArduino: "Arduino",
  catVariables: "Zmienne",
  catFunctions: "Funkcje",
  catDwenguino: "Dwenguino",
  catSocialRobot: "Robot socjalny",
  catComments: "Komentarz",
  catBoardIO: "IO",
  createVar: "Utwórz nową zmienną",
  listVariable: "lista",
  textVariable: "tekst",
  httpRequestError: "Wystąpił problem z żądaniem.",
  linkAlert: "Udpostępnij swoje bloki korzystając z poniższego linku : \n\n\n%1",
  hashError: "Przepraszamy, \"%1\" nie odpowiada żadnemu zapisanemu programowi.",
  xmlError: "Nie można załadować zapisanego pliku. Być może został utworzony za pomocą innej wersji Blockly?",
  badXml: "Błąd parsowania XML : \n%1\n\nZaznacz \"OK\" aby odrzucić twoje zmiany lub \"Cancel\", żeby w przyszłości edytować XML.",
  pressed: WCIŚNIĘTY,
  setup: "konfiguracja",
  loop: "powtórz",
  dwenguino_main_program_structure: "Pierwszy fragment kodu jest wykonywany tylko jeden raz przy starcie programu. Kod w powtórzenie będzie powtarzany w kółko aż do zatrzymania programu (np. po odłączeniu wtyczki).",
  catDwenguino: "Dwenguino",
  delay_help: "Odczekaj określoną liczbę milisekund. (1 sekunda = 1000 milisekund)",
  delay: "odczekaj",
  clearLCD: "opróżnij ekran LCD",
  dwenguinoLCD: "Dwenguino LCD %1 %2 %3 Napisz tekst: %4 Na wierszu: %5 z kolumny: %6",
  pin: "Kołek",
  toneOnPin: "Odtwarzaj dźwięk na",
  frequency: "o częstotliwości",
  noToneOnPin: "zatrzymaj dźwięk na",
  toneOnPinTooltip: "Odtwarzaj dźwięk o określonej częstotliwości na kołku.",
  noToneOnPinTooltip: "Zatrzymaj dźwięk na określonym kołku.",
  trig: "trig numer kołka",
  echo: "echo numer kołka",
  sonarTooltip: "Ten blok odczytuje odległość z czujnika sonaru",
  pirTooltip: "This sensor can detect motion",
  miliseconds: "ms",
  digitalRead: "czytaj wartość cyfrową",
  digitalWriteToPin: "zapisz",
  digitalWriteValue: "wartość cyfrowa",
  digitalWriteTooltip: "Zapisz stan wysoki lub niski na pinie Dwenguino",
  digitalReadTooltip: "odczytaj wartości cyfrowej (1/wysoka lub 0/niska) z określonego kołka",
  high: "WYSOKI",
  low: "NISKI",
  highLowTooltip: "Odpowiada wysokiej (1) lub niskiej (0) wartości na kołku.",
  tutsIntroduction: "Wprowadzenie",
  tutsTheremin: "Theremin",
  tutsRobot: "Robot",
  tutsBasicTest: "Test podstawowy",
  tutsHelloDwenguino: "Cześć Dwenguino!",
  tutsNameOnLcd: "Nazwa na ekranie LCD",
  tutsBlinkLED: "Migacz",
  tutsHelloRobot: "Robot ruchomy",
  tutsLedOnButtonPress: "LED po naciśnięciu przycisku",
  tutsBitPatternOnLeds: "Wzór bitowy na ledach",
  tutsAllButtons: "Wszystkie przyciski",
  tutsDriveForward: "Jedź do przodu",
  tutsRideInSquare: "Jedź po kwadracie",
  tutsRideToWall: "Jedź do ściany",
  tutsAvoidWall: "Unikaj ściany",
  tutsNameOnLcdBasic: "Twoje imię na ekranie LCD",
  tutsNameOnLcdWeGoSTEM: "Imię na ekranie LCD",
  tutsIntroduceYourselfWeGoSTEM: "Przedstaw się",
  tutsShowNameAndDisappearWeGoSTEM: "Spraw aby imię zniknęło",
  tutsLampOnOffWeGoSTEM: "Migacz",
  tutsPoem1: "Wiersz 1",
  tutsPoem2: "Wiersz 2",
  simulator: "Symulator",
  setLedState: "rób %1 %2",
  setLedStateTooltip: "Włącz lub wyłącz LEdwenguinoDCMotorBlock na płytce arduino",
  ledPinsTooltip: "Wybierz LED, którą chcesz włączyć lub wyłączyć",
  dwenguinoOn: "WŁĄCZONE",
  dwenguinoOff: "WYŁĄCZONE",
  dwenguinoOnOffTooltip: "Wybierz WŁĄCZONE lub WYŁĄCZONE",
  dwenguinoLedBlock: "LED",
  dwenguinoSonarBlock: "sonar %1 %2 %3 trig numer kołka %4 echo numer kołka %5",
  dwenguinoServoBlock: "Silnik serwo %1 %2 %3 kołek %4 kąt %5",
  dwenguinoServoDropdownBlock: "Silnik serwo %1",
  dwenguinoServoBlockTooltip: "Ustaw serwo 1 lub 2 na wybrany przez siebie kąt w zakresie od 0 do 180 stopni",
  dwenguinoServoDropdownTooltip: "Wybierz jeden z dwóch wewnętrznych silników serwo",
  dwenguinoServoOne: "1",
  dwenguinoServoTwo: "2",
  dwenguinoDCMotorBlock: "silnik prądu stałego %1 %2 %3 numer %4 prędkość %5",
  dwenguinoDCMotorBlockTooltip: "Ustaw prędkość jednego z dwóch silników podłączonych do Dwenguino. Prędkość jest wartość pomiędzy -255 (pełna prędkość wsteczna) i 255 (pełna prędkość do przodu)",
  dwenguinoAnalogWrite: "zapisz do %1 wartość analogową %2",
  dwenguinoAnalogWriteTooltip: "Zapisz wartość analogową pomiędzy 0 i 255 do określonego kołka",
  dwenguinoAnalogRead: "odczytaj wartość analogową z %1",
  dwenguinoAnalogWriteTooltip: "Odczytaj wartość analogową pomiędzy 0 i 255 z określonego kołka",
  digitalReadSwitch: "odczytaj wartość przycisku %1",
  digitalReadSwitchTooltip: "odczytaj wartość jednego z przycisków dwenguino",
  waitForSwitch: "czekaj aż zostanie naciśnięty przycisk %1",
  north: "PÓŁNOC",
  east:"WSCHÓD",
  south:"POŁUDNIE",
  west: "ZACHÓD",
  center: "CENTER",
  ledsReg: "LED",
  dwenguinoLedsRegTooltip: "Ten blok umożliwia włączanie i wyłączanie ledów od 0 do 7 za pomocą jednej liczby binarnej. Na przykład: 0b00001111 włączy ledy od 0 do 3, a resztę wyłączy",
  pressed: "WCIŚNIĘTY",
  notPressed: "NIE WCIŚNIĘTY",
  pressedTooltip: "Ustawia wartość przycisku. Porównaj tę wartość z wartością, którą odczytasz z danego przycisku.",
  sureYouWantToChangeTutorial: "Czy na pewno chcesz rozpocząć tę książkę?\n Bloki w bieżącym arkuszu zostaną zastąpione!",
  create: "Twórz",
  with_type: "z typem",
  create_global: "Twórz globalny",
  socialRobotRgbLedBlock: "RGB LED",
  socialRobotPinRed: "kołek czerwony",
  socialRobotPinGreen: "kołek zielony",
  socialRobotPinBlue: "kołek niebieski",
  socialRobotRgbLedOffBlock: "Wyłącz LED RGB za pomocą",
  socialRobotRgbColorBlock: "RGB kolor %1",
  socialRobotRgbColor: "czerwony %1 zielony %2 niebieski %3",
  socialRobotLedmatrixImageBlock: "Pokaż wzór na segmencie matrycy led",
  socialRobotLedmatrixImageBlockTooltip: "Pokaż wybrany wzór na wybranym segmencie matrycy led",
  socialRobotLedmatrixEyePatternBlock: "Pokaż wzór oka",
  socialRobotLedmatrixEyePatternBlockTooltip: "Pokaż wybrany wzór oka na wybranym segmencie matrycy led",
  socialRobotLedmatrixEyePatternSegmentBlock: "na segmencie matrycy led",
  socialRobotLedmatrixClearSegmentBlock: "Opróżnij segment matrycy led",
  socialRobotLedmatrixClearSegmentBlockTooltip: "Opróżnij wybrany segment matrycy led.",
  socialRobotLedmatrixClearDisplayBlock: "Opróżnij matrycę led",
  socialRobotLedmatrixClearDisplayBlockTooltip: "Opróżnij całą matrycę ledową.",
  next:"Następny",
  previous:"Poprzedni",
  socialRobotPirBlock: "czujnik zbliżeniowy %1 %2 %3 trig numer kołka %4",
  socialRobotSoundSensorBlock: "czujnik dźwięku %1 %2 %3 kołek %4",
  socialRobotSoundSensorBlockTooltip: "",
  socialRobotTouchSensorBlock: "czujnik dotykowy %1 %2 %3 kołek %4",
  socialRobotTouchSensorBlockTooltip: "",
  socialRobotButtonSensorBlock: "Przycisk %1 %2 %3 kołek %4",
  socialRobotButtonSensorBlockTooltip: "",
  socialrobotSetPinState: "rób %1 %2",
  socialrobotServoBlock: "silnik serwo %1 %2 %3 kołek %4 kąt %5",
  socialrobotWaveArmesBlock: "machaj do biednych %1 %2 serwo kołek prawego ramienia %3 %4 serwo kołek lewego ramienia %5 %6",
  socialRobotArmsDownBlock: "opuścić ramiona %1 %2 %3 serwo kołek prawego ramienia %4 %5 serwo kołek lewego ramienia %6 %7",
  socialRobotArmsUpBlock: "unieść ramiona %1 %2 %3 serwo kołek prawego ramienia %4 %5 serwo kołek lewego ramienia %6 %7",
  socialRobotEyesLeftBlock: "odwróć oczy w lewo %1 %2 %3 Serwo kołek lewego oka %4 %5 Serwo kołek prawego oka %6 %7",
  socialRobotEyesRightBlock: "odwróć oczy w prawo %1 %2 %3 serwo kołek lewego oka %4 %5 serwo kołek prawego oka %6 %7",
  socialrobotReadPinBlock: "odczytaj wartość kołka %1 %2",
  socialRobotServoRightHand: "serwo kołek prawego ramienia",
  socialRobotServoLeftHand: "serwo kołek lewego ramienia",
  sonarSliderLabel: "Odległość sonaru",
  pirButtonLabel: "Przycisk czujnika zbliżeniowego",
  soundButtonLabel: "Przycisk czujnika dźwięku",
  touchButtonLabel: "Przycisk czujnika dotyku",
  lightSensorSliderLabel: "Przycisk czujnika światła",
  servoCostume: "Wygląd",
  servoOptions: "Opcje silniku serwo",
  sonarOptions: "Opcje czujnika sonaru",
  lcdOptions: "Opcje ekranu LCD",
  pirOptions: "Opcje czujnika zbliżeniowego",
  soundOptions: "Opcje czujnika dźwięku",
  touchOptions: "Opcje czujnika dotyku",
  buttonOptions: "Opcje przycisków",
  lightOptions: "Opcje czujnika światła",
  rgbLedOptions: "Opcje RGB LED",
  ledOptions: "Opcje leda",
  pinOptions: "Kołek",
  colorOptions: "Kolor",
  runError: "<h3>Przepraszamy, nie udało nam się wgrać kodu na płytę</h3>",
  uploadError: "Wykonaj poniższe kroki aby zrestartować płytkę Dwenguino: \n    1. Odłącz kabel USB.\n  2. Połączyć komputer i płytkę Dwenguino za pomocą kabla USB.\n   3. Wcisnąć jednocześnie przycisk RESET i przycisk południe na płytce Dwenguino.\n   4. Następnie najpierw zwolnić przycisk RESET\n  5. Potem zwolnij przycisk południe\n  6. Wgraj program ponownie używając przycisku <span id='db_menu_item_run' class='fas fa-play-circle' alt='Wgraj kod na płytkę Dwenguino'></span> w menu głównym", 
  cleanError: "Kod z poprzedniego programu nie mógł zostać usunięty.\nSprawdź czy jakiś inny program używa pliku .cpp i zamknij ten program.",
  cleanError: "The previous code could not be removed.\nPlease check if another application is using any .cpp files.\n Close the application.",
  compileError: "Nie udało się skompilować kodu.\nSprawdź czy jest jakiś błąd w twoim programie, czy brakuje gdzieś jakiegoś bloku?",
  clear: "Usuwać",
  save: "Zapisać",
  dwenguinoStepperMotorBlock: "silnik krokowy %1 %2 %3 numer %4 liczba kroków %5",
  dwenguinoStepperMotorBlockTooltip: "TODO",
  drawingrobotMove: "przesuń rysik pod kątem %1 stopni o %2 kroki",
  drawingrobotMoveXY: "przesuń rysik %1 w prawo i %2 w lewo",
  drawingrobotLine: "narysuj linię do x: %1 y: %2",
  drawingrobotCircle: "narysuj okrąg o promieniu: %1",
  drawingrobotRectangle:"Narysuj prostokąt o szerokości: %1 i wysokości: %2",
  drawingrobotLiftStylus: "podnieś rysik",
  drawingrobotLowerStylus: "upuść rysik",
  drawingrobotChangeColor: "Kolor %1",
  up:"w górę",
  down:"w dół",
  left:"w lewo",
  right:"w prawo",
  bounds:"Uwaga\nPróbujesz rysować poza papierem",
  drawingrobotgrid: "kratka",
  colorpicker: "Kolor",
  drawingrobotSaveImage: "Zapisz rysunek",
  drawingrobotDrawing: "Rysunek",
  stepperMotorOne: "SILNIK KROKOWY 1", 
  stepperMotorTwo: "SILNIK KROKOWY 2",
  stepperMotorTooltip: "Wybierz, który z dwóch silników rysującego robota chcesz kontrolować."
};

MSG.cookieConsent = {
  close: "Close",
  cookieConsent: "We use functional cookies to set up the Dwenguino simulator. ",
  cookieInfo: "More info on how we use cookies.",
  whatAreCookiesTitle: "Wat zijn cookies?",
  whatAreCookiesDescription1: "Cookies zijn kleine tekstbestanden die lokaal worden opgeslagen op uw computer. Deze cookies dienen voor tal van doeleinden: het onthouden van instellingen (login, taalkeuzes), het vergaren van informatie en het bijhouden van het bezoekgedrag van de gebruikers.",
  whatAreCookiesDescription2: "De cookies die wij gebruiken zijn veilig: zij hebben geen toegang tot persoonlijke informatie op uw computer en kunnen deze niet beschadigen of besmetten met virussen. De cookies geven op geen enkele manier persoonlijke informatie aan ons door. De informatie die we via cookies verzamelen helpt ons om je van specifieke diensten te laten genieten.",
  whatAreNecessaryCookiesTitle: "Wat zijn noodzakelijke cookies?",
  whatAreNecessaryCookiesDescription: "Noodzakelijke cookies zijn cookies die je nodig hebt om te surfen op de website en gebruik te maken van de functionaliteit die we aanbieden. Bovendien zijn de cookies noodzakelijk om de beveiligde onderdelen van de website te kunnen zien.",
  whichCookiesTitle: "Welke cookies gebruikt deze website?",
  dwengoCookieTitle: "Aanmelden als gebruiker (Dwengo cookie)",
  dwengoCookieDescription: "Bij het aanmelden op de website wordt een tijdelijke cookie gebruikt waardoor je herkend wordt als gebruiker. Met behulp van deze cookie wordt onder andere je taalinstelling en vooruitgang bewaard. De cookie zorgt er voor dat je toegang hebt tot de beveiligde delen van de website. Deze cookie is slechts geldig tot aan het einde van de sessie en is enkel beschikbaar voor en gemaakt door Dwengo vzw.",
  jenkinsCookieTitle: "Jenkins configuratie (Jenkins cookie)",
  jenkinsCookieDescription: "De Jenkins cookie is voor ons noodzakelijk om de Dwenguino simulator online op een server te kunnen installeren. Jenkins is software waarvan we gebruik maken om onze simulator te updaten. Die cookie bevat informatie over de instellingen van Jenkins en bevat dus ook geen enkele informatie over jou als gebruiker.",
};

MSG.dropzone = {
  dictSelectFile: "Wybierz plik",
  dictChooseFile: "Wybierz plik",
  dictDefaultMessage: "Upuść pliki tutaj, aby je załadować",
  dictFallbackMessage: "Twoja przeglądarka nie obsługuje drop down uploads.",
  dictFileTooBig: "Twój plik jest za duży ({{filesize}}MiB). Maksymalny rozmiar pliku: {{maxFilesize}}MiB.",
  dictFallbackText: "Proszę użyć poniższego formularza awaryjnego, aby przesłać pliki jak za dawnych czasów.",
  dictInvalidFileType: "Nie można przesyłać plików tego typu.",
  dictResponseError: "Serwer odpowiedział kodem {{statusCode}}.",
  dictCancelUpload: "Anuluj przesyłanie",
  dictCancelUploadConfirmation: "Czy na pewno chcesz anulować to przesyłanie?",
  dictRemoveFile: "Usuń plik",
  dictMaxFilesExceeded: "Nie można przesłać więcej plików.",
  dictUploadBlocks: "Prześlij bloki",
  dictFileNotSupported: "Ten plik nie jest obsługiwany.",
};

MSG.ledmatrix = {
  restPosition: 'Pozycja spoczynkowa', 
  blink1: 'Migacz 1',
  blink2: 'Migacz 2',
  blink3: 'Migacz 3',
  blink4: 'Migacz 4',
  blink5: 'Migacz 5',
  right1: 'Prawo 1',
  right2: 'Prawo 2',
  left1: 'Lewo 1',
  left2: 'Lewo 2',
  up1: 'Powyżej  1',
  up2: 'Powyżej 2',
  up3: 'Powyżej  3',
  down1: 'Poniżej 1',
  down2: 'Poniżej 2',
  down3: 'Poniżej 3',
  angryLeft1: 'Zły lewy 1',
  angryLeft2: 'Zły lewy 2',
  angryLeft3: 'Zły lewy 3',
  angryLeft4: 'Zły lewy 4',
  angryRight1: 'Zły prawy 1',
  angryRight2: 'Zły prawy 2',
  angryRight3: 'Zły prawy 3',
  angryRight4: 'Zły prawy 4',
  sadLeft1: 'Smutny lewy 1',
  sadLeft2: 'Smutny lewy 2',
  sadLeft3: 'Smutny lewy 3',
  sadRight1: 'Smutny prawy 1',
  sadRight2: 'Smutny prawy 2',
  sadRight3: 'Smutny prawy 3',
  evilLeft1: 'Złośliwy lewy 1',
  evilLeft2: 'Złośliwy lewy 2',
  evilRight1: 'Złośliwy prawy 1',
  evilRight2: 'Złośliwy prawy 2',
  scanHorizontal1: 'Skan poziomy 1',
  scanHorizontal2: 'Skan poziomy 2',
  scanHorizontal3: 'Skan poziomy 3',
  scanHorizontal4: 'Skan poziomy 4',
  scanVertical1: 'Skan pionowy 1',
  scanVertical2: 'Skan pionowy 2',
  scanVertical3: 'Skan pionowy 3',
  scanVertical4: 'Skan pionowy 4',
  scanVertical5: 'Skan pionowy 5',
  scanVertical6: 'Skan pionowy 6',
  rip1: 'RIP 1',
  rip2: 'RIP 2',
  peering1: 'Gapić się 1',
  peering2: 'Gapić się 2',
  peering3: 'Gapić się 3',
  peering4: 'Gapić się 4'
};

MSG.simulator = {
  start: "Start",
  stop: "Przestań",
  pause: "Pauza",
  step: "1 krok",
  speed: "Prędkość",
  speedVerySlow: "40 razy wolniej",
  speedSlow: "20 razy wolniej",
  speedMedium: "10 razy wolniej",
  speedFast: "5 razy wolniej",
  speedVeryFast: "2 razy wolniej",
  speedRealTime: "Czas rzeczywisty",
  components: "Wybierz części",
  servo: "Serwo",
  servoDescription: "Silnik serwo może obracać się o pewien kąt w zakresie od 0 do 180 stopni. W przypadku zastosowania bloku silników serwo należy wprowadzić w programie żądany kąt. W Toolbox znajdują się również bloki, które mogą być użyte np. do machania rękami; kąt jest już w nich ustawiony.",
  motor: "Silnik",
  DCMotorDescription: "Silnik prądu stałego obraca się całkowicie. Możesz użyć takiego silnika do napędzania robota. Prędkość obrotową silnika i kierunek obrotów musisz określić w twoim programie za pomocą liczb z zakresu od -255 do 255.",
  scope: "Zmienne",
  alertDebug: "Symulacja zatrzymuje się po wznowieniu programowania.",
  distance: "Odległość",
  scenario: "Scenariusz",
  scenario_default: "Normalna płytka",
  scenario_moving: "Robot ruchomy",
  scenario_wall: "Robot ruchomy ze ścianą",
  scenario_socialrobot:"Robot społeczny",
  code: "Kod",
  pir: "czujnik zbliżeniowy",
  pirDescription: "Użyj tego czujnika do wykrywania ruchu. W symulatorze znajduje się przycisk umożliwiający symulację ruchu przez naciśnięcie przycisku. W przypadku wykrycia czujnik zwraca 1, w przeciwnym razie 0.",
  sonar: "Czujnik sonaru",
  sonarDescription: "Użyj tego czujnika do wykrycia osoby lub obiektu i określenia jak daleko od czujnika znajduje się osoba lub obiekt. W symulatorze znajduje się pasek przewijania, który symuluje odległość między obiektem a czujnikiem. Czujnik zwraca odległość w centymetrach.",
  sound: "Czujnik dźwięku",
  soundDescription: "Użyj tego czujnika do wykrywania dźwięku. W symulatorze znajduje się przycisk do symulowania dźwięku. Gdy jest dźwięk, czujnik zwraca 1, gdy jest cisza, zwraca 0.",
  light: "Czujnik światła",
  lightDescription: "Użyj tego czujnika do wykrywania wysokiego lub niskiego poziomu oświetlenia. W symulatorze znajduje się suwak do symulowania światła i ciemności. Przy silnym oświetleniu czujnik światła symulatora zwróci wysoką wartość, przy słabym oświetleniu niską wartość.",
  led: "LED",
  ledDescription: "Symulator posiada ledy w czterech kolorach. Dioda jest sterowana przez pin, który sam wskazujesz. Jeśli kołek jest w stanie WYSOKIM, świeci się LED. Jeśli jest w stanie NISKIM, LED jest wygaszona.",
  rgbled: "RGB LED",
  rgbledDescription: "",
  ledmatrix: "LED matrix",
  ledmatrixDescription: "",
  ledmatrixsegment: "LED matrix segment",
  ledmatrixsegmentDescription: "",
  touch: "Czujnik dotyku",
  touchDescription: "Użyj tego czujnika do wykrycia, czy robot jest dotykany. W symulatorze znajduje się przycisk umożliwiający symulację dotyku poprzez jego naciśnięcie. Po dotknięciu czujnik zwraca 1, w przeciwnym razie 0",
  lcd: "ekran LCD",
  lcdDescription: "Ekran lcd zawiera dwie linie po 16 znaków każda. Żądany tekst, który podajesz w twoim programie.",
  button: "Przycisk",
  buttonDescription: "",
  sound: "Sound sensor",
  soundDescription: "Use the sound sensor to <b>detect sound</b>. In the simulator you will find a button to simulate the presence of sound. When the sound sensor detects sound it will output the value 1, otherwise it will output the value 0.",
  light: "Light sensor",
  lightDescription: "",
  buzzer: "Brzęczyk",
  buzzerDescription: "Dzięki brzęczykowi możesz grać dźwięk o wybranej przez siebie częstotliwości. Żądana częstotliwość (w Hz) jest podawana w programie. Za pomocą bloku oczekiwania określasz, jak długo dźwięk ma być odtwarzany.",
  decoration: "Decoracja",
};

MSG.socialrobot = {
  plain: "Puste serwo",
  eye: "Oko",
  mouth: "Usta",
  righthand: "Prawa ręka",
  lefthand: "Lewa ręka",
};

MSG.tutorialMenu = {
  header: "Samouczki",
  catDwenguino: "Naucz się programować<br>z DwenguinoBlockly",
  catDwenguinoComponents: "Pporęczny przegląd wszystkich komponentów Dwenguino",
  catDwenguinoConnector: "Pin mapping &<br>Expansion connector", catRidingRobot: "Robot ruchomy",
  catRidingRobot: "Robot",
  catSocialRobot: "Robot społeczny",
  catWeGoStem: "WeGoSTEM",
  chooseCategory: "Wybierz kategorię",
  chooseTutorial: "Wybierz samouczek",
  previous: "Poprzedni",
  close: "Zamknij",
  checkAnswer: "Sprawdź odpowiedź",
  correctAnswer: "Odpowiedź była prawidłowa!",
  wrongAnswer: "Odpowiedź była błędna. Proszę spróbować ponownie!",
  dwenguinoComponents: "Komponenty dwenguino",
  sensors: "Sensory",
  actuators: "Siłowniki",
  movement: "Ruch",
  audio: "Audio",
  display: "Wyświetlacz"
};

MSG.tutorials = {
  introduction: {},
  theremin: {},
  robot: {},
  basic_test: {},
  hello_dwenguino: {},
  blink: {},
  hello_robot: {},
  socialrobot: {},
};


MSG.tutorials.general = {
  sureTitle: "Czy jesteś pewien?",
  sureText: "Po kliknięciu 'Next' wszystkie bloki w obszarze roboczym zostaną usunięte.",
};

MSG.tutorials.introduction = {
  step1Title: "Witamy w DwenguinoBlockly",
  step1Content: "Cześć, mam na imię Dwenguino! Pomogę Ci zapoznać się z interfejsem!",
  step2aTitle: "Obszar kodowy Blockly",
  step2aContent: "W tym obszarze umieszczasz swoje bloki kodu. Powinieneś umieścić swoje bloki wewnątrz bloku setup-loop, jeśli chcesz, aby były one wykonywane.",
  step2bTitle: "Blockly toolbox",
  step2bContent: "To jest toolbox, zawiera wszystkie bloki, których możesz użyć do stworzenia twojego programu. W zależności od poziomu, który wybrałeś, zobaczysz więcej lub mniej bloków. Zbadaj i zobacz, jakie są bloki.",
  step3Title: "Wybór języka",
  step3Content: "Użyj tego, aby zmienić język",
  step4Title: "Trudność",
  step4Content: "Ten pasek przewijania możesz ustawić poziom trudności. Na wyższych poziomach masz bardziej zaawansowane bloki. Aby z nich korzystać, najlepiej najpierw opanować bloki na niższych poziomach. Na razie zapewniamy tylko poziomy początkujący i zaawansowany.",
  step5Title: "Dwengobooks",
  step5Content: "Dwengobooks to interaktywne tutoriale, które wyjaśniają krok po kroku jak napisać program.",
  step6Title: "Prześlij kod",
  step6Content: "Gdy uznasz, że twój program jest gotowy, możesz go wgrać na płytkę Dwenguino naciskając ten przycisk. (Nie zapomnij najpierw podłączyć płytki do komputera za pomocą kabla usb). <br/><em>Proszę zauważyć, że to działa tylko wtedy, gdy uruchomisz ten program w Arduino IDE, a nie online w przeglądarce.</em>",
  step7Title: "Otwórz",
  step7Content: "Ten przycisk pozwala na otwarcie wcześniej zapisanego programu.",
  step8Title: "Save",
  step8Content: "Ten przycisk pozwala na zapisanie bloków do lokalnego pliku.",
  step9Title: "Symulator",
  step9Content: "Ten przycisk pozwala na otwarcie symulatora. Możesz użyć tego do przetestowania twojego kodu przed wysłaniem go na płytę.",
};

MSG.tutorials.basic_test = {
  step1Title: "Sprawdź twoją podstawową wiedzę o Dwenguino",
  step1Content: "Jeśli nigdy wcześniej nie pisałeś programu dla Dwenguino, możesz użyć tego testu, aby zobaczyć jak daleko zaszedłeś.",
  step2Title: "Sekwencja",
  step2ContentA: "spójrz na kod, który widzisz w obszarze roboczym blockly. Po uruchomieniu kodu, jaka jest wartość, która znajduje się w a?",
  step2ContentB: "Jaka jest wartość, która jest w b?",
  stepEndTitle: "Tak dobrze!",
  stepEndContent: "Pomyślnie ukończyłeś quiz, przejdź do następnego!",
};

MSG.tutorials.theremin = {
  step1Title: "Przedmowa",
  step1Content: "W dzisiejszych czasach urządzenia elektroniczne są nieodzowne. Wiele z tych urządzeń jest sterowanych przez mikrokontrolery. W tej książce poznajemy krok po kroku wspaniały świat mikrokontrolerów. Pod koniec książki będziesz mógł zaprogramować twoje własne pianino cyfrowe. W ten sposób stworzysz twój pierwszy system wbudowany: cyfrowy system, który jest w stanie współdziałać ze swoim otoczeniem.\
Robimy to za pomocą Dwenguino, łatwej, wielofunkcyjnej platformy mikrokontrolerowej. Dwenguino jest wyposażony w wiele funkcji, które sprawią, że pierwsze kroki pójdą gładko. Dzięki kompatybilności z Arduino IDE odbywa się to za pomocą dobrze przemyślanych narzędzi, które umożliwiają programowanie zarówno graficzne jak i tekstowe.\
Eksperymentowanie z mikrokontrolerami może odbywać się w domu lub w klasie. Niniejsza książeczka jest przeznaczona przede wszystkim dla nauczycieli, którzy w ramach swoich zajęć lekcyjnych zajmują się informatyką, elektroniką lub inżynierią. Ale młodzi ludzie mogą również odkryć tę książeczkę na własną rękę. Dzięki temu ich nauka będzie jeszcze bardziej intensywna.\
Powodzenia!",
  step2Title: "Mikrokontrolery wszędzie",
  step2Content: "W ciągu ostatnich dziesięcioleci liczba urządzeń cyfrowych w domu, ogrodzie i środowisku pracy gwałtownie wzrosła. Zaczęło się od wprowadzenia prostych rzeczy, takich jak budziki i elektryczne szczoteczki do zębów, ale obecnie prawie każde urządzenie jest inteligentne. Może masz kosiarkę lub robota odkurzacza w domu, a nawet samojeżdżący samochód, to z pewnością nie są science fiction w dzisiejszych czasach!\
W rzeczywistości wszystkie te urządzenia są w coraz większym stopniu podłączone do Internetu, tworząc Internet Rzeczy (internet of things). Badania szacują, że do 2020 roku ponad 50 miliardów urządzeń będzie podłączonych do Internetu. Nie mówimy tu tylko o smartfonach i tabletach, ale także o inteligentnych czujnikach dymu, inteligentnych lodówkach i robotach, na przykład.\
Podstawą wszystkich tych urządzeń są cyfrowe systemy obliczeniowe, które zapewniają niezbędną inteligencję. Przykładem tego jest mikrokontroler, który zawiera wszystko, co niezbędne do przetwarzania danych z czujników, wykonywania obliczeń i podejmowania działań.",
  step3Title: "Płyta",
};

MSG.tutorials.hello_dwenguino = {
  step1Title: "Cześć Dwenguino!",
  step1Content: "W tym tutorialu napiszesz twój pierwszy program dla Dwenguino. Ten program zapisuje tekst 'Hello Dwenguino' na ekranie LCD płytki.",
  step2Title: "Symulator",
  step2Content: "Kliknij na przycisk symulatora, aby go otworzyć.",
  step3Title: "Przeciąganie bloków z toolbox",
  step3Content: "Teraz weź poniższy blok z przybornika i umieść go pod tekstem <em><b>przygotuj się na start</b></em>. </br><img src='img/helloDwenguino/dwenguinoLCD.png' alt='obraz bloku lcd dwenguino' style='max-width:100%'/>",
  step4Title: "Aby wykonać tój kod",
  step4Content: "Aby wykonać swój kod w symulatorze, naciśnij przycisk <em><b>Start</b></em>.</br>Co widzisz? </br>Przycisk <em><b>Stop</b></em> pozwala zatrzymać wykonywanie w symulatorze.</br>Zauważ, że nie możesz modyfikować kodu podczas jego wykonywania.",
  step5Title: "Blok 'ustaw, powtórz",
  step5Content: "Kod znajdujący się pod tekstem <em><b>przygotuj się na starcie</b></em>zostanie wykonany jeden raz na początku programu. Kod znajdujący się pod tekstem <em><b>powttórz</b></em> powtarza się w nieskończoność.</br>Is er een verschil wanneer je het <em><b>lcd</b></em>-blok in het gedeelte <em><b>zet klaar bij start</b></em> of het gedeelte <em><b>herhaal</b></em> zet?",
  step6Title: "Teraz ty!",
  step6Content: "Spróbuj teraz! Zmień tekst na ekranie na twoje własne imię. </br> Spróbuj też sprawić, by tekst pojawiał się w drugiej linii ekranu.",
};

SG.tutorials.blink = {
  step1Title: "Migacz",
  step1Content: "W tym tutorialu napiszemy program, który będzie włączał i wyłączał LD13 na przemian. Zadbamy o to, aby LED zapalała się i gasła dwa razy na sekundę.",
  step2Title: "Symulator",
  step2Content: "Kliknij na przycisk symulatora, aby go otworzyć.",
  step3Title: "Przeciągnij bloki z przybornika",
  step3Content: "Użyj następujących bloków do napisania twojego programu: </br><img src='img/blink/requiredBlocks.png' alt='Obraz bloków wymaganych do ćwiczenia mrugania' style='max-width:100%'/></br><b>Wskazówka:</b> czas w bloku <em><b>oczekiwania</b></em> jest podany w milisekundach.</br> 1 sekunda = 1000 milisekund.",
  step4Title: "Wykonaj kod",
  step4Content: "Aby wykonać twój kod w symulatorze, naciśnij przycisk <em><b>Start</b></em>.</br> Co widzisz ?</br>Przycisk <em><b>Stop</b></em> pozwala zatrzymać wykonywanie w symulatorze.</br>Zwróć uwagę, że nie możesz modyfikować kodu podczas jego wykonywania.",
  step5Title: "Czy twój kod działa poprawnie?",
  step5Content: "Jeśli Twój kod nadal nie działa poprawnie, możesz spróbować rozgryźć błąd, przechodząc przez kod blok po bloku.Robisz to klikając na przycisk <em><b>1 krok</b></em> w symulatorze.</br>Jeśli Twój kod działa teraz poprawnie, brawo!",
  step6Title: "Teraz ty!",
  step6Content: "Spróbuj teraz!</br><ul><li>Zmień prędkość migania tak, aby LED zapalała się i gasła raz na sekundę.</li><li>Wybierz inną LED, którą chcesz włączyć lub wyłączyć.</li><li>Spróbuj włączać i wyłączać kilka ledów.</li></ul>",
};

MSG.tutorials.hello_robot = {
  step1Title: "Jeżdżący robot",
  step1Content: "W tym samouczku zaprogramujesz dwukołowego jeżdżącego robota. Otrzymasz zadanie, aby robot jeździł po różnych wzorach.",
  step2Title: "Symulator",
  step2Content: "Kliknij na przycisk symulatora, aby go otworzyć.",
  step3Title: "Wybierz scenariusz",
  step3Content: "Aby móc zaprogramować naszego jeżdżącego robota, należy wybrać w symulatorze scenariusz <em><b>Robota kroczącego</b></em>.",
  step4Title: "Jechać do przodu",
  step4Content: "Pierwszym zadaniem jest sprawienie, aby robot jechał prosto przed siebie. Każde koło robota jest połączone z silnikiem prądu stałego. Aby zaprogramować te silniki użyj następującego bloku:</br><img src='img/helloRobot/DCMotor.png' alt='Motor block' style='max-width:100%'/></br>Zmieniając tę <em><b>liczbę</b></em>, można uruchomić silnik 1 lub 2.</br> <em><b>prędkość</b></em> jest określana liczbą z zakresu od -255 do 255. (-255 = maksymalna prędkość do tyłu, 0 = brak obrotów, 255 = maksymalna prędkość do przodu).",
  step5Title: "Zakręt",
  step5Content: "Zastanów się, jak możesz sprawić, by twój robot tworzył kąt prosty. </br><b>Wskazówka:</b> obróć koła w przeciwnym kierunku, aby robot wykonał zakręt.",
  step6Title: "Kwadrat",
  step6Content: "Teraz, gdy udało Ci się zmusić robota do wykonania skrętu o 90°, możesz spróbować zmusić go do jazdy w kwadracie.",
};

MSG.tutorials.nameOnLcd = {
  step1Title: "Imię na ekranie LCD",
  step1Content: "Otwórz widok symulatora i przetestuj kod. Co widzisz?",
  step2Title: "Imię na ekranie LCD",
  step2Content: "Zmień program tak, aby twoje imię pojawiało się w pierwszej linii ekranu LCD.",
};

MSG.tutorials.blinkLED = {
  step1Title: "Mruganie LED",
  step1Content: "Otwórz widok symulatora i przetestuj kod. Co widzisz?",
  step2Title: "Mruganie LED",
  step2Content: "Zmień program tak, aby LED zaświeciła się na jedną sekundę, a następnie zgasła na jedną sekundę. Ta sekwencja jest powtarzana w nieskończoność.",
  step3Title: "Extra",
  step3Content: "Włączanie i wyłączanie kolejnej LED.",
};

MSG.tutorials.ledOnButtonPress = {
  step1Title: "LED po naciśnięciu przycisku",
  step1Content: "Otwórz widok symulatora i przetestuj kod. Co widzisz?",
  step2Title: "LED po naciśnięciu przycisku",
  step2Content: "Zmień program tak, aby LED włączała się po naciśnięciu przycisku północnego.",
  step3Title: "Extra",
  step3Content: "Upewnij się, że LED wyłącza się po zwolnieniu przycisku północnego.",
};

MSG.tutorials.bitPatternOnLeds = {
  step1Title: "Wzór na diodach LED",
  step1Content: "Otwórz widok symulatora i przetestuj kod. Co widzisz?",
  step2Title: "Wzór na diodach LED",
  step2Content: "Kod, który masz jest bardzo długi. Czy możesz uzyskać ten sam rezultat używając mniejszej ilości bloków? Spróbuj uzyskać ten sam rezultat używając mniejszej liczby bloków!",
  step3Title: "Wzór na diodach LED",
  step3Content: "Gdy uda ci się zredukować liczbę bloków, żałuj jednego z nauczycieli, aby uzyskać informację zwrotną na swój sposób rozwiązania.",
};

MSG.tutorials.allButtons = {
  step1Title: "Wszystkie przyciski",
  step1Content: "Otwórz widok symulatora i przetestuj kod. Co widzisz?",
  step2Title: "Wszystkie przyciski",
  step2Content: "Ten kod powinien włączać diodę LED, gdy jeden z przycisków zostanie naciśnięty. Spójrz na program. Czy wszystkie przyciski działają? Spróbuj poprawić kod dla przycisków, które nie działają.",
  step3Title: "Dodatkowy",
  step3Content: "Zmień kod tak, aby dioda LED wyłączała się po zwolnieniu przycisku.",
};

MSG.tutorials.driveForward = {
  step1Title: "Jazda do przodu",
  step1Content: "Otwórz widok symulatora.",
  step2Title: "Jazda do przodu",
  step2Content: "Otwórz widok symulatora i przetestuj kod. Co widzisz?",
  step3Title: "Jazda do przodu",
  step3Content: "Czy samochód jeździ do przodu? Popraw kod tak, aby samochód jechał do przodu.",
};

MSG.tutorials.rideInSquare = {
  step1Title: "Jazda do kwadratu",
  step1Content: "Otwórz widok symulatora.",
  step2Title: "Jazda do kwadratu",
  step2Content: "Wybierz scenariusz jeżdżący robot i przetestuj kod w symulatorze. Co widzisz?",
  step3Title: "Jazda do kwadratu",
  step3Content: "Czy samochód jeździ w kwadracie? Postaraj się znaleźć błąd i poprawić go. Do tego celu należy użyć debuggera.",
  step4Title: "Dodatkowy",
  step4Content: "Kod jest długi, czy możesz go skrócić zachowując to samo zachowanie?",
};

MSG.tutorials.rideToWall = {
  step1Title: "Jazda do ściany",
  step1Content: "Otwórz widok symulatora.",
  step2Title: "Jazda do ściany",
  step2Content: "Wybór widoku scenariusza.",
  step3Title: "Jazda do ściany",
  step3Content: "Zmień scenariusz na Poruszający się robot ze ścianą i przetestuj kod. Co widzisz?",
  step4Title: "Jazda do ściany",
  step4Content: "Czy samochód podjeżdża do ściany? Czy zatrzymuje się przy ścianie? Zmień kod tak, aby samochód zatrzymał się przy ścianie.",
};

MSG.tutorials.avoidWall = {
  step1Title: "Unikaj ścian",
  step1Content: "Otwórz widok symulatora.",
  step2Title: "Unikaj ścian",
  step2Content: "Wybór widoku scenariusza.",
  step3Title: "Unikaj ścian",
  step3Content: "Zmień scenariusz na jeżdżący robot przy ścianie i przetestuj kod. Co widzisz?",
  step4Title: "Unikaj ścian",
  step4Content: "Czy samochód unika ściany skręcając zanim do niej dojedzie? Zmień kod tak, aby samochód jechał dalej, ale nigdy nie uderzył w ścianę.",
};

MSG.tutorials.nameOnLcdBasic = {
  step0Title: "Jesteś pewien?",
  step0Content: "Jesteś pewien? Po kliknięciu przycisku next bloki na arkuszu zostaną zastąpione.",
  step1Title: "Imię na ekranie LCD",
  step1Content: "W tym tutorialu umieścisz twoje imię na ekranie LCD. Możesz zobaczyć przykład jak to zrobić.</br>Spójrz na kod i spróbuj zrozumieć, co on robi.",
  step2Title: "Badanie na tablicy",
  step2Content: "Przetestuj kod podłączając płytkę Dwenguino do komputera za pomocą kabla usb i wciśnij przycisk play.",
  step3Title: "Twoje własne imię",
  step3Content: "W tej chwili na ekranie widzisz imię \"Tom\". Zmień kod, aby zobaczyć twoje imię.",
  step4Title: "Dwa rzędy",
  step4Content: "Ekran LCD składa się z dwóch rzędów. Zmień wiersz z twoim imieniem z 0 na 1.",
  step5Title: "Test",
  step5Content: "przetestuj twój kod.",
  step6Title: "Gratulacje!",
  step6Content: "Dobra robota! Teraz już wiesz, jak umieścić tekst na ekranie LCD.",
};

MSG.tutorials.nameOnLcdWeGoSTEM = {
  step1Title: "Otwórz okno symulatora",
  step1Content: "Otwórz okno symulatora naciskając przycisk symulatora.",
  step2Title: "Imię na ekranie LCD",
  step2Content: "W tym ćwiczeniu umieścisz swoje imię na ekranie LCD. Zobaczysz przykład, jak to zrobić.</br> Spójrz na bloki kodu i spróbuj zrozumieć, co to robi.",
  step3Title: "Testowanie w symulatorze",
  step3Content: "Przetestuj twój kod, naciskając <e>Start</e> w symulatorze.</br> Co widzisz?",
  step4Tite: "Zatrzymaj symulację",
  step4Content: "Zatrzymaj test, naciskając <e>Stop</e>",
  step5Title: "Twoje własne imię",
  step5Content: "Obecnie na ekranie pojawia się imię \"Tom\". Zmień kod, aby zobaczyć twoje imię.",
  step6Title: "Dwa rzędy",
  step6Content: "Ekran LCD składa się z dwóch rzędów. Zmień wiersz z twoim imieniem z 0 na 1.",
  step7Tite: "Test",
  step7Content:"przetestuj twój kod.",
  step8Title: "Gratulacje!",
  step8Content: "Dobra robota! Teraz już wiesz, jak umieścić tekst na ekranie LCD.",
};

MSG.tutorials.introduceYourself = {
  step1Title: "Otwórz okno symulatora",
  step1Content: "Otwórz okno symulatora naciskając przycisk symulatora.",
  step2Title: "Przedstawiając się",
  step2Content: "W tym ćwiczeniu przedstawisz się za pomocą ekranu LCD. </br> Spójrz na kod i spróbuj dowiedzieć się, co to robi.",
  step3Title: "Testowanie w symulatorze",
  step3Content: "Przetestuj twój kod, naciskając <e>Start</e> w symulatorze.</br>Co widzisz?",
  step4Title: "Zatrzymaj symulację",
  step4Content: "Zatrzymaj test, naciskając <>iStop</i>.</br>Co robi ten program? Zapisz to.",
  step5Title: "Dostosuj kod",
  step5Content: "Istnieją pewne różnice między tekstem, który pokazuje ten program, a tym, co chcesz, aby program pokazywał.</br>Wyreguluj program tak, aby wyświetlany był prawidłowy tekst.",
  step6Title: "Udało się?",
  step6Content:"Czy udało Ci się poprawić kod?",
};

MSG.tutorials.showNameAndDisappear = {
  step1Title: "Otwórz okno symulatora",
  step1Content: "Otwórz okno symulatora naciskając przycisk symulatora.",
  step2Title: "pokaż imię",
  step2Content: "W tym ćwiczeniu wyświetlasz twoje imię na ekranie LCD przez 2 sekundy, a następnie sprawiasz, że znika ono ponownie.",
  step3Title: "Testowanie w symulatorze",
  step3Content: "Przetestuj twój kod, naciskając <e>Start</e> w symulatorze.</br>Co widzisz?",
  step4Title: "Zatrzymaj symulator",
  step4Content: "Zatrzymaj test, naciskając <i>Stop</i>.</br>Co robi ten program? Zapisz to.",
  step5Title: "Dostosuj kod",
  step5Content: "Jakie są różnice między tym programem a tym, który chcesz dostać? </br> Popraw twój kod!",
  step6Title: "Udało się?",
  step6Content:"Czy udało Ci się poprawić kod?",
};

MSG.tutorials.poem1 = {
  step1Title: "Otwórz okno symulatora",
  step1Content: "Otwórz okno symulatora naciskając przycisk symulatora.",
  step2Title: "Wierz",
  step2Content: "Ten program powinien wyświetlić na ekranie LCD wiersz, który widzisz na płycie.",
  step3Title: "Testowanie w symulatorze",
  step3Content: "Przetestuj twój kod, naciskając <e>Start</e> w symulatorze.</br> Co widzisz?",
  step4Title: "Zatrzymaj symulację",
  step4Content: "Zatrzymaj test, naciskając <i>Stop</i>.</br>Co robi ten program? Zapisz to.",
  step5Title: "Dostosuj kod",
  step5Content: "Jakie są różnice między tym programem a tym, który chcesz dostać? </br>Ten program zawiera dwa błędy.</br>Możesz wypróbować kod tak bardzo, jak chcesz, aby znaleźć błędy.</br><b>Spróbuj poprawić błędy w programie.</b>",
  step6Title: "Udało się?",
  step6Content: "Czy udało Ci się poprawić kod?",
};
  
MSG.tutorials.poem2 = {
  step1Title: "Otwórz okno symulatora",
  step1Content: "Otwórz okno symulatora naciskając przycisk symulatora.",
  step2Title: "Wierz",
  step2Content: "Ten program pokazuje wiersz, który można zobaczyć na płycie na ekranie LCD.",
  step3Title: "Testowanie w symulatorze",
  step3Content: "Przetestuj twój kod, naciskając <e>Start</e> w symulatorze.</br> Co widzisz?",
  step4Title: "Zatrzymaj symulację",
  step4Content: "Zatrzymaj test, naciskając <i>Stop</i>.</br>Co robi ten program? Zapisz to.",
  step5Title: "Dostosuj kod",
  step5Content: "Program działa poprawnie, ale jest bardzo duży. Spróbuj skrócić kod poprzez użycie bloku <b>obliczenie z.</b>.",
  step6Title: "Udało się?",
  step6Content: "Czy udało Ci się poprawić kod?",
};
    
MSG.tutorials.lampOnOffWeGoSTEM = {
  step1Title: "Otwórz okno symulatora",
  step1Content: "Otwórz okno symulatora naciskając przycisk symulatora.",
  step2Title: "Wierz",
  step2Content: "Ten program powinien sprawić, że lampa numer 3 będzie migać 1 raz na sekundę.",
  step3Title: "Testowanie w symulatorze",
  step3Content: "Przetestuj twój kod, naciskając <e>Start</e> w symulatorze.</br> Co widzisz?",
  step4Title: "Zatrzymaj symulację",
  step4Content: "Zatrzymaj test, naciskając <i>Stop</i>.</br>Co robi ten program? Zapisz to.",
  step5Title: "Dostosuj kod",
  step5Content: "Czy program działa tak, jak powinien?</br>Zmodyfikuj program tak, aby działał poprawnie",
  step6Title: "Udało się?",
  step6Content:"Czy udało Ci się poprawić kod?",
};
      
/**
 * Social robot tutorials
 */
MSG.tutorials.socialrobot['introduction'] = {};
MSG.tutorials.socialrobot['introduction'].label = '1. Praca z symulatorem';
MSG.tutorials.socialrobot['introduction'].stepTitles = [
  "Zaprojektuj robota",
  "Idź do symulatora",
  "wybierz twój scenariusz",
  "Dodaj bloki",
  "Zmontuj twojego robota",
  "Usuń bloki",
  "Kontroluj twojego robota",
  "Kontroluj twojego robota",
  "Koniec"
];
MSG.tutorials.socialrobot['introduction'].stepContents = [
  "Podczas tego samouczka zajmiesz się projektowaniem twojego własnego robota społecznego. Odkryjesz, co możesz zrobić z <b>symulatorem</b>. <br><img class='tutorial' src='./DwenguinoIDE/img/tutorials/socialrobot/socialrobot.png'><br><!Po tym, możesz przejść przez następujące samouczki, aby dowiedzieć się, jak zbudować osobistego robota krok po kroku.-->",
  "Budowanie robota odbywa się w symulatorze. Otwierasz i ukrywasz go klikając ten przycisk.",
  "W symulatorze można nie tylko budować roboty społeczne, ale także symulować roboty jeżdżące. Istnieją więc różne scenariusze. <b>Kliknij teraz scenariusz robota społecznego.</b> Zobaczysz wtedy inne bloki.",
  "Tutaj zobaczysz wszystkie bloki z symulatora, które możesz wykorzystać do zaprojektowania twojego robota. <br><br> Kliknij na przycisk <b>+</b>, aby dodać blok do twojego robota <b>. Czy widzisz, że pojawia się na dole symulacji?",
  "Po dodaniu bloku konstrukcyjnego możesz przeciągnąć go tutaj w inne miejsce. W ten sposób możesz zdecydować, jak będzie wyglądał twój robot. <br><br>Przesuń mysz nad nowy blok konstrukcyjny i przeciągnij go na robota za pomocą <img class='tutorial' src='./DwenguinoIDE/img/tutorials/socialrobot/drag.jpg' width='20px'>.",
  "Jeśli dodałeś o jeden blok za dużo, możesz <b>usunąć</b> ostatnio utworzony blok ponownie za pomocą <b>przycisku</b>. <br><br>Usuń wszystkie bloki ze twojego robota. Czy się udało?",
  "Wiesz już, jak zbudować robota, ale twój robot nie może się jeszcze poruszać. Dlatego nadal musimy sterować robotem za pomocą samodzielnie napisanego programu. Można to zrobić za pomocą <b>bloków programistycznych</b> z <b>toolboxa</b>.",
  "Kiedy przeciągasz bloki z toolboxa, lądują one w <b>obszarze kodu</b>. To tutaj będzie program, który napiszesz.",
  "Jesteście teraz gotowi do rozpoczęcia kolejnych samouczków, w których nauczycie się korzystać z blokami robota.",
];
MSG.tutorials.socialrobot['socialrobots'] = {};
MSG.tutorials.socialrobot['socialrobots'].label = '2. Roboty społeczne';
MSG.tutorials.socialrobot['socialrobots'].stepTitles = [
  "Roboty społeczne",
  "Roboty społeczne",
  "Roboty społeczne",
  "Roboty społeczne",
];

MSG.tutorials.socialrobot['socialrobots'].stepContents = [
  "Roboty społeczne to roboty, które, podobnie jak ludzie między sobą, potrafią się z nami komunikować.",
  "Są one zaprojektowane, aby zrozumieć ludzi i zwiększyć nasze dobrobyt społeczny",
  "Dokładnie to, co robią roboty społeczne i w jakim środowisku różni się w zależności od robota.",
  "Niektóre roboty będą zaprojektowane tak, aby znajdowały się w twoim domu. Inni będą funkcjonować tylko w pracy lub",
  "w przestrzeni publicznej. <br><br>Mogłeś już spotkać się z robotem społecznym ",
  "na lotnisku? Ten pomoże Ci z biletami lotniczymi lub znalezieniem właściwej bramki.",
  "Nawet w domu spokojnej starości w dzisiejszych czasach można znaleźć roboty do przytulania, które dotrzymują towarzystwa mieszkańcom",
  "Aby wejść w interakcję ze światem zewnętrznym, roboty używają <b>czujników</b> i <b>aktuatorów</b>.",
  "<br><br><b>Czujniki</b> to wejścia sensoryczne, które pozwalają robotowi \"mierzyć\" swoje otoczenie.",
  "Te dane pomiarowe mogą być następnie przetwarzane na informacje. Istnieją wszelkiego rodzaju czujniki,",
  "na przykład czujniki temperatury, światła, podczerwieni, ciśnienia lub ruchu.",
  "<br><br><div class='row'><div class='col-md-4'><img class='tutorial' src='./DwenguinoIDE/img/sonar.png' width='120px'></div>",
  "<div class='col-md-4'><img class='tutorial' src='./DwenguinoIDE/img/socialrobot/pir.png' width='70px'></div></div>",
  "<div class='row'><div class='col-md-4 tutorial'><i>Czujnik ultradźwiękowy</i></div><div class='col-md-4 tutorial'><i>Pasywny czujnik podczerwieni</i>.</div><br><br>",
  "<b>Aktuatory</b> są wyjściami, które pozwalają robotowi 'działać'.",
  "Na przykład, pomyśl o silniku serwo, który kontroluje ramię robota tak, że robot macha do ciebie, gdy cię widzi.<br><br>",
  "<div class='row'><div class='col-md-4'><img class='tutorial' src='./DwenguinoIDE/img/servo.png' width='100px'></div>",
  "<div class='col-md-4'><img class='tutorial' src='./DwenguinoIDE/img/dc.png' width='100px'></div></div>",
  "<div class='row'><div class='col-md-4 tutorial'><i>Silnik serwo</i></div><div class='col-md-4 tutorial'><i>Silnik prądu stałego</i></div></div>",
  "Robot musi podejmować własne <b>decyzje</b>. Może to zrobić w oparciu o dane",
  "które mierzą czujniki. Decyzje podejmowane są zazwyczaj w <b>procesorze</b> (w komputerze)",
  "lub <b>mikrokontroler</b> (przy symulatorze).",
  "<br><br>Mikrokontroler naszego symulatora wygląda tak:",
  "<div class='row'><img class='tutorial center-block' src='./DwenguinoIDE/img/tutorials/dwenguino.png'></div>"
];
MSG.tutorials.socialrobot['hello'] = {};
MSG.tutorials.socialrobot['hello'].label = "3. Powiedz cześć";
MSG.tutorials.socialrobot['hello'].stepTitles = [
  "Wprowadzenie",
  "Do symulatora",
  "Robot społeczny",
  "Wybierz właściwy bloki",
  "Dodaj ekran LCD do twojego robota",
  "Dodaj ekran LCD do twojego kodu",
  "Zagraj w symulację",
  "Zatrzymaj twoją symulację",
  "Pytanie"
];
MSG.tutorials.socialrobot['hello'].stepContents = [
  "W tym tutorialu dowiesz się jak sprawić, by robot coś powiedział. Wykorzystamy do tego ekran LCD.",
  "Otwórz symulator.",
  "Wybierz robota społecznego.",
  "<b>Przewiń</b> przez menu bloków, aż znajdziesz <b>ekran LCD</b>.",
  "Kliknij na przycisk <b>+</b>, aby dodać ekran LCD do twojego robota.",
  "Następnie przeciągnij ekran do miejsca na robocie, w którym chcesz go umieścić.",
  "Czas sprawić, by coś pojawiło się na ekranie. Kliknij na menu <b>Dwenguino</b>.",
  "i przeciągnij <b>ekran LCD</b> z toolboxa. Zatrzasnąć ekran w bloku \"set\".",
  " Wprowadź wiadomość, która ma być wyświetlana na ekranie.<br>",
  "<div class='row'><img class='tutorial center-block' src='./DwenguinoIDE/img/tutorials/socialrobot/lcd1.png'>",
  "<p class='tutorial center-block'><i>Program wyświetli tekst \'Cześć!\' na ekranie LCD.</i></p></div>",
  "Teraz naciśnij przycisk <b>play</b>, aby uruchomić twój program.",
    + "<br><br>Czy widzisz tekst pojawiający się na ekranie LCD robota?",
  "Teraz naciśnij przycisk <b>stop</b>, aby zatrzymać symulację.",
  "Placeholder"
];
MSG.tutorials.socialrobot['hello'].questions = [
  "Wybierz odpowiedni wynik dla poniższego programu."
];
MSG.tutorials.socialrobot['hello'].answers = [
  "Odpowiedź A",
  "Odpowiedź B"
];


MSG.logging = {
  setup: "Ustawienia ",
  login: "Login",
  logout: "Log out",
  firstname: "First name",
  newuser: "Nowy użytkownik",
  username: "Nazwa użytkownika",
  chooseUsername: "Wybierz nazwę użytkownika",
  email: "Email address",
  enterEmail: "Enter email address",
  forgotPassword: "I forgot my password",
  userDoesNotExist: "This user does not exist. Try a different email address.",
  resetPassword: "Reset your password",
  back: "Back",
  enterFirstname: "Enter your first name",
  password: "Password",
  repeatedPassword: "Repeat password",
  enterPassword: "Enter password",
  enterRepeatedPassword: "Repeat your password",
  choosePassword: "Wybierz 4 obrazki jako hasło. Musisz je zapamiętać w odpowiedniej kolejności.",
  currentlySelected: "Obecnie wybrany:",
  language: "Language",
  english: "English",
  dutch: "Dutch",
  role: "Role",
  student: "Student",
  teacher: "Teacher",
  verification: "Verify your email address",
  verificationSentTo: "A verification message has been sent to your email address. Click the link in the email to verify your account.",
  birth: "Data urodzenia",
  school: "Szkoła",
  selectSchool: "Szukaj według nazwy szkoły...",
  agegroup: "wiek:",
  primary1: "Szkoła podstawowa 1",
  primary2: "Szkoła podstawowa 2",
  primary3: "Szkoła podstawowa 3",
  primary4: "Szkoła podstawowa 4",
  primary5: "Szkoła podstawowa 5",
  primary6: "Szkoła podstawowa 6",
  secondary1: "Szkoła średnia 1",
  secondary2: "Szkoła średnia 2",
  secondary3: "Szkoła średnia 3",
  secondary4: "Szkoła średnia 4",
  secondary5: "Szkoła średnia 5",
  secondary6: "Szkoła średnia 6",
  gender: "Płeć: ",
  gender1: "K",
  gender2: "M",
  gender3: "X",
  gender4: "Wolałbym nie mówić",
  activity: "Działalność: ",
  name: "Imię",
  date: "Data",
  ok: "Ok",
  continue: "Continue",
  reset: "Reset",
  person: "Osoba",
  dog: "Pies",
  car: "Samochód",
  camera: "Kamera",
  heart: "Serca",
  plane: "Samolot",
  house: "Dom",
  umbrella: "Parasol",
  star: "Gwiazda",
  money: "Pieniądze",
  gift: "Prezent",
  keys: "Klucze",
  music: "Muzyka",
  snowflake: "Płatek śniegu",
  fire: "Ogień",
  envelope: "Koperta",
  conditions: "Voorwaarden",
  conditions1: "Om de app te gebruiken, moet je akkoord gaan met de <b>gebruiksvoorwaarden</b> en het <b>privacybeleid</b>.",
  generalConditions: "de gebruiksvoorwaarden",
  privacyStatement: "het privacybeleid",
  conditions2: "Daar staat onder andere in dat je moet inloggen om te beschikken over functionaliteit zoals het bewaren van je programma's of het bijhouden van je voortgang, dat je data anoniem wordt gelogd en verwerkt, en dat je ons mag mailen met vragen over privacy.",
  conditions3: "Ben je <b>13 jaar of ouder?</b> Dan mag je hieronder <b>zelf bevestigen</b> dat je de info hebt gelezen en akkoord gaat.",
  conditions4: "Ben je <b>12 jaar of jonger?</b> Dan moet een van je ouders of voogden toestemming geven.",
  acceptConditions: "Ik ga akkoord met de gebruiksvoorwaarden en het privacybeleid van de Dwengo-simulator",
  acceptResearch: "Ik geef toestemming aan Dwengo vzw om de gegevens die de simulator verzamelt, voor <b>wetenschappelijk onderzoek</b> te gebruiken, geanonimiseerd en volgens het privacybeleid.",
  anonymized: "* <b>\'Geanonimiseerd\'</b> wil zeggen dat er geen link is tussen je persoonsgegevens en je data. Niemand weet dus wat je deed in de simulator."
};

MSG.validator = {
  errSchool: "Wybierz szkołę.",
  errId: "Nie wybrano wystarczającej liczby ikon.",
  errAgeGroup: "Wybierz grupę wiekową.",
  errGender: "Wybierz rodzaj.",
  errFirstname: "Je voornaam is niet ingevuld.",
  errLastname: "Je achternaam is niet ingevuld.",
  errPassword: "Je paswoord voldoet niet aan de voorwaarden.",
  errPasswordNotIdentical: "Je paswoorden zijn niet identiek.",
  errEmail: "Je email is niet geldig",
  errActivityId: "Nazwa aktywności nie może być pusta.",
  errAcceptConditions: "Je hebt de gebruiksvoorwaarden en het privacybeleid nog niet geaccepteerd.",
  errAcceptResearch: "Je hebt nog geen toestemming gegeven om de gegevens voor wetenschappelijk onderzoek te laten gebruiken.",
  errRequiredFields: "Je hebt niet alle velden ingevuld.",
  errRoleInvalid: "De opgegeven rol is niet geldig."
};