var MSG = {
  title: "DwenguinoBlockly",
  blocks: "Blokken",
  linkTooltip: "Opslaan en koppelen naar blokken.",
  runTooltip: "Voer het programma uit dat met de blokken in de werkruimte is gemaakt.",
  loadBlocksFileTooltip: "Laadt een block bestand in dat je eerder hebt opgeslagen.",
  saveBlocksFileTooltip: "Sla de blokken op naar een lokaal bestand.",
  toggleSimulator: "Open of sluit het simulatorvenster.",
  badCode: "Programmafout:\n%1",
  timeout: "Het maximale aantal iteraties is overschreden.",
  trashTooltip: "Alle blokken verwijderen",
  catLogic: "Logica",
  catLoops: "Lussen",
  catMath: "Formules",
  catText: "Tekst",
  catLists: "Lijsten",
  catColour: "Kleur",
  catVariables: "Variabelen",
  catFunctions: "Functies",
  catDwenguino: "Dwenguino",
  catBoardIO: "IO",
  listVariable: "lijst",
  textVariable: "tekst",
  httpRequestError: "Er is een probleem opgetreden tijdens het verwerken van het verzoek.",
  linkAlert: "Deel uw blokken via deze koppeling:\n\n%1",
  hashError: "\"%1\" komt helaas niet overeen met een opgeslagen bestand.",
  xmlError: "Uw opgeslagen bestand kan niet geladen worden. Is het misschien gemaakt met een andere versie van Blockly?",
  badXml: "Fout tijdens het verwerken van de XML:\n%1\n\nSelecteer \"OK\" om uw wijzigingen te negeren of \"Annuleren\" om de XML verder te bewerken.",
  pressed: "INGEDRUKT",
  setup: "zet klaar bij start",
  loop: "herhaal",
  dwenguino_main_program_structure: "Het eerste stukje code wordt maar een keer uitgevoerd bij het starten van het programma. De code in de 'herhaal' wordt steeds opnieuw herhaalt tot het programma stopt (bv. wanneer je de stekker uit het bordje trekt).",
  catDwenguino: "Dwenguino",
  delay_help: "Wacht een opgegeven aantal miliseconden. (1 miliseconde = 1000 seconden)",
  delay: "wacht",
  clearLCD: "Maak LCD scherm leeg",
  dwenguinoLCD: "Dwenguino LCD %1 %2 %3 Schrijf tekst: %4 Op rij: %5 Vanaf kolom: %6",
  pin: "pin",
  toneOnPin: "Speel toon af op ",
  frequency: "met frequentie",
  noToneOnPin: "Stop toon op",
  toneOnPinTooltip: "Speel een toon met een specifieke frequentie af op een pin",
  noToneOnPinTooltip: "Stop toon op bepaalde pin",
  trig: "trig pin nummer",
  echo: "echo pin nummer",
  sonarTooltip: "Deze blok leest de afstand in van een sonar sensor",
  miliseconds: "ms",
  digitalRead: "Lees digitale waarde van",
  digitalReadTooltip: "Lees een digitale waarde (1/hoog of 0/laag) vanaf een bepaalde pin",
  high: "HOOG",
  low: "LAAG",
  highLowTooltip: "Komt overeen met een hoge (1) of lage (0) waarde op een pin.",
  tutsIntroduction: "Introductie",
  tutsTheremin: "Theremin",
  tutsRobot: "Robot",
  tutsBasicTest: "Basis test",
  simulator: "Simulator",

};

MSG.tutorials = {
    introduction: {},
    theremin: {},
    robot: {},
    basic_test: {}
};

MSG.tutorials.introduction = {
        step1Title: "Welkom bij DwenguinoBlockly",
        step1Content: "Hoi, ik ben Dwenguino! Ik zal jullie helpen om de interface te leren kennen!",
        step2aTitle: "Het Blockly codegebied",
        step2aContent: "Dit is het blockly codegebied",
        step2bTitle: "De Blockly toolbox",
        step2bContent: "Dit is de toolbox. Deze bevat alle blokken die je kan gebruiken om jouw programma te schrijven. Afhankelijk van het niveau dat je gekozen hebt zie je meer of minder blokken. Ga eens op verkenning en bekijk welke blokken er allemaal zijn.",
        step3Title: "Taal instellen",
        step3Content: "Hier kan je een andere taal selecteren",
        step4Title: "De moeilijkheidsgraad",
        step4Content: "Deze schuifbalk kan je gebruiken om De moeilijkheidsgraad in te stellen. Op hogere niveaus heb je meer geavanceerde blokken. Om deze te gebruiken Beheers je best eerst de blokken op lagere niveaus.",
        step5Title: "Dwengobooks",
        step5Content: "Dwengobooks zijn interactieve tutorials die je stap voor stap uitlgeen hoe je een programma moet schrijven. Je leerkracht kan her zelf ook lessen aan toevoegen zodat je makkelijk de lessen kan volgen.",
        step6Title: "Je code uploaden naar het Dwenguino bord",
        step6Content: "Als je denkt dat je programma af is kan je het uploaden naar het Dwenguino bord door op deze knop te drukken. (Vergeet niet om eerst het bord aan te sluiten op de computer met de usb kabel)",
        step7Title: "Openen",
        step7Content: "Deze knop geeft je de mogelijkheid om een bestand dat je eerder hebt opgeslagen te openen in de editor",
        step8Title: "Opslaan",
        step8Content: "Met deze knop kan je de blokken opslaan naar een lokaal bestand",
        step9Title: "De simulator",
        step9Content: "Met deze knop kan je de simulator openen, deze kan je gebruiken om je code eerst te testen voor je ze naar het bord upload."

};

MSG.tutorials.basic_test = {
    step1Title: "Test je basiskennis van Dwenguino",
    step1Content: "Wanneer je nog nooit een programma hebt geschreven voor de Dwenguino kan je deze test gebruiken om te kijken hoe ver je al staat",
    step2Title: "Sequentie",
    step2ContentA: "Bekijk de code die je ziet de blockly workspace. Wat is na het uitvoeren van de code de waarde die in a zit?",
    step2ContentB: "Wat is de waarde die in b zit?",
    stepEndTitle: "Goed zo!",
    stepEndContent: "Je hebt de quiz successvol afgelegd, op naar de volgende!"
};
