name=DwenguinoWIFI
version=1.0.0
author=Tom Neutens <tom@dwengo.org>
maintainer=Tom Neutens <tom@dwengo.org>
sentence=A library that enables the dwenguino to respond to wifi request using an ESP-01 module on the UART connector.
paragraph=
category=Communication
url=https://github.com/dwengovzw/Blockly-for-Dwenguino
architectures=avr,arm
includes=DwenguinoWIFI.h