ARDUINO_DIR = $(shell pwd)
ARDUINO_SKETCHBOOK = $(shell pwd)
ARDUINO_LIBS = Dwenguino Wire SPI LedController LiquidCrystal dht EEPROM LinxDwenguino NewPing Servo SoftwareSerial
ARDUINO_VERSION = 185
BOARD_TAG = dwenguino
MONITOR_PORT = /dev/ttyACM*
ISP_PORT          = usb
ISP_PROG = avrisp2
BOOTLOADER_PARENT = ./hardware/dwenguino/avr/bootloaders
BOOTLOADER_PATH  = dwenguino
BOOTLOADER_FILE  = BootloaderDwenguino-Welcome.hex
BOARD_TAG         = Dwenguino
ARDMK_VENDOR      = dwenguino
ALTERNATE_CORE    = dwenguino
ARDUINO_VAR_PATH  = ./hardware/dwenguino/avr/variants
ARDUINO_CORE_PATH = ./hardware/dwenguino/avr/cores/dwenguino
USER_LIB_PATH = ./hardware/dwenguino/avr/libraries
ARCHITECTURE = avr
ARDUINO_PREFERENCES_PATH = ./preferences.txt

ARDUINO_QUIET = True

include ./Arduino.mk
